<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 2 — Test Bank – Agricultural Data Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../references.html" rel="next">
<link href="../practice/module01_bank.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5e59ab0f76eb8c10b14673f5248a7137.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Agricultural Data Analytics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../feedback.html" aria-current="page"> <i class="bi bi-chat-left-text" role="img">
</i> 
<span class="menu-text">Feedback</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../practice/module01_bank.html">Test Bank</a></li><li class="breadcrumb-item"><a href="../practice/module02_bank.html">Module 2 — Test Bank</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Title page</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction: How to Think About Data Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 1: Introduction to Excel</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module01a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module01b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Working with Data in Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module01c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 2: Introduction to R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module02a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Getting Started with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module02b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Loading Data and Packages in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module02c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Manipulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 3: Getting and Combining Data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Getting Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cleaning Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Merging Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 4: Graphing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module04a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Graphing Best Practices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module04b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Graphing in Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module04c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Graphing in R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 5: Using Artificial Intelligence</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module05a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">AI Tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module05b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">GitHub Copilot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module05c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Graphing with AI</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module05d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">AI Tools in Excel</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 6: Communicating Results</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module06_assignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Report and Presentation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module06a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Making a Workbook Someone Else Can Read</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module06b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Writing a Report</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module06c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Presentations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 7: Spatial Data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module07a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Spatial Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module07b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Querying Earth Engine from R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 8: Relationships Between Variables</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module08a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Seeing Relationships</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module08b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module08c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Linear Models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 9: Probability and Random Variables</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Probability and Random Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 10: Probability and Simulation I</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Probability and Simulation I</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 11: Probability and Simulation II</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Probability and Simulation II</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 12: Sampling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 13: Randomization Tests</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 14: Bootstrap Methods</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Bootstrap Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true">
 <span class="menu-text">Test Bank</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practice/module01_bank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 - Test bank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practice/module02_bank.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 2 — Test Bank</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../feedback.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Feedback</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Appendix</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#section-1-r-basics" id="toc-section-1-r-basics" class="nav-link active" data-scroll-target="#section-1-r-basics">Section 1 — R Basics</a>
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">Question 6</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7</a></li>
  <li><a href="#question-8" id="toc-question-8" class="nav-link" data-scroll-target="#question-8">Question 8</a></li>
  <li><a href="#question-9" id="toc-question-9" class="nav-link" data-scroll-target="#question-9">Question 9</a></li>
  <li><a href="#question-10" id="toc-question-10" class="nav-link" data-scroll-target="#question-10">Question 10</a></li>
  </ul></li>
  <li><a href="#section-2-reading-and-inspecting-data" id="toc-section-2-reading-and-inspecting-data" class="nav-link" data-scroll-target="#section-2-reading-and-inspecting-data">Section 2 — Reading and Inspecting Data</a>
  <ul>
  <li><a href="#saskatchewan-rm-canola" id="toc-saskatchewan-rm-canola" class="nav-link" data-scroll-target="#saskatchewan-rm-canola">Saskatchewan RM Canola</a>
  <ul class="collapse">
  <li><a href="#question-11" id="toc-question-11" class="nav-link" data-scroll-target="#question-11">Question 11</a></li>
  <li><a href="#question-12" id="toc-question-12" class="nav-link" data-scroll-target="#question-12">Question 12</a></li>
  <li><a href="#question-13" id="toc-question-13" class="nav-link" data-scroll-target="#question-13">Question 13</a></li>
  <li><a href="#question-14" id="toc-question-14" class="nav-link" data-scroll-target="#question-14">Question 14</a></li>
  <li><a href="#question-15" id="toc-question-15" class="nav-link" data-scroll-target="#question-15">Question 15</a></li>
  </ul></li>
  <li><a href="#manitoba-wheat-variety" id="toc-manitoba-wheat-variety" class="nav-link" data-scroll-target="#manitoba-wheat-variety">Manitoba Wheat Variety</a>
  <ul class="collapse">
  <li><a href="#question-16" id="toc-question-16" class="nav-link" data-scroll-target="#question-16">Question 16</a></li>
  <li><a href="#question-17" id="toc-question-17" class="nav-link" data-scroll-target="#question-17">Question 17</a></li>
  <li><a href="#question-18" id="toc-question-18" class="nav-link" data-scroll-target="#question-18">Question 18</a></li>
  <li><a href="#question-19" id="toc-question-19" class="nav-link" data-scroll-target="#question-19">Question 19</a></li>
  <li><a href="#question-20" id="toc-question-20" class="nav-link" data-scroll-target="#question-20">Question 20</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#section-3-data-manipulation-functions" id="toc-section-3-data-manipulation-functions" class="nav-link" data-scroll-target="#section-3-data-manipulation-functions">Section 3 — Data Manipulation Functions</a>
  <ul>
  <li><a href="#saskatchewan-rm-crop-yields" id="toc-saskatchewan-rm-crop-yields" class="nav-link" data-scroll-target="#saskatchewan-rm-crop-yields">Saskatchewan RM Crop Yields</a>
  <ul class="collapse">
  <li><a href="#question-21" id="toc-question-21" class="nav-link" data-scroll-target="#question-21">Question 21</a></li>
  <li><a href="#question-22" id="toc-question-22" class="nav-link" data-scroll-target="#question-22">Question 22</a></li>
  <li><a href="#question-23" id="toc-question-23" class="nav-link" data-scroll-target="#question-23">Question 23</a></li>
  <li><a href="#question-24" id="toc-question-24" class="nav-link" data-scroll-target="#question-24">Question 24</a></li>
  <li><a href="#question-25" id="toc-question-25" class="nav-link" data-scroll-target="#question-25">Question 25</a></li>
  </ul></li>
  <li><a href="#manitoba-wheat-variety-1" id="toc-manitoba-wheat-variety-1" class="nav-link" data-scroll-target="#manitoba-wheat-variety-1">Manitoba Wheat Variety</a>
  <ul class="collapse">
  <li><a href="#question-26" id="toc-question-26" class="nav-link" data-scroll-target="#question-26">Question 26</a></li>
  <li><a href="#question-27" id="toc-question-27" class="nav-link" data-scroll-target="#question-27">Question 27</a></li>
  <li><a href="#question-28" id="toc-question-28" class="nav-link" data-scroll-target="#question-28">Question 28</a></li>
  <li><a href="#question-29" id="toc-question-29" class="nav-link" data-scroll-target="#question-29">Question 29</a></li>
  <li><a href="#question-30" id="toc-question-30" class="nav-link" data-scroll-target="#question-30">Question 30</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#section-4-pipelines-and-grouped-summaries" id="toc-section-4-pipelines-and-grouped-summaries" class="nav-link" data-scroll-target="#section-4-pipelines-and-grouped-summaries">Section 4 — Pipelines and Grouped Summaries</a>
  <ul>
  <li><a href="#saskatchewan-rm-crop-yields-1" id="toc-saskatchewan-rm-crop-yields-1" class="nav-link" data-scroll-target="#saskatchewan-rm-crop-yields-1">Saskatchewan RM Crop Yields</a>
  <ul class="collapse">
  <li><a href="#question-31" id="toc-question-31" class="nav-link" data-scroll-target="#question-31">Question 31</a></li>
  <li><a href="#question-32" id="toc-question-32" class="nav-link" data-scroll-target="#question-32">Question 32</a></li>
  <li><a href="#question-33" id="toc-question-33" class="nav-link" data-scroll-target="#question-33">Question 33</a></li>
  <li><a href="#question-34" id="toc-question-34" class="nav-link" data-scroll-target="#question-34">Question 34</a></li>
  <li><a href="#question-35" id="toc-question-35" class="nav-link" data-scroll-target="#question-35">Question 35</a></li>
  </ul></li>
  <li><a href="#manitoba-wheat-variety-2" id="toc-manitoba-wheat-variety-2" class="nav-link" data-scroll-target="#manitoba-wheat-variety-2">Manitoba Wheat Variety</a>
  <ul class="collapse">
  <li><a href="#question-36" id="toc-question-36" class="nav-link" data-scroll-target="#question-36">Question 36</a></li>
  <li><a href="#question-37" id="toc-question-37" class="nav-link" data-scroll-target="#question-37">Question 37</a></li>
  <li><a href="#question-38" id="toc-question-38" class="nav-link" data-scroll-target="#question-38">Question 38</a></li>
  <li><a href="#question-39" id="toc-question-39" class="nav-link" data-scroll-target="#question-39">Question 39</a></li>
  <li><a href="#question-40" id="toc-question-40" class="nav-link" data-scroll-target="#question-40">Question 40</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../practice/module01_bank.html">Test Bank</a></li><li class="breadcrumb-item"><a href="../practice/module02_bank.html">Module 2 — Test Bank</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Module 2 — Test Bank</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How this test bank works
</div>
</div>
<div class="callout-body-container callout-body">
<p>This bank holds <strong>40 questions</strong>, ten in each section. Section 1 gives you the data inside the question; Sections 2–4 each hold two blocks of five, one block per dataset (the datasets are described below). On the real test you receive <strong>four questions – one from each section</strong> – and you submit <strong>a single, well-commented R script</strong>: a header block at the top, a clearly labelled section for each question, and your sentence answers written as comments. The script should run from top to bottom in a project folder that has the csvs in <code>data/</code>. Each question is designed to take about <strong>8–10 minutes</strong>.</p>
<p>Expand each <strong>Answer</strong> block to check your work. Every value has been computed from the real data; if the source file is refreshed the exact numbers may shift slightly, but the method stays the same.</p>
</div>
</div>
<p><strong>The data.</strong> Two datasets, four files, all in your project’s <code>data/</code> folder:</p>
<p><em>Saskatchewan RM crop yields</em> – average yields in every Saskatchewan Rural Municipality, one row per RM-year(-crop), columns <code>Year</code>, <code>RM</code>, <code>Crop</code>, <code>Yield</code>, <code>Unit</code>:</p>
<ul>
<li><a href="data/rm_canola_yields_1990_2025.csv"><code>rm_canola_yields_1990_2025.csv</code></a> – the <strong>canola rows only</strong>, for Section 2: one crop, one unit, so its summary statistics mean something.</li>
<li><a href="data/rm_yields_1990_2025.csv"><code>rm_yields_1990_2025.csv</code></a> – all <strong>eight crops</strong>, for Sections 3–4. You worked with the wide version in Module 1; this is the long form, with <code>Crop</code> as a variable. <strong>Lentils are recorded in pounds per acre; every other crop is in bushels per acre</strong> – the <code>Unit</code> column says which, and several questions turn on it.</li>
</ul>
<p><em>Manitoba wheat variety yields</em> – MASC’s variety-level spring wheat yields, one row per municipality-variety-year, 2020–2025, columns <code>Year</code>, <code>Municipality</code>, <code>Variety</code>, <code>Farms</code>, <code>Acres</code>, <code>Yield_bu_ac</code>, <code>Reported</code>. Where too few farms grew a variety, the row is <strong>suppressed</strong> for privacy: <code>Reported</code> is FALSE and the numeric columns are missing.</p>
<ul>
<li><a href="data/mb_wheat_reported_2020_2025.csv"><code>mb_wheat_reported_2020_2025.csv</code></a> – the <strong>reported rows only</strong>, for Section 2.</li>
<li><a href="data/mb_wheat_varieties.csv"><code>mb_wheat_varieties.csv</code></a> – the <strong>full file</strong>, suppressed rows included, for Sections 3–4.</li>
</ul>
<p><strong>Grading model.</strong> <strong>20%</strong> for script presentation – a header block, comments in the style of the module, clearly labelled question sections, and a script that runs from top to bottom in a fresh session. The remaining <strong>80%</strong> is split evenly across the four questions, and evenly across the parts within each question. Parts are marked on <strong>follow-through</strong>: if an early part is wrong but the later parts are correctly worked <em>from your own earlier answer</em>, the later parts still earn full marks. Where a part asks for a sentence, write it as a comment in your script.</p>
<blockquote class="blockquote">
<p><strong>Vocabulary note.</strong> Everything here uses only Module 2 tools: <code>&lt;-</code>, arithmetic on vectors, <code>c()</code>, <code>data.frame()</code>, <code>$</code>, <code>mean</code>, <code>median</code>, <code>sd</code>, <code>var</code>, <code>min</code>, <code>max</code>, <code>range</code>, <code>sum</code>, <code>quantile</code> (with <code>probs</code>), <code>IQR</code>, <code>nrow</code>, <code>ncol</code>, <code>names</code>, <code>head</code>, <code>print</code>, <code>glimpse</code>, <code>summary</code>, <code>library()</code>, <code>install.packages()</code>, <code>read_csv</code> with relative paths, <code>filter</code> (with <code>==</code>, <code>&gt;</code>, <code>&lt;</code>, <code>&gt;=</code>, <code>&amp;</code>, <code>|</code>, <code>!</code>, <code>%in%</code>), <code>select</code> (including <code>-</code> and <code>:</code>), <code>rename</code>, <code>mutate</code>, <code>arrange</code> and <code>desc</code>, the pipe <code>|&gt;</code>, <code>summarise</code>, <code>n()</code>, <code>group_by</code>, and <code>write_csv</code>. Nothing beyond that is needed. The chapter’s <code>summarise()</code> examples write <code>na.rm = TRUE</code> inside <code>mean()</code> and <code>sd()</code>; none of the data these questions filter to has missing yields, so answers with or without it get the same numbers and the same marks.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A sample test, with a full-marks answer script
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A real test looks like this – one question from each section:</p>
<ol type="1">
<li><em>Five canola fields yielded 52.3, 47.8, 55.1, 44.6, and 50.9 bu/ac, on 160, 320, 240, 130, and 200 acres. Create the two vectors; convert the yields to t/ha; compute the mean and sd of the yields; compute total production and the acreage-weighted average yield.</em></li>
<li><em>Compute the mean, median, and standard deviation of canola <code>Yield</code>, and its 90th percentile. In a comment: the mean sits a little above the median – what does that direction of gap suggest about the shape of canola yields?</em></li>
<li><em>Filter to the lentil rows, saving as <code>lentils</code> (how many rows?); add a <code>yield_kg_ha</code> column (multiply by 1.12), saving back to <code>lentils</code>; compute the mean of the new column and of the original, and check their ratio.</em></li>
<li><em>In one pipeline, compute each RM’s mean Spring Wheat yield across all years, sorted best-first. Report the top three RMs. In a comment: what did each row of the input represent, and what does each row of the result represent?</em></li>
</ol>
<p>And here is a script that would earn full marks, including all of the presentation component – with the console session it produces shown beneath it:</p>
<div class="cell">
<div class="cell-output-display">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Title: Module 2 test</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Author: Jordan Field</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Date: 2026-10-15</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Description:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   Answers to the four test questions, one section per block.</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#   Sentence answers are written as comments below each result.</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># ---</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Section 1: five canola fields</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Yields (bu/ac) and field sizes (acres)</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>yields <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">52.3</span>, <span class="fl">47.8</span>, <span class="fl">55.1</span>, <span class="fl">44.6</span>, <span class="fl">50.9</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>acres  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">160</span>, <span class="dv">320</span>, <span class="dv">240</span>, <span class="dv">130</span>, <span class="dv">200</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># (a/b) Convert every yield to tonnes per hectare in one step</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>yields_t_ha <span class="ot">&lt;-</span> yields <span class="sc">*</span> <span class="fl">0.0560</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>yields_t_ha</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># (c) Centre and spread of the yields</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(yields)   <span class="co"># 50.14 bu/ac</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(yields)     <span class="co"># 4.06 bu/ac</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co"># (d) Total production, then the average weighted by acres</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>total_bu <span class="ot">&lt;-</span> <span class="fu">sum</span>(yields <span class="sc">*</span> acres)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>total_bu                 <span class="co"># 52,866 bu</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>total_bu <span class="sc">/</span> <span class="fu">sum</span>(acres)    <span class="co"># 50.35 bu/ac</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co"># The weighted average differs from the plain mean because the</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co"># fields differ in size, so each yield should count by its acres.</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Section 2: summary statistics for canola</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the canola file using a relative path from the project folder</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>rm_canola <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rm_canola_yields_1990_2025.csv"</span>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Centre and spread of the canola yields</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(rm_canola<span class="sc">$</span>Yield)      <span class="co"># 28.29 bu/ac</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(rm_canola<span class="sc">$</span>Yield)    <span class="co"># 26.9 bu/ac</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(rm_canola<span class="sc">$</span>Yield)        <span class="co"># 10.06 bu/ac</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="co"># 90th percentile</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(rm_canola<span class="sc">$</span>Yield, <span class="fl">0.9</span>)   <span class="co"># 42.5 bu/ac</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="co"># The mean sits a little above the median, which suggests mild</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="co"># right skew: the best RM-years pull the mean up more than the</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="co"># worst years pull it down.</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Section 3: converting the lentil yields</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the full eight-crop file</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>rm_yields <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rm_yields_1990_2025.csv"</span>)</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only the lentil rows</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>lentils <span class="ot">&lt;-</span> <span class="fu">filter</span>(rm_yields, Crop <span class="sc">==</span> <span class="st">"Lentils"</span>)</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(lentils)    <span class="co"># 6,338 rows</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the converted column (1 lb/ac is about 1.12 kg/ha) and</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="co"># overwrite lentils with the version that has the extra column</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>lentils <span class="ot">&lt;-</span> <span class="fu">mutate</span>(lentils, <span class="at">yield_kg_ha =</span> Yield <span class="sc">*</span> <span class="fl">1.12</span>)</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="co"># Means of the new and original columns</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(lentils<span class="sc">$</span>yield_kg_ha)   <span class="co"># 1,353.4 kg/ha</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(lentils<span class="sc">$</span>Yield)         <span class="co"># 1,208.39 lb/ac</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="co"># Their ratio is 1.12, the conversion factor -- multiplying every</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="co"># value by a constant multiplies the mean by the same constant.</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="co"># Section 4: best wheat-growing RMs</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>rm_yields <span class="sc">|&gt;</span>                              <span class="co"># take the data, THEN</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Crop <span class="sc">==</span> <span class="st">"Spring Wheat"</span>) <span class="sc">|&gt;</span>       <span class="co"># keep spring wheat, THEN</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(RM) <span class="sc">|&gt;</span>                         <span class="co"># split the rows by RM, THEN</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_yield =</span> <span class="fu">mean</span>(Yield)) <span class="sc">|&gt;</span>  <span class="co"># one row per RM: its mean, THEN</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_yield))               <span class="co"># best RMs on top</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="co"># Top three: RM 369 (47.6), RM 333 (47.2), RM 368 (47.2) bu/ac.</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="co"># Each input row was one RM-year observation of spring wheat; each</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="co"># result row is one RM, its years collapsed into a single mean.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="console-transcript">
<pre><code>&gt; # ---
&gt; # Title: Module 2 test
&gt; # Author: Jordan Field
&gt; # Date: 2026-10-15
&gt; # Description:
&gt; #   Answers to the four test questions, one section per block.
&gt; #   Sentence answers are written as comments below each result.
&gt; # ---
&gt; 
&gt; # Load packages
&gt; library(tidyverse)
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors
&gt; 
&gt; # ============================================================
&gt; # Section 1: five canola fields
&gt; # ============================================================
&gt; 
&gt; # Yields (bu/ac) and field sizes (acres)
&gt; yields &lt;- c(52.3, 47.8, 55.1, 44.6, 50.9)
&gt; acres  &lt;- c(160, 320, 240, 130, 200)
&gt; 
&gt; # (a/b) Convert every yield to tonnes per hectare in one step
&gt; yields_t_ha &lt;- yields * 0.0560
&gt; yields_t_ha
[1] 2.9288 2.6768 3.0856 2.4976 2.8504
&gt; 
&gt; # (c) Centre and spread of the yields
&gt; mean(yields)   # 50.14 bu/ac
[1] 50.14
&gt; sd(yields)     # 4.06 bu/ac
[1] 4.062388
&gt; 
&gt; # (d) Total production, then the average weighted by acres
&gt; total_bu &lt;- sum(yields * acres)
&gt; total_bu                 # 52,866 bu
[1] 52866
&gt; total_bu / sum(acres)    # 50.35 bu/ac
[1] 50.34857
&gt; # The weighted average differs from the plain mean because the
&gt; # fields differ in size, so each yield should count by its acres.
&gt; 
&gt; # ============================================================
&gt; # Section 2: summary statistics for canola
&gt; # ============================================================
&gt; 
&gt; # Read the canola file using a relative path from the project folder
&gt; rm_canola &lt;- read_csv("data/rm_canola_yields_1990_2025.csv")
Rows: 10039 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Crop, Unit
dbl (3): Year, RM, Yield

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
&gt; 
&gt; # Centre and spread of the canola yields
&gt; mean(rm_canola$Yield)      # 28.29 bu/ac
[1] 28.29239
&gt; median(rm_canola$Yield)    # 26.9 bu/ac
[1] 26.9
&gt; sd(rm_canola$Yield)        # 10.06 bu/ac
[1] 10.06019
&gt; 
&gt; # 90th percentile
&gt; quantile(rm_canola$Yield, 0.9)   # 42.5 bu/ac
 90% 
42.5 
&gt; 
&gt; # The mean sits a little above the median, which suggests mild
&gt; # right skew: the best RM-years pull the mean up more than the
&gt; # worst years pull it down.
&gt; 
&gt; # ============================================================
&gt; # Section 3: converting the lentil yields
&gt; # ============================================================
&gt; 
&gt; # Read the full eight-crop file
&gt; rm_yields &lt;- read_csv("data/rm_yields_1990_2025.csv")
Rows: 71104 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Crop, Unit
dbl (3): Year, RM, Yield

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
&gt; 
&gt; # Keep only the lentil rows
&gt; lentils &lt;- filter(rm_yields, Crop == "Lentils")
&gt; nrow(lentils)    # 6,338 rows
[1] 6338
&gt; 
&gt; # Add the converted column (1 lb/ac is about 1.12 kg/ha) and
&gt; # overwrite lentils with the version that has the extra column
&gt; lentils &lt;- mutate(lentils, yield_kg_ha = Yield * 1.12)
&gt; 
&gt; # Means of the new and original columns
&gt; mean(lentils$yield_kg_ha)   # 1,353.4 kg/ha
[1] 1353.402
&gt; mean(lentils$Yield)         # 1,208.39 lb/ac
[1] 1208.395
&gt; # Their ratio is 1.12, the conversion factor -- multiplying every
&gt; # value by a constant multiplies the mean by the same constant.
&gt; 
&gt; # ============================================================
&gt; # Section 4: best wheat-growing RMs
&gt; # ============================================================
&gt; 
&gt; rm_yields |&gt;                              # take the data, THEN
+   filter(Crop == "Spring Wheat") |&gt;       # keep spring wheat, THEN
+   group_by(RM) |&gt;                         # split the rows by RM, THEN
+   summarise(mean_yield = mean(Yield)) |&gt;  # one row per RM: its mean, THEN
+   arrange(desc(mean_yield))               # best RMs on top
# A tibble: 298 × 2
      RM mean_yield
   &lt;dbl&gt;      &lt;dbl&gt;
 1   369       47.6
 2   333       47.2
 3   368       47.2
 4   271       46.1
 5   303       45.0
 6   427       45.0
 7   404       44.9
 8   496       44.8
 9   493       44.6
10   338       44.5
# ℹ 288 more rows
&gt; 
&gt; # Top three: RM 369 (47.6), RM 333 (47.2), RM 368 (47.2) bu/ac.
&gt; # Each input row was one RM-year observation of spring wheat; each
&gt; # result row is one RM, its years collapsed into a single mean.</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
<hr>
<section id="section-1-r-basics" class="level1">
<h1>Section 1 — R Basics</h1>
<p><em>These questions are about the building blocks: objects, vectors, data frames, and functions. No data file is needed – the numbers are in the question. Answer in the Section 1 block of your script, with sentence answers written as comments.</em></p>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<p>Five canola fields yielded 52.3, 47.8, 55.1, 44.6, and 50.9 bu/ac, on 160, 320, 240, 130, and 200 acres.</p>
<p><strong>(a)</strong> Create a vector <code>yields</code> and a vector <code>acres</code> holding these values.</p>
<p><strong>(b)</strong> Create a vector <code>yields_t_ha</code> converting the yields to tonnes per hectare (multiply by 0.0560). in one line (R multiplies every element at once).</p>
<p><strong>(c)</strong> Compute the mean and standard deviation of <code>yields</code>.</p>
<p><strong>(d)</strong> Compute total production in bushels (each field’s yield times its acres, summed), and the farm’s average yield weighted by acres (total bushels divided by total acres).</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>yields <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">52.3</span>, <span class="fl">47.8</span>, <span class="fl">55.1</span>, <span class="fl">44.6</span>, <span class="fl">50.9</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>acres  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">160</span>, <span class="dv">320</span>, <span class="dv">240</span>, <span class="dv">130</span>, <span class="dv">200</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>yields_t_ha <span class="ot">&lt;-</span> yields <span class="sc">*</span> <span class="fl">0.0560</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(yields)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(yields)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>total_bu <span class="ot">&lt;-</span> <span class="fu">sum</span>(yields <span class="sc">*</span> acres)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>total_bu <span class="sc">/</span> <span class="fu">sum</span>(acres)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li>2.93, 2.68, 3.09, 2.50, 2.85 t/ha.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Mean <strong>50.14</strong>, sd <strong>4.06</strong>.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Total <strong>52,866 bu</strong>; weighted average <strong>50.35 bu/ac</strong>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<p>Five barley fields yielded 68.2, 71.5, 64.9, 74.1, and 66.3 bu/ac. Five lentil fields yielded 1450, 1720, 1280, 1610, and 1390 lb/ac.</p>
<p><strong>(a)</strong> Compute the mean, the standard deviation, the variance, and the range (maximum minus minimum) of each crop’s yields.</p>
<p><strong>(b)</strong> The lentil standard deviation is far larger. In a comment: why can the two standard deviations not be compared directly?</p>
<p><strong>(c)</strong> Compute the coefficient of variation (sd divided by mean) for each crop. Which crop’s yields are more variable <em>relative to their own average</em>?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>barley  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">68.2</span>, <span class="fl">71.5</span>, <span class="fl">64.9</span>, <span class="fl">74.1</span>, <span class="fl">66.3</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>lentils <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1450</span>, <span class="dv">1720</span>, <span class="dv">1280</span>, <span class="dv">1610</span>, <span class="dv">1390</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(barley)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(lentils)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(barley) <span class="sc">-</span> <span class="fu">min</span>(barley)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(lentils) <span class="sc">-</span> <span class="fu">min</span>(lentils)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(barley) <span class="sc">/</span> <span class="fu">mean</span>(barley)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(lentils) <span class="sc">/</span> <span class="fu">mean</span>(lentils)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li>Barley mean <strong>69.0</strong>, sd <strong>3.77</strong>, variance <strong>14.25</strong>, range <strong>9.2</strong>; lentils mean <strong>1490</strong>, sd <strong>175.36</strong>, variance <strong>30,750</strong>, range <strong>440</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>They are in different units (bushels vs pounds per acre) and on very different scales, so the raw spreads are not comparable.</li>
</ol></li>
<li><ol start="3" type="a">
<li>CV barley <strong>0.055</strong>, lentils <strong>0.118</strong> – lentil yields are more variable relative to their own average.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<p>A trial records, for each field: the crop grown, the seeded acres, and whether the field was irrigated.</p>
<p><strong>(a)</strong> Create three vectors of length four holding made-up values for these three variables, choosing the appropriate type for each (character, numeric, logical).</p>
<p><strong>(b)</strong> In a comment: which values needed quotation marks and which must not have them?</p>
<p><strong>(c)</strong> Combine your three vectors into a data frame called <code>trial</code> and print it.</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>crop      <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Canola"</span>, <span class="st">"Wheat"</span>, <span class="st">"Peas"</span>, <span class="st">"Canola"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>acres     <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">160</span>, <span class="dv">320</span>, <span class="dv">240</span>, <span class="dv">130</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>irrigated <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span>, <span class="cn">TRUE</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>trial <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">crop =</span> crop,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">acres =</span> acres,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">irrigated =</span> irrigated)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>trial</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li>The character values (crop names) need quotes. Numbers must not have them (quoted numbers become text), and <code>TRUE</code>/<code>FALSE</code> must not have them – quoted, they would be text rather than logical values.</li>
</ol></li>
</ul>
</details>
<hr>
</section>
<section id="question-4" class="level3">
<h3 class="anchored" data-anchor-id="question-4">Question 4</h3>
<p>Twelve canola fields yielded 24.1, 31.5, 28.8, 35.2, 22.7, 30.4, 27.9, 33.6, 25.5, 29.3, 32.8, and 26.4 bu/ac.</p>
<p><strong>(a)</strong> Save the values as a vector and compute the mean.</p>
<p><strong>(b)</strong> Compute the 10th, 50th, and 90th percentiles in a single <code>quantile()</code> call.</p>
<p><strong>(c)</strong> In a comment: one of your three percentiles should equal the median. Which one, and does it?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>canola <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">24.1</span>, <span class="fl">31.5</span>, <span class="fl">28.8</span>, <span class="fl">35.2</span>, <span class="fl">22.7</span>, <span class="fl">30.4</span>, <span class="fl">27.9</span>, <span class="fl">33.6</span>, <span class="fl">25.5</span>, <span class="fl">29.3</span>, <span class="fl">32.8</span>, <span class="fl">26.4</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(canola)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(canola, <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.5</span>, <span class="fl">0.9</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li>Mean <strong>29.02</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>10th <strong>24.24</strong>, 50th <strong>29.05</strong>, 90th <strong>33.52</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>The 50th percentile is the median by definition; <code>median(canola)</code> confirms <strong>29.05</strong>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-5" class="level3">
<h3 class="anchored" data-anchor-id="question-5">Question 5</h3>
<p>Consider these three lines:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>k <span class="sc">==</span> <span class="dv">30</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">60</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>(a)</strong> In a comment: say what each line does and what, if anything, it prints.</p>
<p><strong>(b)</strong> In a comment: after the third line runs, does an object called <code>x</code> appear in the Variables pane? Why or why not?</p>
<p><strong>(c)</strong> In a comment: which single symbol would you change to make line 2 <em>assign</em> 30 to <code>k</code>, and which does this book prefer for assignment?</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Line 1 assigns 25 to <code>k</code> (prints nothing). Line 2 asks whether <code>k</code> equals 30 and prints <code>[1] FALSE</code>. Line 3 computes a mean and prints <code>[1] 30</code>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>No – the <code>x =</code> inside the call names an argument for <code>mean()</code>; it does not create an object.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>==</code> would become <code>&lt;-</code> (or <code>=</code>, which also assigns) – and the book uses <code>&lt;-</code> for assignment.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-6" class="level3">
<h3 class="anchored" data-anchor-id="question-6">Question 6</h3>
<p><strong>(a)</strong> <code>mean()</code> takes its data as an argument named <code>x</code>. Write two calls that compute the mean of 12, 18, and 30 – one with the argument unnamed, one with it named – and confirm they agree.</p>
<p><strong>(b)</strong> In a comment: what do you type to open the documentation for <code>sd()</code>?</p>
<p><strong>(c)</strong> A classmate writes <code>Mean(c(12, 18, 30))</code> and R replies <code>could not find function "Mean"</code>. In a comment: what went wrong?</p>
<p><strong>(d)</strong> Compute the standard deviation of the same three values, with the argument named.</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">18</span>, <span class="dv">30</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">18</span>, <span class="dv">30</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">18</span>, <span class="dv">30</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li>Both print <code>[1] 20</code>.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>?sd</code>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>R is exact about names: <code>Mean</code> with a capital M is not the same function as <code>mean</code>.</li>
</ol></li>
<li><ol start="4" type="a">
<li><code>[1] 9.165151</code>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-7" class="level3">
<h3 class="anchored" data-anchor-id="question-7">Question 7</h3>
<p>Four oat fields yielded 84.3, 91.7, 77.2, and 88.5 bu/ac, and oats are selling at $4.15 per bushel.</p>
<p><strong>(a)</strong> Save the yields as a vector and the price as a single object.</p>
<p><strong>(b)</strong> Compute a revenue-per-acre vector (yield times price) in one line, using the price object rather than retyping the number.</p>
<p><strong>(c)</strong> Compute the mean revenue per acre.</p>
<p><strong>(d)</strong> In a comment: the price rises to $4.60. What two lines would you rerun to update every answer, and why is that easier than if you had typed the price into each formula?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>yields <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">84.3</span>, <span class="fl">91.7</span>, <span class="fl">77.2</span>, <span class="fl">88.5</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>price  <span class="ot">&lt;-</span> <span class="fl">4.15</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>revenue <span class="ot">&lt;-</span> yields <span class="sc">*</span> price</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>revenue</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(revenue)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li>349.85, 380.56, 320.38, 367.28 $/ac, rounded to the cent (the console shows 349.845 and so on).</li>
</ol></li>
<li><ol start="3" type="a">
<li>Mean <strong>$354.51</strong> per acre.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Change <code>price &lt;- 4.60</code>, then rerun the lines below it. The price lives in one object, so one edit updates everything – the same reason a spreadsheet keeps a price in one cell.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-8" class="level3">
<h3 class="anchored" data-anchor-id="question-8">Question 8</h3>
<p><strong>(a)</strong> Build a data frame called <code>durum_fields</code> with columns <code>field_id</code> (<code>"D1"</code> to <code>"D4"</code>), <code>region</code> (South, South, Central, North), and <code>yield</code> (28.3, 41.6, 35.2, 44.8).</p>
<p><strong>(b)</strong> Report its number of rows, number of columns, and column names using functions.</p>
<p><strong>(c)</strong> Using <code>$</code>, compute the mean yield and the range (maximum minus minimum).</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>durum_fields <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">field_id =</span> <span class="fu">c</span>(<span class="st">"D1"</span>, <span class="st">"D2"</span>, <span class="st">"D3"</span>, <span class="st">"D4"</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">region =</span> <span class="fu">c</span>(<span class="st">"South"</span>, <span class="st">"South"</span>, <span class="st">"Central"</span>, <span class="st">"North"</span>),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">yield =</span> <span class="fu">c</span>(<span class="fl">28.3</span>, <span class="fl">41.6</span>, <span class="fl">35.2</span>, <span class="fl">44.8</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(durum_fields); <span class="fu">ncol</span>(durum_fields); <span class="fu">names</span>(durum_fields)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(durum_fields<span class="sc">$</span>yield)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(durum_fields<span class="sc">$</span>yield) <span class="sc">-</span> <span class="fu">min</span>(durum_fields<span class="sc">$</span>yield)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li>4 rows, 3 columns; <code>field_id</code>, <code>region</code>, <code>yield</code>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Mean <strong>37.48</strong>; range <strong>16.5</strong>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-9" class="level3">
<h3 class="anchored" data-anchor-id="question-9">Question 9</h3>
<p>A student runs these lines in the console:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bins <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1450</span>, <span class="dv">2200</span>, <span class="dv">1875</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>bins <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">sum</span>(bins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>(a)</strong> In a comment: what exactly does the second line print, <code>[1]</code> included, and is that doubled vector saved anywhere?</p>
<p><strong>(b)</strong> In a comment: what does the third line print, and what does the Variables pane show afterwards?</p>
<p><strong>(c)</strong> The student now wants the doubled vector kept for later. Write the line that does it.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li><code>[1] 2900 4400 3750</code> – displayed only, saved nowhere.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Nothing prints (it is an assignment); the pane shows <code>bins</code> (the three values) and <code>total</code> = 5525.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>bins_doubled &lt;- bins * 2</code>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-10" class="level3">
<h3 class="anchored" data-anchor-id="question-10">Question 10</h3>
<p>Here is a working script:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>v1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">47.2</span>, <span class="fl">49.8</span>, <span class="fl">46.5</span>, <span class="fl">50.1</span>, <span class="fl">48.4</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>v2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">38.9</span>, <span class="fl">55.6</span>, <span class="fl">44.2</span>, <span class="fl">58.3</span>, <span class="fl">41.0</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(v1)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(v2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>(a)</strong> Rewrite it with a header and comments. The two vectors are canola yields from Farm A and Farm B.</p>
<p><strong>(b)</strong> Add lines computing each farm’s standard deviation and range.</p>
<p><strong>(c)</strong> In a comment: the two farms have nearly the same mean. Using your numbers from (b), say in one sentence how they differ.</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Title: Comparing two canola farms</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Author: Your Name</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Date: 2026-10-08</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Description:</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   Compares the centre and spread of canola yields</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co">#   on Farm A and Farm B.</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># ---</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Canola yields by field (bu/ac)</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>farm_a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">47.2</span>, <span class="fl">49.8</span>, <span class="fl">46.5</span>, <span class="fl">50.1</span>, <span class="fl">48.4</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>farm_b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">38.9</span>, <span class="fl">55.6</span>, <span class="fl">44.2</span>, <span class="fl">58.3</span>, <span class="fl">41.0</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Centre</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(farm_a)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(farm_b)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Spread</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(farm_a)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(farm_b)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(farm_a) <span class="sc">-</span> <span class="fu">min</span>(farm_a)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(farm_b) <span class="sc">-</span> <span class="fu">min</span>(farm_b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li>Farm A sd <strong>1.57</strong>, range <strong>3.6</strong>; Farm B sd <strong>8.79</strong>, range <strong>19.4</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>The means are close (48.4 vs 47.6), but Farm B’s yields swing far more from field to field – its spread is five times Farm A’s.</li>
</ol></li>
</ul>
</details>
</section>
</section>
<section id="section-2-reading-and-inspecting-data" class="level1">
<h1>Section 2 — Reading and Inspecting Data</h1>
<p><em>Three blocks of ten, one per dataset. Each block starts by naming its file; on a real test your Section 2 question comes from one of the three. Answer in the Section 2 block of your script.</em></p>
<section id="saskatchewan-rm-canola" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="saskatchewan-rm-canola">Saskatchewan RM Canola</h2>
<p><em>These questions use the canola-only file, <a href="data/rm_canola_yields_1990_2025.csv"><code>rm_canola_yields_1990_2025.csv</code></a>, in your project’s <code>data/</code> folder.</em></p>
<section id="question-11" class="level3">
<h3 class="anchored" data-anchor-id="question-11">Question 11</h3>
<p><strong>(a)</strong> In a comment at the top of your script, sketch your project’s folder layout (the subfolders and where the csv sits).</p>
<p><strong>(b)</strong> Load the tidyverse and read the canola file into an object called <code>rm_canola</code>, using a relative path.</p>
<p><strong>(c)</strong> Report the number of rows, the number of columns, and the column names using functions.</p>
<p><strong>(d)</strong> In a comment: why will your <code>read_csv()</code> line work on the grader’s computer, when a full path starting <code>C:/Users/...</code> would not?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>rm_canola <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rm_canola_yields_1990_2025.csv"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(rm_canola); <span class="fu">ncol</span>(rm_canola); <span class="fu">names</span>(rm_canola)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="3" type="a">
<li><strong>10,039 rows</strong>, <strong>5 columns</strong>: <code>Year</code>, <code>RM</code>, <code>Crop</code>, <code>Yield</code>, <code>Unit</code>.</li>
</ol></li>
<li><ol start="4" type="a">
<li>The path is relative to the project folder, and the grader opens the same self-contained folder – so <code>data/...</code> exists on their machine too. An absolute path names one particular computer’s user and folder layout.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-12" class="level3">
<h3 class="anchored" data-anchor-id="question-12">Question 12</h3>
<p><strong>(a)</strong> Run <code>glimpse()</code> on <code>rm_canola</code>. In a comment: which columns are text (<code>&lt;chr&gt;</code>) and which are numeric (<code>&lt;dbl&gt;</code>)?</p>
<p><strong>(b)</strong> When <code>read_csv()</code> ran, it printed a note about the file. In a comment: what did that note report, and why does the module say to read it every time?</p>
<p><strong>(c)</strong> <code>Year</code> came in as numeric (<code>&lt;dbl&gt;</code>). In a comment: which type of value is each of <code>2024</code> and <code>"2024"</code>? Why do we want a column we will compute with stored as numbers rather than as text?</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li><code>Crop</code> and <code>Unit</code> are <code>&lt;chr&gt;</code>; <code>Year</code>, <code>RM</code>, and <code>Yield</code> are <code>&lt;dbl&gt;</code>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>The row and column counts and its guess at each column’s type (here <code>chr (2)</code> and <code>dbl (3)</code>). R guesses well but not perfectly, so the note is the first check that the file read the way you expect.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>2024</code> is numeric; <code>"2024"</code> is character (text). Numbers stored as text stop behaving like numbers – you cannot do arithmetic with them, and sorting turns alphabetical – so a column you will compute with should show <code>&lt;dbl&gt;</code>, not <code>&lt;chr&gt;</code>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-13" class="level3">
<h3 class="anchored" data-anchor-id="question-13">Question 13</h3>
<p><strong>(a)</strong> Run <code>summary(rm_canola)</code>. From its output, report the minimum, median, and maximum of <code>Yield</code>, and the first and last <code>Year</code>.</p>
<p><strong>(b)</strong> In a comment: work through the module’s inspection questions for this file. Are the yields in between roughly 10 and 60 bu/ac, a typical canola range? Are the years what the file name promises? Are there missing values?</p>
<p><strong>(c)</strong> The minimum is below 2 bu/ac. In a comment: is a canola yield that low necessarily a data error? What kind of year could produce it?</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Yield: min <strong>1.9</strong>, median <strong>26.9</strong>, max <strong>61</strong>. Years <strong>1990</strong> to <strong>2025</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Yes – everything sits between about 2 and 61 bu/ac, sensible for canola; the years run 1990–2025 as advertised; and <code>summary()</code> prints an <code>NA's</code> count only when a column has missing values – no such line appears, so there are none.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Not necessarily – an RM average that low is what a severe drought or a widespread crop failure looks like. Extreme is not the same as wrong; it is a value to investigate, not delete.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-14" class="level3">
<h3 class="anchored" data-anchor-id="question-14">Question 14</h3>
<p><strong>(a)</strong> Compute the mean, median, standard deviation, and variance of <code>rm_canola$Yield</code>.</p>
<p><strong>(b)</strong> Compute the 90th percentile of <code>Yield</code>.</p>
<p><strong>(c)</strong> The mean sits a little above the median. In a comment: using Module 1’s language about means and medians, what does that direction of gap suggest about the shape of canola yields?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(rm_canola<span class="sc">$</span>Yield)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(rm_canola<span class="sc">$</span>Yield)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(rm_canola<span class="sc">$</span>Yield)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(rm_canola<span class="sc">$</span>Yield)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(rm_canola<span class="sc">$</span>Yield, <span class="fl">0.9</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li>Mean <strong>28.29</strong>, median <strong>26.9</strong>, sd <strong>10.06</strong>, variance <strong>101.21</strong> (the sd squared, in squared units).</li>
</ol></li>
<li><ol start="2" type="a">
<li>90th percentile <strong>42.5</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>A mean above the median suggests mild right skew: the very best RM-years pull the mean up more than the worst years pull it down.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-15" class="level3">
<h3 class="anchored" data-anchor-id="question-15">Question 15</h3>
<p>A classmate’s fresh R session runs <code>rm_yields &lt;- read_csv("data/rm_yields_1990_2025.csv")</code> and gets:</p>
<pre><code>Error in read_csv(...) : could not find function "read_csv"</code></pre>
<p><strong>(a)</strong> In a comment: what is the most likely cause, and what one line fixes it?</p>
<p><strong>(b)</strong> In a comment: they object, “but I installed the tidyverse last week!” Explain the difference between installing and loading, and how often each is done.</p>
<p><strong>(c)</strong> In a comment: state the quotes rule – where do quotation marks go when installing, and when loading?</p>
<p><strong>(d)</strong> The tidyverse is a collection of packages. In comments, name the four core ones from the module and the job each does.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>The package is not loaded in this session; run <code>library(tidyverse)</code> first.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Installing downloads the package onto the computer – once per computer. Loading switches it on – once per script or session. Installation does not carry across sessions as loaded.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Quotes when you install (<code>install.packages("tidyverse")</code>), none when you load (<code>library(tidyverse)</code>).</li>
</ol></li>
<li><ol start="4" type="a">
<li><code>readr</code> reads data, <code>dplyr</code> manipulates it, <code>tidyr</code> reshapes it, <code>ggplot2</code> makes graphs.</li>
</ol></li>
</ul>
</details>
</section>
</section>
<section id="manitoba-wheat-variety" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="manitoba-wheat-variety">Manitoba Wheat Variety</h2>
<p><em>These questions use <a href="data/mb_wheat_reported_2020_2025.csv"><code>mb_wheat_reported_2020_2025.csv</code></a> – spring wheat yields by variety and municipality, reported observations only.</em></p>
<section id="question-16" class="level3">
<h3 class="anchored" data-anchor-id="question-16">Question 16</h3>
<p><strong>(a)</strong> In a comment at the top of your script, sketch your project’s folder layout.</p>
<p><strong>(b)</strong> Load the tidyverse and read the file into an object called <code>mb_wheat</code>, using a relative path.</p>
<p><strong>(c)</strong> Report the number of rows, the number of columns, and the column names using functions.</p>
<p><strong>(d)</strong> In a comment: what does one row of this dataset represent?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>mb_wheat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/mb_wheat_reported_2020_2025.csv"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mb_wheat); <span class="fu">ncol</span>(mb_wheat); <span class="fu">names</span>(mb_wheat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="3" type="a">
<li><strong>2,398 rows</strong>, <strong>7 columns</strong>: <code>Year</code>, <code>Municipality</code>, <code>Variety</code>, <code>Farms</code>, <code>Acres</code>, <code>Yield_bu_ac</code>, <code>Reported</code>.</li>
</ol></li>
<li><ol start="4" type="a">
<li>One wheat variety grown in one municipality in one year – its farm count, acres, and average yield.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-17" class="level3">
<h3 class="anchored" data-anchor-id="question-17">Question 17</h3>
<p>A classmate’s script reads the data like this:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mb_wheat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"/Users/sam/Downloads/mb wheat data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>It works on their laptop and fails on everyone else’s.</p>
<p><strong>(a)</strong> In a comment: give two problems – one about where the path points, one about the file’s name and location.</p>
<p><strong>(b)</strong> Rewrite the line the way the module recommends, assuming the file was saved as <code>mb_wheat_reported_2020_2025.csv</code> in the project’s <code>data/</code> folder.</p>
<p><strong>(c)</strong> In a comment: your line fails with <code>does not exist in current working directory</code>. What is the first thing to check?</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>The absolute path names one machine’s user folder, so it exists nowhere else; and the file is loose in Downloads under a space-filled name instead of renamed and placed in the project’s <code>data/</code> folder.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>mb_wheat &lt;- read_csv("data/mb_wheat_reported_2020_2025.csv")</code>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>That the folder opened in Positron is the project folder – the one containing <code>data/</code>. Relative paths start from the opened folder.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-18" class="level3">
<h3 class="anchored" data-anchor-id="question-18">Question 18</h3>
<p><strong>(a)</strong> Run <code>glimpse()</code> on <code>mb_wheat</code>. In a comment: which columns are text (<code>&lt;chr&gt;</code>), which numeric (<code>&lt;dbl&gt;</code>), and which logical (<code>&lt;lgl&gt;</code>)?</p>
<p><strong>(b)</strong> In a comment: what values does the logical column hold in this file, and how does the file’s name explain this?</p>
<p><strong>(c)</strong> In a comment: <code>Farms</code> holds whole numbers. Would <code>glimpse()</code> showing it as <code>&lt;chr&gt;</code> be a problem, and what would it tell you about the file?</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li><code>Municipality</code> and <code>Variety</code> are <code>&lt;chr&gt;</code>; <code>Year</code>, <code>Farms</code>, <code>Acres</code>, <code>Yield_bu_ac</code> are <code>&lt;dbl&gt;</code>; <code>Reported</code> is <code>&lt;lgl&gt;</code>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>All <code>TRUE</code> – this is the reported-only file, with the suppressed (<code>FALSE</code>) rows removed.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Yes – a numeric column arriving as text means some value in it could not be read as a number, and calculations like <code>mean()</code> would fail on it.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-19" class="level3">
<h3 class="anchored" data-anchor-id="question-19">Question 19</h3>
<p><strong>(a)</strong> Run <code>summary(mb_wheat)</code>. From its output, report the minimum, median, and maximum of <code>Yield_bu_ac</code>, and the first and last <code>Year</code>.</p>
<p><strong>(b)</strong> In a comment: work through the module’s inspection questions. Are the yields in mostly between 30 and 100 bu/ac, a typical spring wheat range? Are there missing values?</p>
<p><strong>(c)</strong> The minimum is <strong>4.5 bu/ac</strong>. In a comment: is a reported yield that low necessarily an error?</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Yield: min <strong>4.5</strong>, median <strong>62.2</strong>, max <strong>97.8</strong>. Years <strong>2020</strong> to <strong>2025</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Plausible – most values sit tens-of-bushels, sensible for Manitoba wheat; no <code>NA's</code> lines appear, so no missing values in this file.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Not necessarily – a variety on a few drought- or flood-hit fields can genuinely average that low. Extreme is a value to investigate, not delete.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-20" class="level3">
<h3 class="anchored" data-anchor-id="question-20">Question 20</h3>
<p><strong>(a)</strong> Compute the mean, median, standard deviation, and variance of <code>mb_wheat$Yield_bu_ac</code>.</p>
<p><strong>(b)</strong> In a comment: the mean sits a little <em>below</em> the median here. In Module 1’s language, what does that direction of gap suggest, and what kind of observations would produce it?</p>
<p><strong>(c)</strong> Compute the smallest and largest yields in one <code>range()</code> call.</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(mb_wheat<span class="sc">$</span>Yield_bu_ac)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(mb_wheat<span class="sc">$</span>Yield_bu_ac)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(mb_wheat<span class="sc">$</span>Yield_bu_ac)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(mb_wheat<span class="sc">$</span>Yield_bu_ac)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(mb_wheat<span class="sc">$</span>Yield_bu_ac)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li>Mean <strong>61.16</strong>, median <strong>62.2</strong>, sd <strong>12.38</strong>, variance <strong>153.34</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Mild left skew: unusually <em>low</em> values pull the mean down more than the high values pull it up – a tail of very poor variety-municipality observations mixed in with normal ones.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>[1]  4.5 97.8</code> – <code>range()</code> returns both ends as one vector.</li>
</ol></li>
</ul>
</details>
</section>
</section>
</section>
<section id="section-3-data-manipulation-functions" class="level1">
<h1>Section 3 — Data Manipulation Functions</h1>
<p><em>Three blocks of ten, one per dataset. Each question uses two or three of the functions in sequence – save each intermediate result to an object and work step by step (pipelines wait for Section 4).</em></p>
<section id="saskatchewan-rm-crop-yields" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="saskatchewan-rm-crop-yields">Saskatchewan RM Crop Yields</h2>
<p><em>These questions use the full eight-crop file: read <a href="data/rm_yields_1990_2025.csv"><code>rm_yields_1990_2025.csv</code></a> into an object called <code>rm_yields</code> at the start of this block.</em></p>
<section id="question-21" class="level3">
<h3 class="anchored" data-anchor-id="question-21">Question 21</h3>
<p><strong>(a)</strong> Filter <code>rm_yields</code> to Canola in 2024, saving the result as <code>canola_2024</code>. How many rows are in the filtered data frame?</p>
<p><strong>(b)</strong> From <code>canola_2024</code>, select only the <code>RM</code> and <code>Yield</code> columns, saving the result. Report its column names and its number of columns.</p>
<p><strong>(c)</strong> In a comment: after (a) and (b), how many rows does <code>rm_yields</code> itself have, and why?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>canola_2024 <span class="ot">&lt;-</span> <span class="fu">filter</span>(rm_yields, Crop <span class="sc">==</span> <span class="st">"Canola"</span> <span class="sc">&amp;</span> Year <span class="sc">==</span> <span class="dv">2024</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(canola_2024)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>canola_slim <span class="ot">&lt;-</span> <span class="fu">select</span>(canola_2024, RM, Yield)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(canola_slim)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(canola_slim)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li><strong>293 rows</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>RM</code>, <code>Yield</code>; <strong>2 columns</strong> (still 293 rows).</li>
</ol></li>
<li><ol start="3" type="a">
<li>Still <strong>71,104</strong> – <code>filter()</code> and <code>select()</code> return new data frames and leave the original untouched.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-22" class="level3">
<h3 class="anchored" data-anchor-id="question-22">Question 22</h3>
<p><strong>(a)</strong> Filter to rows where the crop is Oats <strong>or</strong> Barley, using <code>|</code>, saving the result. How many rows are in the filtered data frame?</p>
<p><strong>(b)</strong> Write the same filter using <code>%in%</code> and confirm the row count matches.</p>
<p><strong>(c)</strong> Sort your filtered data frame from highest yield to lowest. What crop, RM, and year appear in the top row, and at what yield?</p>
<p><strong>(d)</strong> In a comment: a classmate tried <code>filter(rm_yields, Crop == "Oats" &amp; Crop == "Barley")</code> and got zero rows. Why?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>oats_barley <span class="ot">&lt;-</span> <span class="fu">filter</span>(rm_yields, Crop <span class="sc">==</span> <span class="st">"Oats"</span> <span class="sc">|</span> Crop <span class="sc">==</span> <span class="st">"Barley"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(oats_barley)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>oats_barley2 <span class="ot">&lt;-</span> <span class="fu">filter</span>(rm_yields, Crop <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Oats"</span>, <span class="st">"Barley"</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(oats_barley2)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(oats_barley, <span class="fu">desc</span>(Yield))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>(a, b) <strong>19,709 rows</strong> both ways.</li>
<li><ol start="3" type="a">
<li>A tie at <strong>165.1 bu/ac</strong>: Oats in RM <strong>369</strong> (2025) and Oats in RM <strong>438</strong> (2020) share the maximum, so either is a correct top row.</li>
</ol></li>
<li><ol start="4" type="a">
<li><code>&amp;</code> requires both conditions true of the <em>same row</em>, and no single row’s crop is both Oats and Barley. “Or” is the right connector.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-23" class="level3">
<h3 class="anchored" data-anchor-id="question-23">Question 23</h3>
<p><strong>(a)</strong> Filter to the Spring Wheat observations of at least 60 bu/ac (all years), using <code>&gt;=</code> and saving the result. How many rows are in the filtered data frame?</p>
<p><strong>(b)</strong> Filter again to keep only the 2023 rows of that result. How many rows are in this second data frame?</p>
<p><strong>(c)</strong> From your 2023 data frame, select <code>RM</code> and <code>Yield</code> and sort best-first. Which RM tops the list, at what yield?</p>
<p><strong>(d)</strong> In a comment: rewrite the condition “yield at least 60 and the crop is <em>not</em> Spring Wheat” using <code>!</code>.</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>sw_60 <span class="ot">&lt;-</span> <span class="fu">filter</span>(rm_yields, Crop <span class="sc">==</span> <span class="st">"Spring Wheat"</span> <span class="sc">&amp;</span> Yield <span class="sc">&gt;=</span> <span class="dv">60</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sw_60)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>sw_60_2023 <span class="ot">&lt;-</span> <span class="fu">filter</span>(sw_60, Year <span class="sc">==</span> <span class="dv">2023</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sw_60_2023)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>sw_best <span class="ot">&lt;-</span> <span class="fu">select</span>(sw_60_2023, RM, Yield)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(sw_best, <span class="fu">desc</span>(Yield))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li><strong>434 rows</strong>. (b) <strong>53 rows</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>RM <strong>187</strong>, at <strong>74.7 bu/ac</strong>.</li>
</ol></li>
<li><ol start="4" type="a">
<li><code>filter(rm_yields, Yield &gt;= 60 &amp; !Crop == "Spring Wheat")</code>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-24" class="level3">
<h3 class="anchored" data-anchor-id="question-24">Question 24</h3>
<p><strong>(a)</strong> Make a version of the data with only <code>Year</code>, <code>RM</code>, <code>Crop</code>, and <code>Yield</code> – once by <em>naming what you keep</em>, once by <em>dropping</em> what you don’t want – saving each, and confirm the two have the same column names. Then make a third version keeping the adjacent-column range <code>Year:Crop</code>, and report its column names.</p>
<p><strong>(b)</strong> Rename <code>Yield</code> to <code>yield_per_acre</code> in the full data, saving the result, and show the new column names.</p>
<p><strong>(c)</strong> Filter your renamed data frame to Peas in 2025. How many rows are in the filtered data frame?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>kept    <span class="ot">&lt;-</span> <span class="fu">select</span>(rm_yields, Year, RM, Crop, Yield)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>dropped <span class="ot">&lt;-</span> <span class="fu">select</span>(rm_yields, <span class="sc">-</span>Unit)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(kept)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dropped)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>ranged  <span class="ot">&lt;-</span> <span class="fu">select</span>(rm_yields, Year<span class="sc">:</span>Crop)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ranged)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>renamed <span class="ot">&lt;-</span> <span class="fu">rename</span>(rm_yields, <span class="at">yield_per_acre =</span> Yield)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(renamed)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>peas_2025 <span class="ot">&lt;-</span> <span class="fu">filter</span>(renamed, Crop <span class="sc">==</span> <span class="st">"Peas"</span> <span class="sc">&amp;</span> Year <span class="sc">==</span> <span class="dv">2025</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(peas_2025)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li>Identical: <code>Year</code>, <code>RM</code>, <code>Crop</code>, <code>Yield</code> both ways; the range version keeps <code>Year</code>, <code>RM</code>, <code>Crop</code>.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>Year</code>, <code>RM</code>, <code>Crop</code>, <code>yield_per_acre</code>, <code>Unit</code>.</li>
</ol></li>
<li><ol start="3" type="a">
<li><strong>285 rows</strong>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-25" class="level3">
<h3 class="anchored" data-anchor-id="question-25">Question 25</h3>
<p><strong>(a)</strong> Filter to Canola in 2024, then in one <code>mutate()</code> call add two columns: <code>yield_t_ha</code> (multiply by 0.0560) and <code>yield_kg_ha</code> (multiply by 56.0). Save the result of each step.</p>
<p><strong>(b)</strong> Compute the mean of each new column.</p>
<p><strong>(c)</strong> Sort by <code>yield_t_ha</code>, best first. Which RM tops the table, and at what yield in t/ha?</p>
<p><strong>(d)</strong> In a comment: without running anything, what is the mean of <code>yield_kg_ha</code> divided by the mean of <code>yield_t_ha</code>, and why?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>canola_2024 <span class="ot">&lt;-</span> <span class="fu">filter</span>(rm_yields, Crop <span class="sc">==</span> <span class="st">"Canola"</span> <span class="sc">&amp;</span> Year <span class="sc">==</span> <span class="dv">2024</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>canola_2024 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(canola_2024,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">yield_t_ha  =</span> Yield <span class="sc">*</span> <span class="fl">0.0560</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">yield_kg_ha =</span> Yield <span class="sc">*</span> <span class="fl">56.0</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(canola_2024<span class="sc">$</span>yield_t_ha)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(canola_2024<span class="sc">$</span>yield_kg_ha)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(canola_2024, <span class="fu">desc</span>(yield_t_ha))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li><strong>1.76 t/ha</strong> and <strong>1,764.11 kg/ha</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>RM <strong>493</strong>, at <strong>2.57 t/ha</strong>.</li>
</ol></li>
<li><ol start="4" type="a">
<li>1,000 – both columns are the same yields scaled by constants, and 56.0 / 0.0560 = 1000 (a tonne is 1,000 kg).</li>
</ol></li>
</ul>
</details>
</section>
</section>
<section id="manitoba-wheat-variety-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="manitoba-wheat-variety-1">Manitoba Wheat Variety</h2>
<p><em>These questions use the full <a href="data/mb_wheat_varieties.csv"><code>mb_wheat_varieties.csv</code></a> – including the suppressed rows, where <code>Reported</code> is FALSE and the numeric columns are missing. Read it into an object called <code>mb</code> at the start of this block.</em></p>
<section id="question-26" class="level3">
<h3 class="anchored" data-anchor-id="question-26">Question 26</h3>
<p><strong>(a)</strong> Filter <code>mb</code> to the reported rows (<code>Reported == TRUE</code>), saving as <code>mb_rep</code>. How many rows are in the filtered data frame?</p>
<p><strong>(b)</strong> From <code>mb_rep</code>, select <code>Municipality</code>, <code>Variety</code>, and <code>Yield_bu_ac</code>, saving the result. Report its column names.</p>
<p><strong>(c)</strong> In a comment: how many rows does <code>mb</code> itself still have, and what happened to the suppressed rows in <code>mb_rep</code>?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mb_rep <span class="ot">&lt;-</span> <span class="fu">filter</span>(mb, Reported <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mb_rep)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>mb_slim <span class="ot">&lt;-</span> <span class="fu">select</span>(mb_rep, Municipality, Variety, Yield_bu_ac)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(mb_slim)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li><strong>2,398 rows</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>Municipality</code>, <code>Variety</code>, <code>Yield_bu_ac</code>.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>mb</code> still has <strong>5,358</strong> rows – filtering returns a new data frame. The 2,960 suppressed rows are simply absent from <code>mb_rep</code>; they were not deleted from anything.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-27" class="level3">
<h3 class="anchored" data-anchor-id="question-27">Question 27</h3>
<p><strong>(a)</strong> From <code>mb_rep</code> (reported rows), filter to the varieties <code>AAC BRANDON (BW 932)</code> <strong>or</strong> <code>AAC STARBUCK &lt;SECAN&gt;</code> using <code>|</code>, saving the result. How many rows are in the filtered data frame?</p>
<p><strong>(b)</strong> Write the same filter using <code>%in%</code> and confirm the count matches.</p>
<p><strong>(c)</strong> In a comment: a classmate wrote the condition with <code>&amp;</code> instead of <code>|</code> and got zero rows. Why?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>two_var <span class="ot">&lt;-</span> <span class="fu">filter</span>(mb_rep, Variety <span class="sc">==</span> <span class="st">"AAC BRANDON (BW 932)"</span> <span class="sc">|</span> Variety <span class="sc">==</span> <span class="st">"AAC STARBUCK &lt;SECAN&gt;"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(two_var)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>two_var2 <span class="ot">&lt;-</span> <span class="fu">filter</span>(mb_rep, Variety <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"AAC BRANDON (BW 932)"</span>, <span class="st">"AAC STARBUCK &lt;SECAN&gt;"</span>))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(two_var2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>(a, b) <strong>893 rows</strong> both ways.</li>
<li><ol start="3" type="a">
<li><code>&amp;</code> demands both conditions true of the same row, and no single row’s variety is both names at once. “Or” is the right connector.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-28" class="level3">
<h3 class="anchored" data-anchor-id="question-28">Question 28</h3>
<p><strong>(a)</strong> Filter <code>mb_rep</code> to yields above 80 bu/ac, saving the result. How many rows are in the filtered data frame?</p>
<p><strong>(b)</strong> Filter that result again to 2024 only. How many rows now?</p>
<p><strong>(c)</strong> Sort your over-80 data frame from (a) best-first. Which municipality, variety, and year top the list, at what yield?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>high <span class="ot">&lt;-</span> <span class="fu">filter</span>(mb_rep, Yield_bu_ac <span class="sc">&gt;</span> <span class="dv">80</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(high)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>high_2024 <span class="ot">&lt;-</span> <span class="fu">filter</span>(high, Year <span class="sc">==</span> <span class="dv">2024</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(high_2024)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(high, <span class="fu">desc</span>(Yield_bu_ac))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li><strong>97 rows</strong>. (b) <strong>16 rows</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>HILLSBURG-ROBLIN-SHELL RIVER, <code>BOLLES &lt;SEED DEPOT&gt;</code>, in <strong>2022</strong>, at <strong>97.8 bu/ac</strong>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-29" class="level3">
<h3 class="anchored" data-anchor-id="question-29">Question 29</h3>
<p><strong>(a)</strong> From <code>mb_rep</code>, make a version with only <code>Year</code>, <code>Municipality</code>, <code>Variety</code>, and <code>Yield_bu_ac</code> – once by naming what you keep, once by dropping what you don’t (<code>Farms</code>, <code>Acres</code>, <code>Reported</code>) – saving each, and confirm the two have the same column names. Then make a third version keeping the adjacent range <code>Year:Variety</code> and report its names.</p>
<p><strong>(b)</strong> Rename <code>Yield_bu_ac</code> to <code>yield</code>, saving the result, and show the new column names.</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>kept    <span class="ot">&lt;-</span> <span class="fu">select</span>(mb_rep, Year, Municipality, Variety, Yield_bu_ac)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>dropped <span class="ot">&lt;-</span> <span class="fu">select</span>(mb_rep, <span class="sc">-</span>Farms, <span class="sc">-</span>Acres, <span class="sc">-</span>Reported)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(kept)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dropped)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>ranged  <span class="ot">&lt;-</span> <span class="fu">select</span>(mb_rep, Year<span class="sc">:</span>Variety)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ranged)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>renamed <span class="ot">&lt;-</span> <span class="fu">rename</span>(mb_rep, <span class="at">yield =</span> Yield_bu_ac)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(renamed)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol type="a">
<li>Identical four names both ways; the range version keeps <code>Year</code>, <code>Municipality</code>, <code>Variety</code>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>The same seven columns with <code>yield</code> in place of <code>Yield_bu_ac</code>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-30" class="level3">
<h3 class="anchored" data-anchor-id="question-30">Question 30</h3>
<p><strong>(a)</strong> From <code>mb_rep</code>, use one <code>mutate()</code> to add <code>total_bu</code>, each observation’s acres times its yield, saving the result.</p>
<p><strong>(b)</strong> Compute the mean of <code>total_bu</code>.</p>
<p><strong>(c)</strong> Sort by <code>total_bu</code>, largest first. Which municipality tops the table, and at roughly what total?</p>
<p><strong>(d)</strong> In a comment: what does <code>total_bu</code> measure that <code>Yield_bu_ac</code> does not?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mb_rep <span class="ot">&lt;-</span> <span class="fu">mutate</span>(mb_rep, <span class="at">total_bu =</span> Acres <span class="sc">*</span> Yield_bu_ac)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(mb_rep<span class="sc">$</span>total_bu)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(mb_rep, <span class="fu">desc</span>(total_bu))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li>Mean <strong>382,865 bu</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>PORTAGE LA PRAIRIE, at about <strong>5.13 million bushels</strong>.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Production – how much grain the planting actually produced – rather than how well each acre yielded. A modest yield on enormous acres can out-produce a great yield on few.</li>
</ol></li>
</ul>
</details>
</section>
</section>
</section>
<section id="section-4-pipelines-and-grouped-summaries" class="level1">
<h1>Section 4 — Pipelines and Grouped Summaries</h1>
<p><em>Three blocks of ten, one per dataset. Answer in the Section 4 block of your script. Write multi-step work as pipelines with <code>|&gt;</code>, one step per line.</em></p>
<section id="saskatchewan-rm-crop-yields-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="saskatchewan-rm-crop-yields-1">Saskatchewan RM Crop Yields</h2>
<p><em>Still the full eight-crop file (<code>rm_yields</code>).</em></p>
<section id="question-31" class="level3">
<h3 class="anchored" data-anchor-id="question-31">Question 31</h3>
<p><strong>(a)</strong> Write a pipeline, one step per line with a short comment on each step, that filters <code>rm_yields</code> to Durum in 2025, keeps only the <code>RM</code> and <code>Yield</code> columns, and sorts the result from highest yield to lowest.</p>
<p><strong>(b)</strong> Run it. How many rows are in the resulting data frame, and which RM had the best durum yield in 2025, at what value?</p>
<p><strong>(c)</strong> In a comment: read your pipeline aloud as a “take the data, then …, then …, then …” sentence.</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>rm_yields <span class="sc">|&gt;</span>                              <span class="co"># take the data, THEN</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Crop <span class="sc">==</span> <span class="st">"Durum"</span> <span class="sc">&amp;</span> Year <span class="sc">==</span> <span class="dv">2025</span>) <span class="sc">|&gt;</span>  <span class="co"># keep durum in 2025, THEN</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(RM, Yield) <span class="sc">|&gt;</span>                    <span class="co"># keep two columns, THEN</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Yield))                    <span class="co"># sort best-first</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li><strong>189 rows</strong>; RM <strong>369</strong> at <strong>105.6 bu/ac</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Take <code>rm_yields</code>, then keep the 2025 durum rows, then keep the RM and Yield columns, then sort from highest yield to lowest.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-32" class="level3">
<h3 class="anchored" data-anchor-id="question-32">Question 32</h3>
<p><strong>(a)</strong> In one pipeline, compute the mean flax yield across 2020–2025 (<code>Year &gt;= 2020</code>), calling the result column <code>mean_yield</code>.</p>
<p><strong>(b)</strong> Add <code>n()</code> to the same <code>summarise()</code> to count how many observations that mean is based on.</p>
<p><strong>(c)</strong> In a comment: why is reporting the count alongside the mean good practice?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>rm_yields <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Crop <span class="sc">==</span> <span class="st">"Flax"</span> <span class="sc">&amp;</span> Year <span class="sc">&gt;=</span> <span class="dv">2020</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_yield =</span> <span class="fu">mean</span>(Yield),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>(a, b) Mean <strong>22.39 bu/ac</strong> from <strong>1,143</strong> observations.</li>
<li><ol start="3" type="a">
<li>A mean based on a handful of rows deserves less trust than one based on a thousand; the count tells the reader which they are looking at.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-33" class="level3">
<h3 class="anchored" data-anchor-id="question-33">Question 33</h3>
<p><strong>(a)</strong> In one pipeline, compute the mean canola yield for <strong>each year</strong> from 2021 to 2025 (filter first, then group).</p>
<p><strong>(b)</strong> Report the five means. Which year was worst, and which best?</p>
<p><strong>(c)</strong> In a comment: 2021 was a severe drought year in Saskatchewan. Does the data agree?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>rm_yields <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Crop <span class="sc">==</span> <span class="st">"Canola"</span> <span class="sc">&amp;</span> Year <span class="sc">&gt;=</span> <span class="dv">2021</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_yield =</span> <span class="fu">mean</span>(Yield))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>(a, b) 2021 <strong>21.9</strong>, 2022 <strong>35.4</strong>, 2023 <strong>33.9</strong>, 2024 <strong>31.5</strong>, 2025 <strong>43.9</strong>. Worst 2021, best 2025.</li>
<li><ol start="3" type="a">
<li>Yes – the 2021 mean sits roughly a third below the surrounding years.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-34" class="level3">
<h3 class="anchored" data-anchor-id="question-34">Question 34</h3>
<p><strong>(a)</strong> In one pipeline: filter to Lentils, convert to kg/ha with <code>mutate()</code> (multiply by 1.12), then summarise the mean of the converted column.</p>
<p><strong>(b)</strong> Report the mean in kg/ha.</p>
<p><strong>(c)</strong> In a comment: in what order do your steps run, and why would putting the <code>summarise()</code> before the <code>mutate()</code> fail?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>rm_yields <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Crop <span class="sc">==</span> <span class="st">"Lentils"</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">yield_kg_ha =</span> Yield <span class="sc">*</span> <span class="fl">1.12</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_kg_ha =</span> <span class="fu">mean</span>(yield_kg_ha))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li><strong>1,353.4 kg/ha</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Top to bottom – each step’s output feeds the next. After <code>summarise()</code> the data has collapsed to one row and the <code>yield_kg_ha</code> column would not exist yet to summarise.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-35" class="level3">
<h3 class="anchored" data-anchor-id="question-35">Question 35</h3>
<p><strong>(a)</strong> In one pipeline: for <strong>2025 only</strong>, compute each crop’s mean yield and observation count, sorted from highest mean to lowest, and save the result as <code>crop_summary_2025</code>.</p>
<p><strong>(b)</strong> Write the table to <code>output/crop_summary_2025.csv</code>.</p>
<p><strong>(c)</strong> Report the two highest-yielding crops in the sorted table. In a comment: check the Unit column: why is the first-place crop not comparable to the rest, and which bushel crop is the real standout?, and which crop is really the standout?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>crop_summary_2025 <span class="ot">&lt;-</span> rm_yields <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">==</span> <span class="dv">2025</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Crop) <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_yield =</span> <span class="fu">mean</span>(Yield),</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_yield))</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(crop_summary_2025, <span class="st">"output/crop_summary_2025.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>(a, c) Lentils top the table at <strong>1,897</strong> – but that is pounds per acre, not bushels. Among the bushel crops, Oats lead at <strong>97.5 bu/ac</strong> (Barley next at 72.8). 2025 was a strong year across the board.</li>
</ul>
</details>
</section>
</section>
<section id="manitoba-wheat-variety-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="manitoba-wheat-variety-2">Manitoba Wheat Variety</h2>
<p><em>Full <a href="data/mb_wheat_varieties.csv"><code>mb_wheat_varieties.csv</code></a>, read as <code>mb</code>, with the reported rows saved as <code>mb_rep &lt;- filter(mb, Reported == TRUE)</code> at the start of this block. Build everything else as pipelines.</em></p>
<section id="question-36" class="level3">
<h3 class="anchored" data-anchor-id="question-36">Question 36</h3>
<p><strong>(a)</strong> Write a pipeline, one step per line with a short comment on each, that filters <code>mb_rep</code> to 2025, keeps <code>Municipality</code>, <code>Variety</code>, and <code>Yield_bu_ac</code>, and sorts best-first.</p>
<p><strong>(b)</strong> Run it. How many rows are in the resulting data frame, and which municipality and variety top it, at what yield?</p>
<p><strong>(c)</strong> In a comment: read the pipeline aloud as a “take the data, then …” sentence.</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>mb_rep <span class="sc">|&gt;</span>                                          <span class="co"># take the reported rows, THEN</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">==</span> <span class="dv">2025</span>) <span class="sc">|&gt;</span>                          <span class="co"># keep 2025, THEN</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Municipality, Variety, Yield_bu_ac) <span class="sc">|&gt;</span>    <span class="co"># keep three columns, THEN</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Yield_bu_ac))                       <span class="co"># sort best-first</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li><strong>438 rows</strong>; LOUISE, growing SY MANNESS, at <strong>96.3 bu/ac</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Take the reported rows, then keep 2025, then keep three columns, then sort from highest yield to lowest.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-37" class="level3">
<h3 class="anchored" data-anchor-id="question-37">Question 37</h3>
<p><strong>(a)</strong> In one pipeline, compute the mean of <code>Yield_bu_ac</code> across all of <code>mb_rep</code>, calling it <code>mean_yield</code>, together with <code>n()</code>.</p>
<p><strong>(b)</strong> Report both values.</p>
<p><strong>(c)</strong> In a comment: why report the count alongside the mean?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>mb_rep <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_yield =</span> <span class="fu">mean</span>(Yield_bu_ac),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li>Mean <strong>61.16 bu/ac</strong> from <strong>2,398</strong> observations.</li>
</ol></li>
<li><ol start="3" type="a">
<li>A mean earns trust in proportion to what it is based on; the count tells the reader how much that is.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-38" class="level3">
<h3 class="anchored" data-anchor-id="question-38">Question 38</h3>
<p><strong>(a)</strong> In one pipeline, compute each variety’s mean yield and observation count across <code>mb_rep</code>, sorted from highest mean to lowest.</p>
<p><strong>(b)</strong> Report the top two varieties, their means, and their counts.</p>
<p><strong>(c)</strong> In a comment: the second-place variety was observed exactly once. Which of the two means would you trust more, and why?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>mb_rep <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Variety) <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_yield =</span> <span class="fu">mean</span>(Yield_bu_ac),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_yield))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li>AAC WESTKING, <strong>79.2 bu/ac</strong> from <strong>17</strong> observations; then CDC GO (BW781), <strong>77.5</strong> from <strong>1</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>WESTKING’s – seventeen municipality-years is evidence; a single observation could be one lucky field in one good year.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-39" class="level3">
<h3 class="anchored" data-anchor-id="question-39">Question 39</h3>
<p>A bushel of wheat is 60 lb, so one bu/ac is about 0.0673 t/ha.</p>
<p><strong>(a)</strong> In one pipeline: convert <code>mb_rep</code>’s yields to t/ha with <code>mutate()</code>, then compute the mean t/ha for each year.</p>
<p><strong>(b)</strong> Report the 2021 and 2025 values.</p>
<p><strong>(c)</strong> In a comment: why must the <code>mutate()</code> step come before the <code>summarise()</code> step?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mb_rep <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">yield_t_ha =</span> Yield_bu_ac <span class="sc">*</span> <span class="fl">0.0673</span>) <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">|&gt;</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_t_ha =</span> <span class="fu">mean</span>(yield_t_ha))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="2" type="a">
<li>2021 <strong>3.34 t/ha</strong>; 2025 <strong>4.58 t/ha</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Each step’s output feeds the next – after <code>summarise()</code> the data has collapsed to one row per year and the <code>yield_t_ha</code> column would not exist to average.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-40" class="level3">
<h3 class="anchored" data-anchor-id="question-40">Question 40</h3>
<p><strong>(a)</strong> In one pipeline: for <strong>2025 only</strong>, compute each variety’s mean reported yield and observation count, sorted best-first, and save the result as <code>variety_summary_2025</code>.</p>
<p><strong>(b)</strong> Write the table to <code>output/variety_summary_2025.csv</code>.</p>
<p><strong>(c)</strong> Report the top row. In a comment: the table also contains varieties observed only twice – what should a reader keep in mind when comparing rows?</p>
<details>
<summary>
Answer
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>variety_summary_2025 <span class="ot">&lt;-</span> mb_rep <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">==</span> <span class="dv">2025</span>) <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Variety) <span class="sc">|&gt;</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_yield =</span> <span class="fu">mean</span>(Yield_bu_ac),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_yield))</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(variety_summary_2025, <span class="st">"output/variety_summary_2025.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><ol start="3" type="a">
<li>AAC WESTKING, <strong>79.2 bu/ac</strong> from 17 observations. Rows with tiny counts (some varieties appear once or twice) carry far less evidence than their neighbours – the <code>n</code> column is part of the answer, not decoration.</li>
</ol></li>
</ul>
</details>


</section>
</section>
</section>

</main> <!-- /main -->
<script>
// Wrap each executed chunk's console output in a collapsed <details> so
// students can predict what R will print before revealing it.
//
// Quarto has code-fold for *code*, but no equivalent for output, so we do it
// here: for every .cell-output block, build a <details class="console-fold">
// and move the output inside it. Runs once on DOMContentLoaded.
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll(".console-transcript, .cell-output").forEach(function (out) {
    // Don't double-wrap, and skip output already inside a transcript.
    if (out.closest("details.console-fold")) return;
    if (out.classList.contains("cell-output") && out.closest(".console-transcript")) return;

    var details = document.createElement("details");
    details.className = "console-fold";

    var summary = document.createElement("summary");
    // transcript = a full console session from console(); stderr =
    // messages/warnings; error = a deliberate mistake we're showing.
    if (out.classList.contains("console-transcript")) {
      summary.textContent = "Show console session";
    } else if (out.classList.contains("cell-output-error")) {
      summary.textContent = "Show R's error message";
    } else if (out.classList.contains("cell-output-stderr")) {
      summary.textContent = "Show console message";
    } else {
      summary.textContent = "Show console output";
    }
    details.appendChild(summary);

    out.parentNode.insertBefore(details, out);
    details.appendChild(out);
  });
});

// Split sidebar module labels ("Module 5: Probability and Random Variables")
// into a small number line above the title, so the module number is scannable
// and long titles stop wrapping mid-phrase. Quarto emits the whole label as one
// text node, so the split has to happen here rather than in CSS.
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll(".sidebar-item-section .menu-text").forEach(function (el) {
    if (el.querySelector(".module-label")) return;          // already split
    var m = el.textContent.match(/^\s*Module\s+(\d+)\s*:\s*(.+)$/);
    if (!m) return;                                          // not a module part

    el.textContent = "";
    var num = document.createElement("span");
    num.className = "module-label";
    num.textContent = "Module " + m[1];
    var title = document.createElement("span");
    title.className = "module-title";
    title.textContent = m[2];
    el.appendChild(num);
    el.appendChild(title);
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/agdataanalytics\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../practice/module01_bank.html" class="pagination-link" aria-label="Module 1 - Test bank">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module 1 - Test bank</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>