<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 1 — Test Bank – AREC 261: Agricultural Data Analytics I</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../practice/module02_practice.html" rel="next">
<link href="../practice/module01_bank.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8af8f98213e2c1b30ec54438e312c198.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../practice/module01_bank.html">Test Bank</a></li><li class="breadcrumb-item"><a href="../practice/module01_practice.html">Module 1 — Test Bank</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">AREC 261: Agricultural Data Analytics I</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction: How to Think About Data Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 1: Data Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Describing Data in Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R and Positron</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Transforming Data in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Graphing in R and Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Communicating Data Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Relationships Between Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 2: Probability and Simulation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability and Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability and Simulation I</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability and Simulation II</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 3: Inference Through Simulation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bootstrap Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Test Bank</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practice/module01_bank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 — Full Test Bank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practice/module01_practice.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 1 — Test Bank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practice/module02_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 — Test Bank</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#instructions" id="toc-instructions" class="nav-link active" data-scroll-target="#instructions">Instructions</a>
  <ul class="collapse">
  <li><a href="#datasets" id="toc-datasets" class="nav-link" data-scroll-target="#datasets">Datasets</a></li>
  </ul></li>
  <li><a href="#type-1-descriptive-statistics" id="toc-type-1-descriptive-statistics" class="nav-link" data-scroll-target="#type-1-descriptive-statistics">Type 1: Descriptive Statistics</a>
  <ul class="collapse">
  <li><a href="#variant-1a-canola-in-2023" id="toc-variant-1a-canola-in-2023" class="nav-link" data-scroll-target="#variant-1a-canola-in-2023">Variant 1A — Canola in 2023</a></li>
  <li><a href="#variant-1b-spring-wheat-in-2023" id="toc-variant-1b-spring-wheat-in-2023" class="nav-link" data-scroll-target="#variant-1b-spring-wheat-in-2023">Variant 1B — Spring Wheat in 2023</a></li>
  </ul></li>
  <li><a href="#type-2-conditional-functions-and-lookups" id="toc-type-2-conditional-functions-and-lookups" class="nav-link" data-scroll-target="#type-2-conditional-functions-and-lookups">Type 2: Conditional Functions and Lookups</a>
  <ul class="collapse">
  <li><a href="#variant-2a" id="toc-variant-2a" class="nav-link" data-scroll-target="#variant-2a">Variant 2A</a></li>
  <li><a href="#variant-2b" id="toc-variant-2b" class="nav-link" data-scroll-target="#variant-2b">Variant 2B</a></li>
  </ul></li>
  <li><a href="#type-3-pivottables" id="toc-type-3-pivottables" class="nav-link" data-scroll-target="#type-3-pivottables">Type 3: PivotTables</a>
  <ul class="collapse">
  <li><a href="#variant-3a-comparing-crops" id="toc-variant-3a-comparing-crops" class="nav-link" data-scroll-target="#variant-3a-comparing-crops">Variant 3A — Comparing crops</a></li>
  <li><a href="#variant-3b-crops-over-time-the-drought-signal" id="toc-variant-3b-crops-over-time-the-drought-signal" class="nav-link" data-scroll-target="#variant-3b-crops-over-time-the-drought-signal">Variant 3B — Crops over time (the drought signal)</a></li>
  </ul></li>
  <li><a href="#type-4-charts" id="toc-type-4-charts" class="nav-link" data-scroll-target="#type-4-charts">Type 4: Charts</a>
  <ul class="collapse">
  <li><a href="#variant-4a-distribution-of-yields" id="toc-variant-4a-distribution-of-yields" class="nav-link" data-scroll-target="#variant-4a-distribution-of-yields">Variant 4A — Distribution of yields</a></li>
  <li><a href="#variant-4b-a-crop-over-time" id="toc-variant-4b-a-crop-over-time" class="nav-link" data-scroll-target="#variant-4b-a-crop-over-time">Variant 4B — A crop over time</a></li>
  </ul></li>
  <li><a href="#auto-generated-practice-quiz" id="toc-auto-generated-practice-quiz" class="nav-link" data-scroll-target="#auto-generated-practice-quiz">Auto-Generated Practice Quiz</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../practice/module01_bank.html">Test Bank</a></li><li class="breadcrumb-item"><a href="../practice/module01_practice.html">Module 1 — Test Bank</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Module 1 — Test Bank</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="instructions" class="level2">
<h2 class="anchored" data-anchor-id="instructions">Instructions</h2>
<p>Each practice test consists of <strong>four questions</strong>, one from each type below. Download the dataset, complete the work in Excel, and check your answers by expanding the answer section below each question.</p>
<p>On the <strong>real test</strong>, you will receive a PDF with four questions and will submit a <code>.xlsx</code> workbook with your answers. You will have access to the full test bank for practice — the test draws one question randomly from each type.</p>
<section id="datasets" class="level3">
<h3 class="anchored" data-anchor-id="datasets">Datasets</h3>
<p>This module provides the <strong>same</strong> Saskatchewan crop-yield data in <strong>two shapes</strong>. Use whichever fits the question — see <a href="../module01.html#sec-wide-long" class="quarto-xref"><span>Wide vs.&nbsp;Long Data</span></a> in the module for why the shape matters.</p>
<p><strong>Wide format</strong> — <a href="data/rm_yields_1990plus.csv"><code>rm_yields_1990plus.csv</code></a> — one row per RM-year, each crop in its own column. Use this for <strong>descriptive statistics, conditional functions, and lookups</strong> (Types 1, 2, and the chart questions).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Column</th>
<th>Excel col</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Year</code></td>
<td>A</td>
<td>Crop year (1990–2025)</td>
</tr>
<tr class="even">
<td><code>RM</code></td>
<td>B</td>
<td>Rural Municipality number (1–622)</td>
</tr>
<tr class="odd">
<td><code>Spring Wheat</code></td>
<td>C</td>
<td>Spring wheat yield (bu/ac)</td>
</tr>
<tr class="even">
<td><code>Durum</code></td>
<td>D</td>
<td>Durum yield (bu/ac)</td>
</tr>
<tr class="odd">
<td><code>Canola</code></td>
<td>E</td>
<td>Canola yield (bu/ac)</td>
</tr>
<tr class="even">
<td><code>Barley</code></td>
<td>F</td>
<td>Barley yield (bu/ac)</td>
</tr>
<tr class="odd">
<td><code>Oats</code></td>
<td>G</td>
<td>Oats yield (bu/ac)</td>
</tr>
<tr class="even">
<td><code>Peas</code></td>
<td>H</td>
<td>Field pea yield (bu/ac)</td>
</tr>
<tr class="odd">
<td><code>Lentils</code></td>
<td>I</td>
<td>Lentil yield (lb/ac)</td>
</tr>
<tr class="even">
<td><code>Flax</code></td>
<td>J</td>
<td>Flax yield (bu/ac)</td>
</tr>
</tbody>
</table>
<p><strong>Long format</strong> — <a href="data/rm_yields_1990plus_long.csv"><code>rm_yields_1990plus_long.csv</code></a> — one row per RM-year-<strong>crop</strong>, with the crop name in its own column. Use this for <strong>PivotTables</strong> (Type 3), where you want to group <em>by crop</em>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Column</th>
<th>Excel col</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Year</code></td>
<td>A</td>
<td>Crop year (1990–2025)</td>
</tr>
<tr class="even">
<td><code>RM</code></td>
<td>B</td>
<td>Rural Municipality number</td>
</tr>
<tr class="odd">
<td><code>Crop</code></td>
<td>C</td>
<td>Crop name (one of the eight crops)</td>
</tr>
<tr class="even">
<td><code>Yield</code></td>
<td>D</td>
<td>Yield value for that crop</td>
</tr>
<tr class="odd">
<td><code>Unit</code></td>
<td>E</td>
<td><code>bu/ac</code> for all crops except Lentils (<code>lb/ac</code>)</td>
</tr>
</tbody>
</table>
<p>Both files come from the Government of Saskatchewan’s <a href="https://dashboard.saskatchewan.ca/agriculture/rm-yields/rm-yields-data">RM Yields dataset</a>, filtered to 1990 onward and the eight most widely grown crops. They contain identical information — the long file simply <em>stacks</em> the crop columns of the wide file.</p>
<p><strong>Important — this is real data, so it has gaps.</strong> In the <strong>wide</strong> file a cell is <strong>blank</strong> when that crop was not grown (or not reported) in that RM and year; Excel’s <code>AVERAGE</code>, <code>COUNT</code>, <code>MEDIAN</code>, etc. <strong>automatically skip blank cells</strong>. In the <strong>long</strong> file, those non-observations are simply absent (no row), which is why the long file has fewer rows than 8 × the wide file. Either way: never fill a blank with 0 (a blank means “no data,” not “a yield of zero”).</p>
<p>Import each CSV using <strong>Data → Get Data → From Text/CSV</strong> (not by double-clicking) to avoid Excel mangling any values.</p>
<blockquote class="blockquote">
<p><strong>A note on the numbers.</strong> Because Saskatchewan updates this dataset over time, the exact figures in the answer keys are stated <strong>as of the current data snapshot</strong>. The important thing is the <strong>method</strong> — the right filter and the right formula — which stays correct even if a number shifts slightly when the data is refreshed.</p>
</blockquote>
<hr>
</section>
</section>
<section id="type-1-descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="type-1-descriptive-statistics">Type 1: Descriptive Statistics</h2>
<p>Several of these questions focus on a <strong>single crop in a single year</strong>. The cleanest approach in Excel is to first <strong>filter</strong> the data to that year (Data → Filter, or copy the year’s rows to a new sheet), then compute the statistics on that crop’s column. Place each answer in a clearly labelled cell, using an Excel formula (not a hard-coded value).</p>
<section id="variant-1a-canola-in-2023" class="level3">
<h3 class="anchored" data-anchor-id="variant-1a-canola-in-2023">Variant 1A — Canola in 2023</h3>
<p>Filter the data to <strong><code>Year = 2023</code></strong> and work with the <strong>Canola</strong> column.</p>
<p><strong>(a)</strong> Compute the <strong>mean</strong> canola yield across all RMs that reported canola in 2023.</p>
<p><strong>(b)</strong> Compute the <strong>median</strong> canola yield.</p>
<p><strong>(c)</strong> Compute the <strong>sample standard deviation</strong> of canola yield.</p>
<p><strong>(d)</strong> Compute the <strong>first quartile (Q1)</strong> and <strong>third quartile (Q3)</strong>, and the <strong>interquartile range (IQR)</strong>.</p>
<p><strong>(e)</strong> Compute the <strong>90th percentile</strong> of canola yield. Write one sentence explaining what it means in plain language.</p>
<p><strong>(f)</strong> Is the mean or the median higher? What does this tell you about the shape of the distribution?</p>
<details>
<summary>
<strong>Answers</strong>
</summary>
<p><em>Values as of the current snapshot; 2023 has 295 RM rows, of which 289 reported canola (6 blanks).</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 33%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Part</th>
<th>Value</th>
<th>Formula (assuming 2023 Canola values are in <code>E2:E296</code>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(a) Mean</td>
<td>≈ 33.88 bu/ac</td>
<td><code>=AVERAGE(E2:E296)</code></td>
</tr>
<tr class="even">
<td>(b) Median</td>
<td>≈ 35.50 bu/ac</td>
<td><code>=MEDIAN(E2:E296)</code></td>
</tr>
<tr class="odd">
<td>(c) Std dev</td>
<td>≈ 13.33 bu/ac</td>
<td><code>=STDEV.S(E2:E296)</code></td>
</tr>
<tr class="even">
<td>(d) Q1</td>
<td>≈ 22.60 bu/ac</td>
<td><code>=QUARTILE.INC(E2:E296, 1)</code></td>
</tr>
<tr class="odd">
<td>(d) Q3</td>
<td>≈ 44.90 bu/ac</td>
<td><code>=QUARTILE.INC(E2:E296, 3)</code></td>
</tr>
<tr class="even">
<td>(d) IQR</td>
<td>≈ 22.30 bu/ac</td>
<td><code>=QUARTILE.INC(E2:E296,3) - QUARTILE.INC(E2:E296,1)</code></td>
</tr>
<tr class="odd">
<td>(e) P90</td>
<td>≈ 50.44 bu/ac</td>
<td><code>=PERCENTILE.INC(E2:E296, 0.9)</code></td>
</tr>
</tbody>
</table>
<p><strong>Part (e) interpretation:</strong> About 90% of reporting RMs had a 2023 canola yield of ~50.4 bu/ac or less; only the top 10% of RMs exceeded it.</p>
<p><strong>Part (f):</strong> The median (≈35.5) is higher than the mean (≈33.9), indicating a slight <strong>left (negative) skew</strong> — a number of low-yielding RMs (some as low as ~3 bu/ac, likely drought-hit) pull the mean below the median.</p>
<p><strong>Common mistakes:</strong></p>
<ul>
<li><strong>Filtering first is essential.</strong> If you compute <code>AVERAGE</code> on the whole (unfiltered) Canola column you get the 1990–2025 average (≈28.3), not the 2023 average.</li>
<li>Using <code>STDEV.P</code> instead of <code>STDEV.S</code>. Use <code>.S</code> for a sample.</li>
<li>Filling blank cells with 0 — this drags the mean down and is wrong. Leave blanks blank; <code>AVERAGE</code> skips them.</li>
<li>Forgetting <code>PERCENTILE.INC</code> takes a decimal (0.9), not 90.</li>
</ul>
</details>
</section>
<section id="variant-1b-spring-wheat-in-2023" class="level3">
<h3 class="anchored" data-anchor-id="variant-1b-spring-wheat-in-2023">Variant 1B — Spring Wheat in 2023</h3>
<p>Filter the data to <strong><code>Year = 2023</code></strong> and work with the <strong>Spring Wheat</strong> column.</p>
<p><strong>(a)</strong> Compute the <strong>mean</strong> and <strong>median</strong> spring wheat yield.</p>
<p><strong>(b)</strong> Compute the <strong>sample standard deviation</strong> and <strong>sample variance</strong>. What are the units of the variance?</p>
<p><strong>(c)</strong> Compute the <strong>minimum</strong>, <strong>maximum</strong>, and <strong>range</strong> of spring wheat yield.</p>
<p><strong>(d)</strong> Compute <strong>Q1</strong>, <strong>Q3</strong>, and the <strong>IQR</strong>.</p>
<p><strong>(e)</strong> How many RMs reported a spring wheat yield in 2023? (Count the non-blank cells.)</p>
<details>
<summary>
<strong>Answers</strong>
</summary>
<p><em>Values as of the current snapshot; assume the 2023 Spring Wheat values are in column <code>C</code>.</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 31%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Part</th>
<th>Value</th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(a) Mean</td>
<td>≈ 42.87 bu/ac</td>
<td><code>=AVERAGE(C2:C296)</code></td>
</tr>
<tr class="even">
<td>(a) Median</td>
<td>≈ 45.80 bu/ac</td>
<td><code>=MEDIAN(C2:C296)</code></td>
</tr>
<tr class="odd">
<td>(b) Std dev</td>
<td>≈ 17.22 bu/ac</td>
<td><code>=STDEV.S(C2:C296)</code></td>
</tr>
<tr class="even">
<td>(b) Variance</td>
<td>≈ 296.5 (bu/ac)²</td>
<td><code>=VAR.S(C2:C296)</code></td>
</tr>
<tr class="odd">
<td>(c) Min / Max</td>
<td>(lowest / highest reported)</td>
<td><code>=MIN(C2:C296)</code>, <code>=MAX(C2:C296)</code></td>
</tr>
<tr class="even">
<td>(c) Range</td>
<td>Max − Min</td>
<td><code>=MAX(C2:C296) - MIN(C2:C296)</code></td>
</tr>
<tr class="odd">
<td>(e) Count</td>
<td>≈ 285 RMs</td>
<td><code>=COUNT(C2:C296)</code></td>
</tr>
</tbody>
</table>
<p><strong>Part (b):</strong> Variance units are <strong>squared</strong> — (bu/ac)² — because variance averages the <em>squared</em> deviations. This is why standard deviation (the square root) is usually reported instead: it is back in bu/ac.</p>
<p><strong>Part (e):</strong> Use <code>COUNT</code> (counts numbers, skips blanks), <strong>not</strong> <code>COUNTA</code> (which would count text) and not the total row count. A handful of RMs did not report spring wheat, so the count is below the ~295 total rows.</p>
<p><strong>Common mistakes:</strong></p>
<ul>
<li>Reporting the total number of 2023 rows (295) instead of the number that actually <em>reported</em> spring wheat.</li>
<li>Confusing standard deviation with variance — they differ by a square.</li>
</ul>
</details>
<hr>
</section>
</section>
<section id="type-2-conditional-functions-and-lookups" class="level2">
<h2 class="anchored" data-anchor-id="type-2-conditional-functions-and-lookups">Type 2: Conditional Functions and Lookups</h2>
<p>These questions use conditional functions (<code>COUNTIF</code>, <code>AVERAGEIF</code>, <code>SUMIF</code>, <code>COUNTIFS</code>) and lookups (<code>XLOOKUP</code>, <code>INDEX</code>/<code>MATCH</code>) across the <strong>full, unfiltered</strong> dataset. Each answer should use an Excel formula.</p>
<p>Throughout, assume the data occupies the range shown by your import (row 1 is the header; columns A–J as in the table above). Adjust the row numbers to match your sheet.</p>
<section id="variant-2a" class="level3">
<h3 class="anchored" data-anchor-id="variant-2a">Variant 2A</h3>
<p><strong>(a)</strong> Across <strong>all years and RMs</strong>, how many rows have a <strong>canola yield strictly greater than 40 bu/ac</strong>?</p>
<p><strong>(b)</strong> What is the <strong>average canola yield in the year 2023 only</strong>? (Use <code>AVERAGEIF</code> on the <code>Year</code> column — no manual filtering.)</p>
<p><strong>(c)</strong> What is the <strong>average canola yield in 2010</strong> versus <strong>2021</strong>? (2021 was a severe drought year.) Which is higher, and by how much?</p>
<p><strong>(d)</strong> Use a lookup to find the <strong>canola yield in RM 1 in 2023</strong>. (Hint: you will need to match on <strong>two</strong> conditions — RM and Year. <code>XLOOKUP</code> with a concatenated key, or <code>INDEX</code>/<code>MATCH</code> with two criteria, both work.)</p>
<p><strong>(e)</strong> Write a formula that classifies each row’s canola yield as <code>"Low"</code> (below 20), <code>"Medium"</code> (20 to 40), or <code>"High"</code> (above 40).</p>
<details>
<summary>
<strong>Answers</strong>
</summary>
<p><em>Assume Year = col A, RM = col B, Canola = col E, data in rows 2:10650.</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 31%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Part</th>
<th>Value</th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(a) Count &gt; 40</td>
<td>(snapshot value)</td>
<td><code>=COUNTIF(E2:E10650, "&gt;40")</code></td>
</tr>
<tr class="even">
<td>(b) Avg 2023</td>
<td>≈ 33.88 bu/ac</td>
<td><code>=AVERAGEIF(A2:A10650, 2023, E2:E10650)</code></td>
</tr>
<tr class="odd">
<td>(c) Avg 2010 / 2021</td>
<td>2010 much higher</td>
<td><code>=AVERAGEIF(A2:A10650, 2010, E2:E10650)</code> and <code>=AVERAGEIF(A2:A10650, 2021, E2:E10650)</code></td>
</tr>
<tr class="even">
<td>(d) RM 1, 2023 canola</td>
<td>≈ 36.8 bu/ac</td>
<td>see below</td>
</tr>
</tbody>
</table>
<p><strong>Part (d) — two-criteria lookup.</strong> The tidiest modern approach is a <code>XLOOKUP</code> on a concatenated key, or a boolean <code>XLOOKUP</code>:</p>
<pre><code>=XLOOKUP(1&amp;"|"&amp;2023, B2:B10650&amp;"|"&amp;A2:A10650, E2:E10650)</code></pre>
<p>or with <code>INDEX</code>/<code>MATCH</code>:</p>
<pre><code>=INDEX(E2:E10650, MATCH(1&amp;"|"&amp;2023, B2:B10650&amp;"|"&amp;A2:A10650, 0))</code></pre>
<p>(Enter as an array formula in older Excel; modern Excel handles it directly.)</p>
<p><strong>Part (e):</strong></p>
<pre><code>=IFS(E2&lt;20, "Low", E2&lt;=40, "Medium", TRUE, "High")</code></pre>
<p>Copy down all rows. Blank cells will need handling — wrap in an <code>IF</code> to leave blanks blank: <code>=IF(E2="", "", IFS(...))</code>.</p>
<p><strong>Notes:</strong></p>
<ul>
<li>For (c), the drought contrast is real and stark — 2021 canola yields were far below 2010. This is the kind of pattern the data is good for.</li>
<li><code>AVERAGEIF</code>’s criterion for a number can be written bare (<code>2023</code>) or quoted (<code>"2023"</code>); both work.</li>
</ul>
</details>
</section>
<section id="variant-2b" class="level3">
<h3 class="anchored" data-anchor-id="variant-2b">Variant 2B</h3>
<p><strong>(a)</strong> How many rows report a <strong>lentil</strong> yield (i.e., how many non-blank cells in the Lentils column across all years)? (Hint: <code>COUNT</code>.)</p>
<p><strong>(b)</strong> What is the <strong>average barley yield across all years</strong> in <strong>RM 100</strong>? (Use <code>AVERAGEIF</code> on the <code>RM</code> column.)</p>
<p><strong>(c)</strong> How many rows have <strong>canola above 40 AND spring wheat above 45</strong>, in the same RM-year? (Use <code>COUNTIFS</code>.)</p>
<p><strong>(d)</strong> Use a lookup to find the <strong>spring wheat yield in RM 100 in 2023</strong>.</p>
<p><strong>(e)</strong> In how many rows is the <strong>canola yield above the overall average canola yield</strong>? (Use <code>COUNTIF</code> with the computed average.)</p>
<details>
<summary>
<strong>Answers</strong>
</summary>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 31%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Part</th>
<th>Value</th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(a) Lentil count</td>
<td>(snapshot value)</td>
<td><code>=COUNT(I2:I10650)</code></td>
</tr>
<tr class="even">
<td>(b) Avg barley, RM 100</td>
<td>(snapshot value)</td>
<td><code>=AVERAGEIF(B2:B10650, 100, F2:F10650)</code></td>
</tr>
<tr class="odd">
<td>(c) Canola&gt;40 &amp; wheat&gt;45</td>
<td>(snapshot value)</td>
<td><code>=COUNTIFS(E2:E10650, "&gt;40", C2:C10650, "&gt;45")</code></td>
</tr>
<tr class="even">
<td>(d) RM 100, 2023 wheat</td>
<td>≈ 52.9 bu/ac</td>
<td><code>=XLOOKUP(100&amp;"|"&amp;2023, B2:B10650&amp;"|"&amp;A2:A10650, C2:C10650)</code></td>
</tr>
<tr class="odd">
<td>(e) Above-average count</td>
<td>(snapshot value)</td>
<td><code>=COUNTIF(E2:E10650, "&gt;"&amp;AVERAGE(E2:E10650))</code></td>
</tr>
</tbody>
</table>
<p><strong>Notes:</strong></p>
<ul>
<li>For (e), the <code>"&gt;"&amp;AVERAGE(...)</code> trick builds the criterion text dynamically. You cannot write <code>"&gt;AVERAGE(E2:E10650)"</code> — that is treated as literal text.</li>
<li>For (a), use <code>COUNT</code> (numbers only), which naturally skips the many blanks in the Lentils column.</li>
</ul>
</details>
<hr>
</section>
</section>
<section id="type-3-pivottables" class="level2">
<h2 class="anchored" data-anchor-id="type-3-pivottables">Type 3: PivotTables</h2>
<p><strong>Use the long-format file for these questions:</strong> <a href="data/rm_yields_1990plus_long.csv"><code>rm_yields_1990plus_long.csv</code></a>. Because the crop name is in its own <code>Crop</code> column, you can put <strong>Crop</strong> on Rows and pivot <em>by crop</em> — something the wide file cannot do in a single PivotTable (see <a href="../module01.html#sec-wide-long" class="quarto-xref"><span>Wide vs.&nbsp;Long Data</span></a>). Create each PivotTable on a <strong>new sheet</strong>.</p>
<section id="variant-3a-comparing-crops" class="level3">
<h3 class="anchored" data-anchor-id="variant-3a-comparing-crops">Variant 3A — Comparing crops</h3>
<p><strong>(a)</strong> Build a PivotTable of <strong>average yield for each crop in 2023</strong> (put <code>Year</code> in Filters = 2023, <code>Crop</code> on Rows, <code>Yield</code> in Values → Average). Rank the crops from highest to lowest average yield.</p>
<p><strong>(b)</strong> Why does <strong>Lentils</strong> appear far larger than every other crop? What does that tell you about mixing it into the comparison?</p>
<p><strong>(c)</strong> Add <code>Unit</code> to the <strong>Filters</strong> and set it to <code>bu/ac</code> (excluding lentils). Now which crop has the highest average yield, and which the lowest?</p>
<details>
<summary>
<strong>Answers</strong>
</summary>
<p><strong>Setup:</strong> <code>Year</code> → Filters (set to 2023); <code>Crop</code> → Rows; <code>Yield</code> → Values, set to <strong>Average</strong> (right-click the value → Summarize Values By → Average).</p>
<p><strong>Part (a):</strong> Average yield by crop, 2023 (snapshot values):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Crop</th>
<th>Avg yield</th>
<th>Unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lentils</td>
<td>≈ 1314</td>
<td><strong>lb/ac</strong></td>
</tr>
<tr class="even">
<td>Oats</td>
<td>≈ 71.1</td>
<td>bu/ac</td>
</tr>
<tr class="odd">
<td>Barley</td>
<td>≈ 54.6</td>
<td>bu/ac</td>
</tr>
<tr class="even">
<td>Spring Wheat</td>
<td>≈ 42.9</td>
<td>bu/ac</td>
</tr>
<tr class="odd">
<td>Peas</td>
<td>≈ 34.0</td>
<td>bu/ac</td>
</tr>
<tr class="even">
<td>Canola</td>
<td>≈ 33.9</td>
<td>bu/ac</td>
</tr>
<tr class="odd">
<td>Durum</td>
<td>≈ 29.6</td>
<td>bu/ac</td>
</tr>
<tr class="even">
<td>Flax</td>
<td>≈ 20.3</td>
<td>bu/ac</td>
</tr>
</tbody>
</table>
<p><strong>Part (b):</strong> Lentils are reported in <strong>lb/ac</strong>, while every other crop is in <strong>bu/ac</strong>. The number is bigger because the <em>unit</em> is different, not because lentils out-yield everything — a classic reminder to check units before comparing. It should not be ranked against the bu/ac crops.</p>
<p><strong>Part (c):</strong> Filtering to <code>bu/ac</code> only, <strong>Oats</strong> has the highest average (≈71 bu/ac) and <strong>Flax</strong> the lowest (≈20 bu/ac) in 2023.</p>
<p><strong>Why long format matters here:</strong> “average yield <em>by crop</em>” requires <code>Crop</code> to be a single field you can drop on Rows. In the wide file the crops are eight separate columns, so this pivot is impossible without reshaping first.</p>
</details>
</section>
<section id="variant-3b-crops-over-time-the-drought-signal" class="level3">
<h3 class="anchored" data-anchor-id="variant-3b-crops-over-time-the-drought-signal">Variant 3B — Crops over time (the drought signal)</h3>
<p><strong>(a)</strong> Build a PivotTable with <code>Year</code> on Rows and <code>Crop</code> on Columns, <code>Yield</code> in Values → Average. Filter <code>Unit</code> to <code>bu/ac</code>. Read across a recent row: in a typical year, which crops sit highest and lowest?</p>
<p><strong>(b)</strong> Using the same table, compare <strong>canola in 2021 vs 2023</strong>. How large is the drought gap?</p>
<p><strong>(c)</strong> Looking down the columns, which single year stands out as a <strong>drought year</strong> — yields low across <em>all</em> crops at once?</p>
<details>
<summary>
<strong>Answers</strong>
</summary>
<p><strong>Setup:</strong> <code>Year</code> → Rows, <code>Crop</code> → Columns, <code>Yield</code> → Values (Average); <code>Unit</code> → Filters set to <code>bu/ac</code>.</p>
<p><strong>Part (a):</strong> In a typical recent year, <strong>Oats</strong> and <strong>Barley</strong> sit highest, the wheats and peas/canola in the middle, and <strong>Flax</strong> lowest — the same ordering the by-crop pivot showed.</p>
<p><strong>Part (b):</strong> Canola averaged <strong>≈ 21.9 bu/ac in 2021</strong> versus <strong>≈ 33.9 bu/ac in 2023</strong> — roughly a <strong>one-third drop</strong> in the drought year. The crop × year grid makes the gap jump out.</p>
<p><strong>Part (c):</strong> <strong>2021</strong> stands out — reading across that row, <em>every</em> crop’s average dips together, the signature of a widespread drought rather than a crop-specific problem. (Contrast with a year where only one crop is low, which would point to a pest or disease specific to that crop.)</p>
<p><strong>Note on units:</strong> always filter to a single <code>Unit</code> before comparing crops on one chart or table, so lentils (lb/ac) don’t swamp the bu/ac crops.</p>
</details>
<hr>
</section>
</section>
<section id="type-4-charts" class="level2">
<h2 class="anchored" data-anchor-id="type-4-charts">Type 4: Charts</h2>
<p>Create the following charts on a new sheet in your workbook. Each chart should have a descriptive title, labelled axes, and be formatted so that someone unfamiliar with the data can understand what it shows.</p>
<section id="variant-4a-distribution-of-yields" class="level3">
<h3 class="anchored" data-anchor-id="variant-4a-distribution-of-yields">Variant 4A — Distribution of yields</h3>
<p>Filter the data to <strong><code>Year = 2023</code></strong>.</p>
<p><strong>(a)</strong> Create a <strong>histogram</strong> of <strong>Canola</strong> yield across all RMs in 2023. Use approximately 10–15 bins.</p>
<p>Answer the following based on your histogram:</p>
<ul>
<li>Is the distribution roughly symmetric, left-skewed, or right-skewed?</li>
<li>Are there any obvious outliers (very low-yielding RMs)?</li>
<li>What is the approximate centre of the distribution?</li>
</ul>
<p><strong>(b)</strong> Create a <strong>box-and-whisker plot</strong> comparing <strong>Canola, Spring Wheat, and Barley</strong> yields in 2023 (three boxes on one chart).</p>
<p>Answer the following based on your box plot:</p>
<ul>
<li>Which crop has the highest median yield?</li>
<li>Which crop has the most variability (widest box / whiskers)?</li>
<li>Are outliers flagged for any crop?</li>
</ul>
<details>
<summary>
<strong>Answers</strong>
</summary>
<p><strong>Part (a) — Histogram:</strong></p>
<p><strong>How to create:</strong> Select the 2023 Canola column → <strong>Insert → Statistical Chart → Histogram</strong>. Right-click the horizontal axis → <strong>Format Axis</strong> → set the bin width to spread the ~3–60 bu/ac range across 10–15 bins.</p>
<p><strong>Formatting:</strong> Title like “Distribution of Canola Yields Across Saskatchewan RMs, 2023”; x-axis “Canola yield (bu/ac)”, y-axis “Number of RMs”.</p>
<p><strong>Expected interpretation:</strong></p>
<ul>
<li>The distribution is <strong>slightly left-skewed</strong> — most RMs cluster in the 30s–40s, with a tail of low-yielding (drought-affected) RMs pulling to the left.</li>
<li>A few RMs at the low end (single digits to ~15 bu/ac) look like <strong>outliers</strong> — real, drought-hit municipalities.</li>
<li>The <strong>centre</strong> is around 34–36 bu/ac (mean ≈33.9, median ≈35.5).</li>
</ul>
<p><strong>Part (b) — Box plot:</strong></p>
<p><strong>How to create:</strong> Arrange the three crop columns (2023 only) side by side and select them → <strong>Insert → Statistical Chart → Box and Whisker</strong>.</p>
<p><strong>Formatting:</strong> Title like “2023 Yield Distributions by Crop, Saskatchewan RMs”; label the axes.</p>
<p><strong>Expected interpretation:</strong></p>
<ul>
<li><strong>Barley</strong> typically has the highest median yield of the three; <strong>canola</strong> the lowest.</li>
<li><strong>Spring wheat</strong> tends to show wide spread (large IQR); all three show low-end outliers from drought-hit RMs.</li>
<li>Outliers appear as individual points beyond the whiskers — expect several at the low end.</li>
</ul>
<p><strong>Common mistakes:</strong></p>
<ul>
<li>Unlabelled axes or missing title — always include both.</li>
<li>Too few or too many histogram bins. Fewer than ~6 hides the shape; more than ~20 adds noise.</li>
<li>For the box plot, forgetting to select all three crop columns — you would get one box instead of three.</li>
</ul>
</details>
</section>
<section id="variant-4b-a-crop-over-time" class="level3">
<h3 class="anchored" data-anchor-id="variant-4b-a-crop-over-time">Variant 4B — A crop over time</h3>
<p>Use the <strong>full</strong> dataset (all years). Either file works here: from the <strong>wide</strong> file put <code>Canola</code> in Values; from the <strong>long</strong> file put <code>Yield</code> in Values and filter <code>Crop</code> to Canola. Both give the same by-year averages.</p>
<p><strong>(a)</strong> Build a PivotTable of <strong>average canola yield by year</strong> (Year on Rows, canola yield as Average), then create a <strong>line chart</strong> of average canola yield from 1990 to 2025.</p>
<p>Answer the following based on your line chart:</p>
<ul>
<li>Is there a long-run <strong>upward trend</strong> in average canola yield? Why might that be?</li>
<li>Which years show sharp <strong>dips</strong>? What do those dips correspond to?</li>
</ul>
<p><strong>(b)</strong> On the same idea, make a line chart of <strong>average spring wheat yield by year</strong>. Do wheat and canola tend to rise and fall <strong>together</strong> across years?</p>
<details>
<summary>
<strong>Answers</strong>
</summary>
<p><strong>Part (a):</strong></p>
<p><strong>How to create:</strong> PivotTable (<code>Year</code> → Rows, <code>Canola</code> → Values as Average) → select the result → <strong>Insert → Line Chart</strong> (or use a PivotChart). Title “Average Saskatchewan Canola Yield by Year, 1990–2025”; x-axis “Year”, y-axis “Average yield (bu/ac)”.</p>
<p><strong>Expected interpretation:</strong></p>
<ul>
<li>Yes — there is a clear <strong>long-run upward trend</strong>. Average canola yields have roughly risen over the decades, driven by <strong>better genetics (hybrids), agronomy, and equipment</strong>.</li>
<li>Sharp <strong>dips</strong> appear in known <strong>drought years</strong> — most notably <strong>2021</strong>, and others earlier in the series. These are weather shocks, not trend changes.</li>
</ul>
<p><strong>Part (b):</strong></p>
<ul>
<li>Wheat and canola yields largely <strong>move together</strong> year to year — a good year for one tends to be a good year for the other, because both respond to the same growing-season weather. The overlaid line charts should rise and fall roughly in sync, with drought years (like 2021) dipping for both.</li>
</ul>
<p><strong>Common mistakes:</strong></p>
<ul>
<li>Plotting <em>every RM</em> instead of the yearly average — you want the PivotTable’s per-year average, not 10,000 points.</li>
<li>Leaving the year axis as a “count” or treating years as categories unevenly — make sure the x-axis is the Year field.</li>
</ul>
</details>
<hr>
</section>
</section>
<section id="auto-generated-practice-quiz" class="level2">
<h2 class="anchored" data-anchor-id="auto-generated-practice-quiz">Auto-Generated Practice Quiz</h2>
<p>For a randomized practice quiz that draws one question from each type, visit the <a href="quiz/index.html">Practice Quiz Generator</a>. Each time you click <strong>Generate quiz</strong>, you get a fresh set of four questions — just like the real module test.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/agdataanalytics\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../practice/module01_bank.html" class="pagination-link" aria-label="Module 1 — Full Test Bank">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Module 1 — Full Test Bank</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../practice/module02_practice.html" class="pagination-link" aria-label="Module 2 — Test Bank">
        <span class="nav-page-text">Module 2 — Test Bank</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>