<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 1 — Full Test Bank – Agricultural Data Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../practice/module01_practice.html" rel="next">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4d4f1a06cb68144beac409d1735daa47.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Agricultural Data Analytics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../feedback.html" aria-current="page"> <i class="bi bi-chat-left-text" role="img">
</i> 
<span class="menu-text">Feedback</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../practice/module01_bank.html">Test Bank</a></li><li class="breadcrumb-item"><a href="../practice/module01_bank.html">Module 1 — Full Test Bank</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Title page</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction: How to Think About Data Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 1: Introduction to Excel</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module01a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module01b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Working with Data in Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module01c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 2: Introduction to R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module02a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Getting Started with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module02b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Loading Data and the Tidyverse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module02c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tidy Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 3: Working With Real Data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../moduleRDa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Starting a Project</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../moduleRDb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Getting Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../moduleRDc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Joining and Cleaning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 4: Graphing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Graphing Best Practices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Graphing in Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03e.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Graphing in R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 5: Using Artificial Intelligence</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module04a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">AI Tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module04b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">GitHub Copilot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module04c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Graphing with AI</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 6: Communicating Results</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Making a Workbook Someone Else Can Read</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Writing a Report</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module03f.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Presentations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 7: Relationships Between Variables</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module06a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Seeing Relationships</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module06b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module06c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Linear Models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 8: Probability and Random Variables</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Probability and Random Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 9: Probability and Simulation I</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Probability and Simulation I</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 10: Probability and Simulation II</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Probability and Simulation II</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 11: Sampling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 12: Randomization Tests</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Randomization Tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 13: Bootstrap Methods</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../module12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Bootstrap Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true">
 <span class="menu-text">Test Bank</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practice/module01_bank.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Module 1 — Full Test Bank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practice/module01_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 — Test Bank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practice/module02_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 — Test Bank</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../feedback.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Feedback</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#section-1-building-a-worksheet" id="toc-section-1-building-a-worksheet" class="nav-link active" data-scroll-target="#section-1-building-a-worksheet">Section 1 — Building a Worksheet</a>
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a></li>
  </ul></li>
  <li><a href="#section-2-descriptive-statistics-and-distributions" id="toc-section-2-descriptive-statistics-and-distributions" class="nav-link" data-scroll-target="#section-2-descriptive-statistics-and-distributions">Section 2 — Descriptive Statistics and Distributions</a>
  <ul>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">Question 6</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7</a></li>
  <li><a href="#question-8" id="toc-question-8" class="nav-link" data-scroll-target="#question-8">Question 8</a></li>
  <li><a href="#question-9" id="toc-question-9" class="nav-link" data-scroll-target="#question-9">Question 9</a></li>
  <li><a href="#question-10" id="toc-question-10" class="nav-link" data-scroll-target="#question-10">Question 10</a></li>
  </ul></li>
  <li><a href="#section-3-conditional-functions-lookups" id="toc-section-3-conditional-functions-lookups" class="nav-link" data-scroll-target="#section-3-conditional-functions-lookups">Section 3 — Conditional Functions &amp; Lookups</a>
  <ul>
  <li><a href="#question-11" id="toc-question-11" class="nav-link" data-scroll-target="#question-11">Question 11</a></li>
  <li><a href="#question-12" id="toc-question-12" class="nav-link" data-scroll-target="#question-12">Question 12</a></li>
  <li><a href="#question-13" id="toc-question-13" class="nav-link" data-scroll-target="#question-13">Question 13</a></li>
  <li><a href="#question-14" id="toc-question-14" class="nav-link" data-scroll-target="#question-14">Question 14</a></li>
  <li><a href="#question-15" id="toc-question-15" class="nav-link" data-scroll-target="#question-15">Question 15</a></li>
  </ul></li>
  <li><a href="#section-4-pivottables" id="toc-section-4-pivottables" class="nav-link" data-scroll-target="#section-4-pivottables">Section 4 — PivotTables</a>
  <ul>
  <li><a href="#question-16" id="toc-question-16" class="nav-link" data-scroll-target="#question-16">Question 16</a></li>
  <li><a href="#question-17" id="toc-question-17" class="nav-link" data-scroll-target="#question-17">Question 17</a></li>
  <li><a href="#question-18" id="toc-question-18" class="nav-link" data-scroll-target="#question-18">Question 18</a></li>
  <li><a href="#question-19" id="toc-question-19" class="nav-link" data-scroll-target="#question-19">Question 19</a></li>
  <li><a href="#question-20" id="toc-question-20" class="nav-link" data-scroll-target="#question-20">Question 20</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../practice/module01_bank.html">Test Bank</a></li><li class="breadcrumb-item"><a href="../practice/module01_bank.html">Module 1 — Full Test Bank</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Module 1 — Full Test Bank</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How this test bank works
</div>
</div>
<div class="callout-body-container callout-body">
<p>This bank holds <strong>20 questions</strong>: five in each of four sections. On the real test you receive <strong>four questions — one from each section</strong> — and you submit an <code>.xlsx</code> workbook with <strong>a separate sheet for each section’s answers</strong>. Each question is designed to take about <strong>8–10 minutes</strong>.</p>
<p>Expand each <strong>Answer</strong> block to check your work. Every value has been computed from the real data; when the source files are refreshed the exact numbers may shift slightly, but the method stays the same.</p>
</div>
</div>
<p><strong>The dataset.</strong></p>
<ul>
<li><strong>Saskatchewan RM Crop Yields</strong> (1990–2025). Average yield (bu/ac) for eight crops in every Rural Municipality. Wide file <code>rm_yields_1990plus.csv</code> for Sections 2–3; long file <code>rm_yields_1990plus_long.csv</code> for Section 4. Blank = crop not grown/reported that RM-year.</li>
</ul>
<p><strong>Working with a single year.</strong> Several questions ask you to work with one year of the data. Do <strong>not</strong> just apply a filter and point a formula at the whole column: as Module 1 explains, a filter hides rows from <em>you</em>, not from your formulas. Copy the rows you want onto a new sheet first, or use a conditional function that tests the year. If you copy 2023 out, you will have <strong>295 rows</strong> of data.</p>
<p><strong>Grading model.</strong> <strong>10%</strong> for presentation — labelled cells, sensible formats, a reader can follow the sheet. The remaining <strong>90%</strong> is split evenly across the four questions, and evenly across the parts within each question. Parts are marked on <strong>follow-through</strong>: if an early part is wrong but the later parts are correctly worked <em>from your own earlier answer</em>, the later parts still earn full marks.</p>
<blockquote class="blockquote">
<p><strong>Vocabulary note.</strong> Everything here uses only Module 1 tools: <code>SUM</code>, <code>AVERAGE</code>, <code>COUNT</code>, <code>COUNTA</code>, <code>MEDIAN</code>, <code>MODE.SNGL</code>, <code>MIN</code>, <code>MAX</code>, <code>ROUND</code>, <code>SUMPRODUCT</code>, <code>STDEV.S</code>, <code>VAR.S</code>, <code>QUARTILE.INC</code>, <code>PERCENTILE.INC</code>, <code>IF</code>, <code>COUNTIF</code>, <code>SUMIF</code>, <code>AVERAGEIF</code>, <code>XLOOKUP</code>; relative and absolute references; number and date formatting; sorting and filtering; wide vs long shape; and PivotTables.</p>
</blockquote>
<hr>
<section id="section-1-building-a-worksheet" class="level1">
<h1>Section 1 — Building a Worksheet</h1>
<p><em>These questions are about spreadsheet mechanics: anchoring references, formatting numbers and dates, and order of operations. The data is given in the question — copy the block and paste it into Excel.</em></p>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<p><em>Paste this block into a blank sheet.</em></p>
<pre class="plain"><code>Field   Acres   Yield (bu/ac)
North   120 41.2
South   240 38.6
Creek   95  44.8
Home    310 36.1
Rented  175 39.9</code></pre>
<p>Off to the right of the table, in a column with nothing else in it, put the canola price <strong>$14.20</strong> in a single labelled cell.</p>
<p><strong>(a)</strong> Add a <strong>Revenue ($/ac)</strong> column: each field’s yield times the price cell. Write the formula once and fill it down. Format as currency with two decimals.</p>
<p><strong>(b)</strong> Add a <strong>Total revenue ($)</strong> column: revenue per acre times that field’s acres. Format with a thousands separator and no decimals.</p>
<p><strong>(c)</strong> Under the table, use <code>SUM</code> to total the acres, the total bushels (yield × acres), and the total revenue.</p>
<p><strong>(d)</strong> In a spare column, repeat the (a) formula <em>without</em> the <code>$</code> signs and fill it down all five rows. Label the block clearly as the incorrect version.</p>
<p><strong>(e)</strong> Beside it, write one sentence saying what appears in those cells and why.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>With the price in <code>F1</code>: <code>=C2*$F$1</code> → $585.04, $548.12, $636.16, $512.62, $566.58.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>=D2*B2</code> → $70,204.80 · $131,548.80 · $60,435.20 · $158,912.20 · $99,151.50.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Acres <strong>940</strong>; bushels <strong>36,637.5</strong>; total revenue <strong>$520,252.50</strong>.</li>
</ol></li>
<li><ol start="4" type="a">
<li>The unanchored version, filled down five rows.</li>
</ol></li>
<li><ol start="5" type="a">
<li>The first row is right; every row below it returns <strong>$0.00</strong>, because the price reference walks down to <code>F2</code>, <code>F3</code>… which are empty. Excel treats an empty cell as zero here and reports no error, so the column simply fills with zeros.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<p><em>Paste this block into a blank sheet.</em></p>
<pre class="plain"><code>Field   Canola  Wheat   Barley
North   41.2    52.4    63.1
South   38.6    49.8    58.7
Creek   44.8    55.2    66.4
Home    36.1    47.3    61.9
Rented  39.9    51.0    60.2</code></pre>
<p>Directly above the three yield columns, enter the prices in a single row: Canola <strong>$14.20</strong>, Wheat <strong>$8.35</strong>, Barley <strong>$5.60</strong>.</p>
<p><strong>(a)</strong> To the right, build a revenue-per-acre block of the same shape. Write <strong>one</strong> formula in its top-left cell and fill it across and down to complete all fifteen cells.</p>
<p><strong>(b)</strong> State the formula you used, and say which part of the price reference is locked and which is not.</p>
<p><strong>(c)</strong> Under your revenue block, use <code>AVERAGE</code> to find the mean revenue per acre for each crop.</p>
<p><strong>(d)</strong> Which crop gives the highest average revenue per acre, and by how much over the second-placed crop?</p>
<p><strong>(e)</strong> A student anchors the price fully as <code>$B$1</code> instead. In one sentence, say what their wheat and barley columns would show and why nothing on the sheet would look broken.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>With prices in row 1 and the first yield in <code>B3</code>: <code>=B3*B$1</code>, filled across and down. Any layout works provided the price <strong>row</strong> is locked and the column is not.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Only the <strong>row</strong> is locked (<code>B$1</code>). Filling down must keep pointing at the price row; filling across must let the column move so each crop meets its own price.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Canola <strong>$569.70</strong>, Wheat <strong>$427.02</strong>, Barley <strong>$347.54</strong>.</li>
</ol></li>
<li><ol start="4" type="a">
<li><strong>Canola</strong>, by about <strong>$142.69</strong> over wheat (569.704 − 427.019 = 142.685; accept $142.68 or $142.69 — the difference lands exactly on a half-cent).</li>
</ol></li>
<li><ol start="5" type="a">
<li>Every column would use the canola price, so wheat and barley revenues would be roughly 70% and 150% too high. The sheet still fills with plausible dollar figures, so nothing signals the error.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<p><em>Paste this block into a blank sheet.</em></p>
<pre class="plain"><code>Date    Crop    Tonnes
14 September 2026   Canola  42.5
18 September 2026   Canola  38.0
23 September 2026   Wheat   61.2
2 October 2026  Wheat   55.8
9 October 2026  Barley  47.3</code></pre>
<p><strong>(a)</strong> Make sure Excel has read the dates as <strong>dates</strong>, not text, and format them as <code>DD-MMM-YYYY</code> (e.g.&nbsp;14-Sep-2026). Show tonnes to one decimal.</p>
<p><strong>(b)</strong> Add a <strong>Days since previous</strong> column. Leave the first row blank. Make sure the results show as plain numbers.</p>
<p><strong>(c)</strong> In one cell, compute the number of days from the first delivery to the last.</p>
<p><strong>(d)</strong> Use <code>SUM</code> to total the tonnes, and <code>AVERAGE</code> to find the mean load size.</p>
<p><strong>(e)</strong> In one sentence, explain why part (b) would fail if Excel had stored the dates as text rather than as dates.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Dates formatted <code>DD-MMM-YYYY</code>; tonnes <code>0.0</code>.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>=A3-A2</code> filled down → <strong>4, 5, 9, 7</strong> days. If the cell shows <code>04-Jan-1900</code> it inherited the date format; change it to Number.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>=A6-A2</code> = <strong>25</strong> days.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Total <strong>244.8</strong> tonnes; mean <strong>48.96</strong> tonnes.</li>
</ol></li>
<li><ol start="5" type="a">
<li>Excel stores a date as a number, which is why subtracting two of them gives a count of days. Text cannot be subtracted, so the formula would return an error instead of a gap.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-4" class="level3">
<h3 class="anchored" data-anchor-id="question-4">Question 4</h3>
<p><em>Paste this block into a blank sheet.</em></p>
<pre class="plain"><code>Load    Protein
A   0.1342
B   0.1285
C   0.1401
D   0.1198
E   0.1356</code></pre>
<p><strong>(a)</strong> Copy the protein column into a second column. Format the first as <strong>General</strong> and the second as <strong>Percentage with 2 decimals</strong>. Label both with the format used.</p>
<p><strong>(b)</strong> Under each column, compute the average with <code>AVERAGE</code>, formatting each the same way as the column above it.</p>
<p><strong>(c)</strong> The two averages display differently but hold the same number. In a spare cell, write that value to four decimal places.</p>
<p><strong>(d)</strong> The contract pays a premium on any load above 13.5% protein. Add a column using <code>IF</code> that returns <code>Yes</code> or <code>No</code>, and use <code>COUNTIF</code> to count how many qualify.</p>
<p><strong>(e)</strong> A student writes <code>=IF(B2&gt;13.5,"Yes","No")</code> and gets <code>No</code> for every load. In one sentence, explain the error.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>The same five values twice; only the format differs. General shows <code>0.1342</code>, <code>0.1285</code>…; Percentage shows <code>13.42%</code>, <code>12.85%</code>….</li>
</ol></li>
<li><ol start="2" type="a">
<li>Both averages hold the same number. General shows the full <code>0.13164</code>; the percentage column shows <code>13.16%</code>.</li>
</ol></li>
<li><ol start="3" type="a">
<li><strong>0.1316</strong>.</li>
</ol></li>
<li><ol start="4" type="a">
<li><code>=IF(B2&gt;0.135,"Yes","No")</code>; <code>=COUNTIF(D2:D6,"Yes")</code> = <strong>2</strong> (loads C and E).</li>
</ol></li>
<li><ol start="5" type="a">
<li>The cells hold proportions, not percentages — 0.1342, not 13.42. Nothing is above 13.5, so every row returns <code>No</code>. Formatting a cell as a percentage does not change the stored value.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-5" class="level3">
<h3 class="anchored" data-anchor-id="question-5">Question 5</h3>
<p><em>Paste this block into a blank sheet.</em></p>
<pre class="plain"><code>Field   Acres   Yield (bu/ac)
North   120 41.2
South   240 38.6
Creek   95  44.8
Home    310 36.1
Rented  175 39.9</code></pre>
<p><strong>(a)</strong> Use <code>AVERAGE</code> to find the plain mean of the five yields.</p>
<p><strong>(b)</strong> Add a <strong>Bushels</strong> column (yield × acres) and total it, along with the acres, using <code>SUM</code>.</p>
<p><strong>(c)</strong> The farm’s actual average yield is total bushels divided by total acres. Compute it. Format both averages to one decimal place.</p>
<p><strong>(d)</strong> Compute the same figure a second way, in a single cell, using <code>SUMPRODUCT</code> over <code>SUM</code>.</p>
<p><strong>(e)</strong> The two averages in (a) and (c) differ. In one or two sentences, say which one answers “what did this farm average across all its acres”, and what the plain mean is treating as equally important.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li><code>=AVERAGE(C2:C6)</code> = <strong>40.1</strong> bu/ac.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>=B2*C2</code> filled down; acres <strong>940</strong>, bushels <strong>36,637.5</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>=D7/B7</code> = <strong>39.0</strong> bu/ac.</li>
</ol></li>
<li><ol start="4" type="a">
<li><code>=SUMPRODUCT(C2:C6,B2:B6)/SUM(B2:B6)</code> = <strong>39.0</strong> — the same number in one step.</li>
</ol></li>
<li><ol start="5" type="a">
<li>The <strong>weighted</strong> average in (c) answers it, because it counts every bushel once regardless of which field grew it. The plain mean treats each <em>field</em> as equally important, so the 95-acre Creek field — the highest yielding of the five — counts as much as the 310-acre Home field, and pulls the answer up by about 1.1 bu/ac.</li>
</ol></li>
</ul>
</details>
</section>
</section>
<section id="section-2-descriptive-statistics-and-distributions" class="level1">
<h1>Section 2 — Descriptive Statistics and Distributions</h1>
<p><em>These questions use the <strong>Saskatchewan RM Crop Yields</strong> dataset (<code>rm_yields_1990plus.csv</code>): average yield in bushels per acre for each crop in every Rural Municipality. A blank cell means that crop was not grown or not reported in that RM that year.</em></p>
<section id="question-6" class="level3">
<h3 class="anchored" data-anchor-id="question-6">Question 6</h3>
<p>Work with the <strong>Canola</strong> column for 2023 (copy the 2023 rows to a sheet of their own first — see the note above).</p>
<p><strong>(a)</strong> Compute the mean and the median canola yield.</p>
<p><strong>(b)</strong> The two differ. State which is larger and, in one or two sentences, say what that tells you about how the low-yielding RMs are distributed.</p>
<p><strong>(c)</strong> Compute the standard deviation and the coefficient of variation.</p>
<p><strong>(d)</strong> Repeat (a) and (c) for the <strong>Barley</strong> column in the same year.</p>
<p><strong>(e)</strong> Barley’s standard deviation is much larger than canola’s. Using your CVs, explain in two sentences whether barley yields were genuinely more variable, and why comparing the raw standard deviations alone would mislead.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Mean <strong>33.88</strong>, median <strong>35.50</strong> bu/ac (n = 289).</li>
</ol></li>
<li><ol start="2" type="a">
<li>The mean is <strong>below</strong> the median, so a minority of RMs with unusually low yields — down to 3.4 bu/ac — pull the average beneath the middle value. Most RMs sit higher than the mean suggests.</li>
</ol></li>
<li><ol start="3" type="a">
<li>SD <strong>13.33</strong>; CV = 13.33 / 33.88 = <strong>0.394</strong>.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Barley: mean <strong>54.56</strong>, SD <strong>24.60</strong>, CV <strong>0.451</strong>.</li>
</ol></li>
<li><ol start="5" type="a">
<li>Barley’s SD is nearly twice canola’s, but barley also yields far more per acre, so part of that spread is just scale. The CVs (0.451 vs 0.394) show barley was only modestly more variable <em>relative to its own average</em>. Comparing raw SDs across crops with different means overstates the difference.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-7" class="level3">
<h3 class="anchored" data-anchor-id="question-7">Question 7</h3>
<p>Work with the <strong>Spring Wheat</strong> column for 2023, using the 2023 rows you extracted.</p>
<p><strong>(a)</strong> Compute the first and third quartiles with <code>QUARTILE.INC</code>, and the interquartile range.</p>
<p><strong>(b)</strong> Compute the 10th and 90th percentiles with <code>PERCENTILE.INC</code>.</p>
<p><strong>(c)</strong> In one sentence, say what the 10th percentile means for a farmer in this dataset.</p>
<p><strong>(d)</strong> Compute the range (<code>MAX</code> − <code>MIN</code>).</p>
<p><strong>(e)</strong> The range is far larger than the IQR. Explain in two sentences why, and say which of the two you would quote in a report describing a typical spread across RMs.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Q1 <strong>28.50</strong>, Q3 <strong>55.60</strong>, IQR <strong>27.10</strong> bu/ac.</li>
</ol></li>
<li><ol start="2" type="a">
<li>10th percentile <strong>19.34</strong>, 90th percentile <strong>64.92</strong> bu/ac.</li>
</ol></li>
<li><ol start="3" type="a">
<li>One RM in ten had an average spring wheat yield at or below 19.34 bu/ac that year.</li>
</ol></li>
<li><ol start="4" type="a">
<li>74.7 − 5.0 = <strong>69.70</strong> bu/ac.</li>
</ol></li>
<li><ol start="5" type="a">
<li>The range is set entirely by the two most extreme RMs, so a single failed or exceptional RM defines it. The IQR covers the middle half and ignores both tails, so it is the better description of a typical spread — quote the IQR, and mention the extremes separately if they matter.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-8" class="level3">
<h3 class="anchored" data-anchor-id="question-8">Question 8</h3>
<p>Work with the <strong>Canola</strong> column for 2023, using the 2023 rows you extracted.</p>
<p><strong>(a)</strong> Build a histogram of the canola yields with about 10–15 bins. Give it a descriptive title and label both axes.</p>
<p><strong>(b)</strong> State the mean and the median beneath the chart, and describe the shape in one or two sentences: symmetric, or skewed — and if skewed, in which direction. Say how the mean’s position relative to the median matches what you see.</p>
<p><strong>(c)</strong> A classmate applies a filter to show only 2023, leaves the full file in place, and writes <code>=AVERAGE</code> over the whole canola column. They get <strong>28.29</strong> rather than your figure. In two sentences, explain what they actually computed and why the filter did not help.</p>
<p><strong>(d)</strong> A classmate makes the same histogram with 3 bins and concludes the data is symmetric. In one or two sentences, explain what went wrong.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Histogram, 10–15 bins, titled and labelled.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Mean <strong>33.88</strong>, median <strong>35.50</strong>. <strong>Left-skewed</strong> — a tail toward the low yields: most RMs cluster between roughly 25 and 50 bu/ac with a thin tail down to 3.4. The mean sits below the median, which is exactly what a low tail does: the extreme values drag the average down while the middle value barely moves.</li>
</ol></li>
<li><ol start="3" type="a">
<li>They computed the mean canola yield across <strong>every year from 1990 to 2025</strong>, not 2023. A filter hides rows from the person looking at the sheet; it does nothing to the range a formula reads. The fix is to copy the 2023 rows to their own sheet, or to use a conditional function that tests the year.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Three bins are too coarse to show the tail. Each bin spans about 19 bu/ac, so the low RMs get absorbed into a wide left-hand bar and the asymmetry disappears. Bin width has to be fine enough to reveal the shape without showing random noise.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-9" class="level3">
<h3 class="anchored" data-anchor-id="question-9">Question 9</h3>
<p>Work with the 2023 rows you extracted. You will use the <strong>Canola</strong> and <strong>Barley</strong> columns.</p>
<p><strong>(a)</strong> Compute the mean of each, along with the mean of the <strong>Oats</strong> column.</p>
<p><strong>(b)</strong> Use <code>COUNT</code> on each of the three columns. The three counts differ. In one sentence, say what that difference tells you about the dataset.</p>
<p><strong>(c)</strong> Explain in one sentence why <code>COUNT</code> and <code>COUNTA</code> would give different answers if the blank cells contained the text <code>"n/a"</code> instead of being empty.</p>
<p><strong>(d)</strong> A student fills every blank canola cell with 0 and recomputes the mean. Compute what that mean would be, and state the difference from your answer in (a).</p>
<p><strong>(e)</strong> In two sentences, explain why filling blanks with zero is wrong here, and what the blank actually represents.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Canola <strong>33.88</strong>, Barley <strong>54.56</strong>, Oats <strong>71.14</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Canola 289, Barley 285, Oats 200. Not every crop is grown or reported in every RM, so the columns have different numbers of observations.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>COUNT</code> counts numbers only, so it would still return 289; <code>COUNTA</code> counts any non-empty cell, so it would also count the <code>"n/a"</code> entries and return 295 — the full number of 2023 rows.</li>
</ol></li>
<li><ol start="4" type="a">
<li>With 295 rows and six zeros, the mean falls to <strong>33.19</strong> — about <strong>0.69</strong> bu/ac lower.</li>
</ol></li>
<li><ol start="5" type="a">
<li>A blank means the crop was not grown or not reported, not that the RM harvested nothing. Entering 0 turns a missing observation into a measured failure and drags the average down.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-10" class="level3">
<h3 class="anchored" data-anchor-id="question-10">Question 10</h3>
<p>Using the whole dataset (all years), work with the <strong>Canola</strong> column.</p>
<p><strong>(a)</strong> Compute the mean canola yield for <code>Year = 2021</code> and for <code>Year = 2022</code>.</p>
<p><strong>(b)</strong> Compute the percentage change from 2021 to 2022 and format it as a percentage with one decimal.</p>
<p><strong>(c)</strong> State the formula you used and say which year belongs in the denominator, and why.</p>
<p><strong>(d)</strong> Compute the standard deviation for each of the two years.</p>
<p><strong>(e)</strong> In two sentences, use both the means and the standard deviations to describe what happened between the two years. Say what a single mean on its own would have hidden.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>2021 mean <strong>21.86</strong>, 2022 mean <strong>35.40</strong> bu/ac.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>=(B2-B1)/B1</code> = <strong>+61.9%</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>The <strong>starting</strong> year (2021) goes in the denominator: percentage change measures movement relative to where you began.</li>
</ol></li>
<li><ol start="4" type="a">
<li>2021 SD <strong>8.14</strong>; 2022 SD <strong>12.38</strong>.</li>
</ol></li>
<li><ol start="5" type="a">
<li>Average yields rose by about three-fifths after the 2021 drought, and the spread widened as well — RMs did not all recover equally. A mean alone would have shown the recovery but hidden the fact that the gap between good and poor RMs grew.</li>
</ol></li>
</ul>
</details>
</section>
</section>
<section id="section-3-conditional-functions-lookups" class="level1">
<h1>Section 3 — Conditional Functions &amp; Lookups</h1>
<p><em>These questions use the <strong>Saskatchewan RM Crop Yields</strong> dataset (<code>rm_yields_1990plus.csv</code>).</em></p>
<section id="question-11" class="level3">
<h3 class="anchored" data-anchor-id="question-11">Question 11</h3>
<p>Work with the 2023 rows you extracted.</p>
<p><strong>(a)</strong> Use <code>COUNTIF</code> to count the RMs with a canola yield above 40 bu/ac.</p>
<p><strong>(b)</strong> Use <code>COUNTIF</code> to count those at or below 20 bu/ac.</p>
<p><strong>(c)</strong> Use <code>AVERAGEIF</code> to find the mean <strong>barley</strong> yield in those RMs where canola came in above 40.</p>
<p><strong>(d)</strong> Compute the mean barley yield across all RMs in 2023, and compare it with your answer to (c).</p>
<p><strong>(e)</strong> In two sentences, say what the comparison suggests, and give one reason other than crop choice that might explain it.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li><code>=COUNTIF(canola_range,"&gt;40")</code> = <strong>114</strong> RMs. (In the shipped file canola is column <strong>E</strong>; use whatever range your 2023 rows occupy.)</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>=COUNTIF(canola_range,"&lt;=20")</code> = <strong>57</strong> RMs.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>=AVERAGEIF(canola_range,"&gt;40",barley_range)</code> = <strong>77.40</strong> bu/ac. Canola is tested, barley is averaged. Note this averages <strong>112</strong> RMs, not the 114 from (a): two of them have no barley figure, and <code>AVERAGEIF</code> skips blanks in the range it is averaging. Dividing a <code>SUMIF</code> by 114 instead gives 76.04 and is wrong.</li>
</ol></li>
<li><ol start="4" type="a">
<li>All-RM barley mean <strong>54.56</strong>; the good-canola RMs averaged <strong>22.83</strong> bu/ac more (accept 22.84 if computed from the rounded figures).</li>
</ol></li>
<li><ol start="5" type="a">
<li>RMs that grew canola well also grew barley well, which points to something affecting both crops rather than to the crops themselves. Growing-season rainfall is the obvious candidate — soil zone and seeding date would also do it.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-12" class="level3">
<h3 class="anchored" data-anchor-id="question-12">Question 12</h3>
<p>Work with the 2023 rows you extracted.</p>
<p><strong>(a)</strong> Use <code>IF</code> to add a column labelling each RM <code>Above</code> or <code>Below</code> according to whether its canola yield beats the 2023 canola mean. Compute the mean in its own cell and point the <code>IF</code> at that cell.</p>
<p><strong>(b)</strong> Use <code>COUNTIF</code> to count how many RMs fall in each category.</p>
<p><strong>(c)</strong> The two counts are not equal. In one or two sentences, explain what that tells you about the distribution.</p>
<p><strong>(d)</strong> Now repeat (a) and (b) using the <strong>median</strong> instead of the mean.</p>
<p><strong>(e)</strong> The median split is much closer to even. In two sentences, explain why that is guaranteed by the definition of the median, and what the mean split told you that the median split did not.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li><code>=IF(E2&gt;$M$1,"Above","Below")</code> where <code>M1</code> (any spare cell) holds <code>=AVERAGE(canola_range)</code> = 33.88.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Above <strong>153</strong>, Below <strong>136</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>More RMs sit above the mean than below it (153 to 136), which is the signature of a low tail: a minority of very poor RMs drags the mean down past the middle of the data.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Median 35.50 → Above <strong>143</strong>, Below <strong>146</strong>.</li>
</ol></li>
<li><ol start="5" type="a">
<li>The median is <em>defined</em> as the value with half the observations on each side, so the split is even by construction (143/146, the difference being ties at the median). The mean split is informative precisely because it is uneven — the 153/136 gap is a measure of the skew that the median split cannot show.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-13" class="level3">
<h3 class="anchored" data-anchor-id="question-13">Question 13</h3>
<p>Work with the 2023 rows you extracted. Build a small price table well clear of the data:</p>
<pre class="plain"><code>Crop    Price ($/bu)
Canola  14.20
Spring Wheat    8.35
Barley  5.60
Oats    4.50</code></pre>
<p><strong>(a)</strong> Use <code>XLOOKUP</code> to pull the canola price into a cell, looking it up by name rather than typing the number.</p>
<p><strong>(b)</strong> Add a <strong>Canola revenue ($/ac)</strong> column: each RM’s canola yield times the looked-up price. Write it once and fill it down.</p>
<p><strong>(c)</strong> Explain in one sentence which references in your formula had to be absolute.</p>
<p><strong>(d)</strong> Use <code>AVERAGE</code> to find the mean canola revenue per acre across RMs, and <code>MAX</code> to find the highest.</p>
<p><strong>(e)</strong> Copy your revenue column and paste it as <strong>values</strong> beside itself, labelled “at $14.20”. Now change the price in your price table to <strong>$11.50</strong> and paste the new column as values beside that, labelled “at $11.50”. In one sentence, explain why keeping the price in a looked-up cell is better practice than typing 14.20 into the formula.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>With the price table pasted well clear of the data — say in <code>L2:M5</code> — <code>=XLOOKUP("Canola",$L$2:$L$5,$M$2:$M$5)</code> = 14.20.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>=E2*$N$1</code> where <code>N1</code> holds the looked-up price and canola is column <strong>E</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>The lookup ranges (<code>$L$2:$L$5</code>, <code>$M$2:$M$5</code>) and the price cell (<code>$N$1</code>) — all must stay put as the formula fills down.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Mean <strong>$481.11</strong>/ac; maximum <strong>$853.42</strong>/ac.</li>
</ol></li>
<li><ol start="5" type="a">
<li>Both columns pasted as values, so the grader can see the before and after. Every revenue updated at once when the price changed: the price lives in one place, so it can be checked, sourced and changed without editing 289 formulas, and no stale number hides inside a formula.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-14" class="level3">
<h3 class="anchored" data-anchor-id="question-14">Question 14</h3>
<p>Work with the 2023 rows you extracted.</p>
<p><strong>(a)</strong> Use <code>SUMIF</code> to total the canola yields of RMs with a canola yield above 40 bu/ac.</p>
<p><strong>(b)</strong> Use <code>COUNTIF</code> to count those RMs, then divide to get their mean.</p>
<p><strong>(c)</strong> Check your answer to (b) using <code>AVERAGEIF</code>. The two should match.</p>
<p><strong>(d)</strong> In one sentence, say when you would prefer <code>SUMIF</code> and <code>COUNTIF</code> over <code>AVERAGEIF</code>.</p>
<p><strong>(e)</strong> A student writes <code>=COUNTIF(canola_range,"&gt;AVERAGE(canola_range)")</code> to count RMs above the mean, and gets 0. Explain the error in one or two sentences and give the formula that works.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li><code>=SUMIF(canola_range,"&gt;40")</code> = <strong>5,399.60</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li>5,399.60 / 114 = <strong>47.36</strong> bu/ac.</li>
</ol></li>
<li><ol start="3" type="a">
<li><code>=AVERAGEIF(canola_range,"&gt;40")</code> = <strong>47.36</strong> — the same.</li>
</ol></li>
<li><ol start="4" type="a">
<li>When you need the total as well as the average, or when the criterion range and the averaging range differ in a way that is easier to write out in two steps.</li>
</ol></li>
<li><ol start="5" type="a">
<li>Everything inside quotation marks is treated as literal text, so Excel searches for cells containing the characters <code>&gt;AVERAGE(...)</code> and finds none. Join the operator to the computed value instead: <code>=COUNTIF(canola_range,"&gt;"&amp;AVERAGE(canola_range))</code> = <strong>153</strong>.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-15" class="level3">
<h3 class="anchored" data-anchor-id="question-15">Question 15</h3>
<p>Work with the 2023 rows you extracted.</p>
<p><strong>(a)</strong> Use <code>COUNTIF</code> twice to count the RMs whose <strong>canola</strong> yield is above 40, and the RMs whose <strong>barley</strong> yield is above 70.</p>
<p><strong>(b)</strong> Use <code>AVERAGEIF</code> to find the mean canola yield in RMs where <strong>barley</strong> came in above 70 bu/ac. Note carefully which column is tested and which is averaged.</p>
<p><strong>(c)</strong> Compare that with the overall mean canola yield and state the difference.</p>
<p><strong>(d)</strong> Add an <code>IF</code> column flagging RMs where canola is above 40 <strong>and</strong> barley is above 70, returning <code>Both</code> or a blank. (<code>IF</code> alone is enough — nest a second <code>IF</code> inside the first.)</p>
<p><strong>(e)</strong> Count the <code>Both</code> RMs with <code>COUNTIF</code>, and in two sentences say what the number suggests about whether good canola RMs and good barley RMs are the same places.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Canola above 40: <strong>114</strong>. Barley above 70: <strong>96</strong>.</li>
</ol></li>
<li><ol start="2" type="a">
<li><code>=AVERAGEIF(barley_range,"&gt;70",canola_range)</code> = <strong>46.60</strong> bu/ac — testing barley, averaging canola.</li>
</ol></li>
<li><ol start="3" type="a">
<li>The overall canola mean is 33.88, so RMs with strong barley averaged <strong>12.72</strong> bu/ac more canola.</li>
</ol></li>
<li><ol start="4" type="a">
<li><code>=IF(E2&gt;40,IF(F2&gt;70,"Both",""),"")</code> — canola is column E, barley column F. The nested form is the one shown in Module 1.</li>
</ol></li>
<li><ol start="5" type="a">
<li><strong>86</strong> RMs qualify on both counts. That is most of the 96 strong-barley RMs, so good canola and good barley land in largely the same places — consistent with a shared cause such as rainfall rather than anything specific to either crop.</li>
</ol></li>
</ul>
</details>
</section>
</section>
<section id="section-4-pivottables" class="level1">
<h1>Section 4 — PivotTables</h1>
<p><em>These questions use the <strong>long</strong> version of the Saskatchewan RM data (<code>rm_yields_1990plus_long.csv</code>), with one row per RM-year-crop. A PivotTable can only group by a field that lives in its own column, which is why the long shape is needed here.</em></p>
<section id="question-16" class="level3">
<h3 class="anchored" data-anchor-id="question-16">Question 16</h3>
<p><strong>(a)</strong> Build a PivotTable with <strong>Crop</strong> in Rows and average <strong>Yield</strong> in Values. Change the summary from Sum to <strong>Average</strong>.</p>
<p><strong>(b)</strong> One crop shows an average in the thousands while the rest are in the tens. Name it and explain in one sentence what has gone wrong with the comparison.</p>
<p><strong>(c)</strong> Copy the table from (a) and paste it as values somewhere on your sheet so it survives. Then add <strong>Year</strong> to Columns and filter to 2021–2023.</p>
<p><strong>(d)</strong> Read off the average canola yield in each of those three years.</p>
<p><strong>(e)</strong> In two sentences, describe what happened to canola between 2021 and 2023, and say what the Crop-only table in (a) hid.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Crop in Rows, Yield in Values, set to Average.</li>
</ol></li>
<li><ol start="2" type="a">
<li><strong>Lentils</strong>, averaging about <strong>1,208</strong>. Lentils are reported in <strong>pounds</strong> per acre while every other crop is in bushels per acre, so the column mixes two units and the averages cannot be compared. The <code>Unit</code> column in the long file records which is which.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Year in Columns, filtered to 2021–2023.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Canola: 2021 <strong>21.86</strong>, 2022 <strong>35.40</strong>, 2023 <strong>33.88</strong> bu/ac.</li>
</ol></li>
<li><ol start="5" type="a">
<li>Canola yields collapsed in the 2021 drought and rose about 62% the following year, holding near that level in 2023. A single all-years average of about 28 bu/ac would have hidden a swing of that size entirely.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-17" class="level3">
<h3 class="anchored" data-anchor-id="question-17">Question 17</h3>
<p><strong>(a)</strong> Build a PivotTable of average <strong>Yield</strong> by <strong>Year</strong>, filtered to the <strong>Canola</strong> crop only.</p>
<p><strong>(b)</strong> Identify the three worst years and the three best, with their averages.</p>
<p><strong>(c)</strong> Change the summary from Average to <strong>Count</strong>. What is the count telling you, and why does it vary by year?</p>
<p><strong>(d)</strong> Switch back to Average and add <strong>Count</strong> as a second Values field so both appear side by side.</p>
<p><strong>(e)</strong> The counts are lower in the earliest years of the series than in recent ones. In two sentences, explain why a year built on fewer reporting RMs deserves more caution than one built on more.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Year in Rows, Yield in Values set to Average, Crop filtered to Canola.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Worst: <strong>2002</strong> (15.83), <strong>2003</strong> (17.03), <strong>2001</strong> (18.19). Best: <strong>2025</strong> (43.94), <strong>2016</strong> (42.18), <strong>2019</strong> (40.78).</li>
</ol></li>
<li><ol start="3" type="a">
<li>The count is the number of RMs reporting a canola yield that year. It varies because not every RM grows canola every year, and because reporting coverage changes over time.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Both fields in Values: Average of Yield and Count of Yield.</li>
</ol></li>
<li><ol start="5" type="a">
<li>An average built from fewer RMs is more sensitive to any single unusual RM, so it is a less reliable summary of the province. It may also cover a different set of RMs than other years, so a year-to-year comparison is not quite like for like.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-18" class="level3">
<h3 class="anchored" data-anchor-id="question-18">Question 18</h3>
<p><strong>(a)</strong> Build a PivotTable with <strong>Year</strong> in Rows and <strong>Crop</strong> in Columns, showing average <strong>Yield</strong>.</p>
<p><strong>(b)</strong> Filter to the years 2019–2023 and to Canola, Spring Wheat and Barley.</p>
<p><strong>(c)</strong> Read off the 2021 row. All three crops are low. What does that pattern suggest about the cause?</p>
<p><strong>(d)</strong> Compute, for each of the three crops, how much its 2022 average exceeded its 2021 average.</p>
<p><strong>(e)</strong> In two sentences, say which crop recovered most in absolute terms and which in proportional terms. If they are the same crop, say why that is not guaranteed — what would have to be true of a crop for the two answers to disagree?</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Year in Rows, Crop in Columns, Average of Yield in Values.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Filtered to 2019–2023 and the three crops.</li>
</ol></li>
<li><ol start="3" type="a">
<li>All three crops fell together, which points to a cause affecting the whole growing season rather than anything crop-specific — the 2021 drought.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Canola <strong>+13.54</strong> (21.86 → 35.40), Spring Wheat <strong>+15.58</strong> (30.22 → 45.80), Barley <strong>+26.50</strong> (34.83 → 61.33).</li>
</ol></li>
<li><ol start="5" type="a">
<li><strong>Barley</strong> recovered most in absolute terms (+26.50 bu/ac) <em>and</em> proportionally (+76%, against canola’s +62% and wheat’s +52%). Barley yields far more per acre to begin with, so its absolute gain would be largest even at an equal percentage — check both before claiming one crop recovered the most.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-19" class="level3">
<h3 class="anchored" data-anchor-id="question-19">Question 19</h3>
<p><strong>(a)</strong> Build a PivotTable of average <strong>Yield</strong> by <strong>Crop</strong>, with <strong>Year</strong> as a Filter (not in Rows or Columns).</p>
<p><strong>(b)</strong> Set the filter to 2021 and record the averages for <strong>Canola, Barley and Oats</strong> only.</p>
<p><strong>(c)</strong> Set it to 2022 and record the same three. Paste both sets of values somewhere on your sheet so they survive the filter change.</p>
<p><strong>(d)</strong> Compute the proportional change for each of the three, and say which improved most.</p>
<p><strong>(e)</strong> In two sentences, explain the difference between putting Year in the <strong>Filter</strong> area and putting it in <strong>Columns</strong>, and say when you would choose each.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Crop in Rows, Yield in Values set to Average, Year in Filters.</li>
</ol></li>
<li><ol start="2" type="a">
<li>2021 (bu/ac): Canola <strong>21.86</strong>, Barley <strong>34.83</strong>, Oats <strong>45.06</strong>.</li>
</ol></li>
<li><ol start="3" type="a">
<li>2022 (bu/ac): Canola <strong>35.40</strong>, Barley <strong>61.33</strong>, Oats <strong>85.77</strong>.</li>
</ol></li>
<li><ol start="4" type="a">
<li>Canola +62%, Barley +76%, <strong>Oats +90%</strong> (45.06 → 85.77) — oats improved most.</li>
</ol></li>
<li><ol start="5" type="a">
<li>The Filter area shows one year at a time and keeps the table small; Columns shows every year side by side so they can be compared directly. Use a Filter when you want a clean single-period table, and Columns when the comparison across periods is the point.</li>
</ol></li>
</ul>
</details>
</section>
<section id="question-20" class="level3">
<h3 class="anchored" data-anchor-id="question-20">Question 20</h3>
<p><strong>(a)</strong> Build a PivotTable with <strong>Crop</strong> in Rows and average <strong>Yield</strong> in Values, filtered to <code>Year = 2023</code>.</p>
<p><strong>(b)</strong> Add <strong>Count</strong> of Yield alongside the average.</p>
<p><strong>(c)</strong> The counts are not equal across crops. Name the two crops with the fewest observations and give their counts.</p>
<p><strong>(d)</strong> Copy the 2023 rows onto a sheet of their own, then compute those same two averages with <code>AVERAGEIF</code> on the crop column, and confirm they match the PivotTable.</p>
<p><strong>(e)</strong> In two sentences, say why it is worth checking a PivotTable result against a formula at least once, and what kind of mistake this catches.</p>
<details>
<summary>
Answer
</summary>
<ul>
<li><ol type="a">
<li>Crop in Rows, Average of Yield, filtered to 2023.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Both fields in Values.</li>
</ol></li>
<li><ol start="3" type="a">
<li><strong>Flax</strong> (<strong>164</strong>) and <strong>Durum</strong> (<strong>173</strong>). Lentils (196) and Oats (200) are also well below canola, wheat and barley at 285–289.</li>
</ol></li>
<li><ol start="4" type="a">
<li>On the extracted 2023 rows: <code>=AVERAGEIF(crop_range,"Flax",yield_range)</code> = <strong>20.31</strong> and the same for Durum = <strong>29.60</strong> — both match. Run the same formula over the <em>whole</em> file instead and Flax returns 20.53, the all-years average: the criterion selects the crop, not the year, so the year has to be handled by which rows you point at.</li>
</ol></li>
<li><ol start="5" type="a">
<li>A PivotTable silently applies whatever filters are set, and it is easy to leave one on from an earlier step or to summarise the wrong field. Recomputing one figure with a formula catches exactly that kind of error, which produces a plausible-looking number rather than an error message.</li>
</ol></li>
</ul>
</details>


</section>
</section>

</main> <!-- /main -->
<script>
// Wrap each executed chunk's console output in a collapsed <details> so
// students can predict what R will print before revealing it.
//
// Quarto has code-fold for *code*, but no equivalent for output, so we do it
// here: for every .cell-output block, build a <details class="console-fold">
// and move the output inside it. Runs once on DOMContentLoaded.
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll(".console-transcript, .cell-output").forEach(function (out) {
    // Don't double-wrap, and skip output already inside a transcript.
    if (out.closest("details.console-fold")) return;
    if (out.classList.contains("cell-output") && out.closest(".console-transcript")) return;

    var details = document.createElement("details");
    details.className = "console-fold";

    var summary = document.createElement("summary");
    // transcript = a full console session from console(); stderr =
    // messages/warnings; error = a deliberate mistake we're showing.
    if (out.classList.contains("console-transcript")) {
      summary.textContent = "Show console session";
    } else if (out.classList.contains("cell-output-error")) {
      summary.textContent = "Show R's error message";
    } else if (out.classList.contains("cell-output-stderr")) {
      summary.textContent = "Show console message";
    } else {
      summary.textContent = "Show console output";
    }
    details.appendChild(summary);

    out.parentNode.insertBefore(details, out);
    details.appendChild(out);
  });
});

// Split sidebar module labels ("Module 5: Probability and Random Variables")
// into a small number line above the title, so the module number is scannable
// and long titles stop wrapping mid-phrase. Quarto emits the whole label as one
// text node, so the split has to happen here rather than in CSS.
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll(".sidebar-item-section .menu-text").forEach(function (el) {
    if (el.querySelector(".module-label")) return;          // already split
    var m = el.textContent.match(/^\s*Module\s+(\d+)\s*:\s*(.+)$/);
    if (!m) return;                                          // not a module part

    el.textContent = "";
    var num = document.createElement("span");
    num.className = "module-label";
    num.textContent = "Module " + m[1];
    var title = document.createElement("span");
    title.className = "module-title";
    title.textContent = m[2];
    el.appendChild(num);
    el.appendChild(title);
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/agdataanalytics\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
  </div>
  <div class="nav-page nav-page-next">
      <a href="../practice/module01_practice.html" class="pagination-link" aria-label="Module 1 — Test Bank">
        <span class="nav-page-text">Module 1 — Test Bank</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>