<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Cleaning Data – Agricultural Data Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./module03c.html" rel="next">
<link href="./module03a.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-89ad577b4eee21b2557706cfbfdd3e54.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Agricultural Data Analytics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./feedback.html" aria-current="page"> <i class="bi bi-chat-left-text" role="img">
</i> 
<span class="menu-text">Feedback</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./module03a.html">Module 3: Getting and Combining Data</a></li><li class="breadcrumb-item"><a href="./module03b.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cleaning Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Title page</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction: How to Think About Data Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 1: Introduction to Excel</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module01a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module01b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Working with Data in Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module01c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 2: Introduction to R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module02a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Getting Started with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module02b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Loading Data and Packages in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module02c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Manipulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 3: Getting and Combining Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module03a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Getting Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module03b.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cleaning Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module03c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Merging Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 4: Graphing</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module04a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Graphing Best Practices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module04b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Graphing in Excel</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module04c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Graphing in R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 5: Using Artificial Intelligence</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module05a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">AI Tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module05b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">GitHub Copilot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module05c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Graphing with AI</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module05d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">AI Tools in Excel</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 6: Spatial Data and Mapping</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module06a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Thinking Spatially</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module06b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Working with Spatial Data in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module06c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Making and Interpreting Maps</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 7: Field-Level Data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module07a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">How Field-Level Data Are Produced</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module07b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Working with Real Machinery Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module07c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Mapping Field-Level Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 8: External Spatial Data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module08a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Obtaining Environmental and Remote-Sensing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module08b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Combining External and Field Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module08c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Mapping Integrated Field Information</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 9: Thinking About Modelling Data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module09a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Models as Simplifications</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module09b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Predictions, Errors, and Model Quality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module09c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Seeing Relationships</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 10: Correlation and Simple Linear Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module10a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module10b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module10c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Evaluating and Criticizing a Linear Model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 11: Advanced Visualization and Interactive Displays</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module11a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Advanced Graph Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module11b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Interactive Charts, Maps, and Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module11c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Dashboards and Visual Data Products</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Module 12: Communicating and Delivering Results</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module12_assignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Report and Presentation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module12a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Making a Workbook Someone Else Can Read</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module12b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Writing a Report</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./module12c.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Presentations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Test Bank</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./practice/module01_bank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1 - Test bank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./practice/module02_bank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2 — Test Bank</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./feedback.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Feedback</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Appendix</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-tidy-data" id="toc-sec-tidy-data" class="nav-link active" data-scroll-target="#sec-tidy-data"><span class="header-section-number">8.1</span> Data shape</a>
  <ul>
  <li><a href="#sec-unpivot" id="toc-sec-unpivot" class="nav-link" data-scroll-target="#sec-unpivot"><span class="header-section-number">8.1.1</span> Data shape in Excel</a></li>
  <li><a href="#sec-reshaping" id="toc-sec-reshaping" class="nav-link" data-scroll-target="#sec-reshaping"><span class="header-section-number">8.1.2</span> Data shape in R</a></li>
  </ul></li>
  <li><a href="#sec-data-cleaning" id="toc-sec-data-cleaning" class="nav-link" data-scroll-target="#sec-data-cleaning"><span class="header-section-number">8.2</span> Data cleaning</a>
  <ul>
  <li><a href="#know-what-the-values-mean" id="toc-know-what-the-values-mean" class="nav-link" data-scroll-target="#know-what-the-values-mean">Know what the values mean</a></li>
  <li><a href="#take-a-first-look" id="toc-take-a-first-look" class="nav-link" data-scroll-target="#take-a-first-look">Take a first look</a></li>
  <li><a href="#check-each-variable" id="toc-check-each-variable" class="nav-link" data-scroll-target="#check-each-variable">Check each variable</a></li>
  <li><a href="#check-variables-together" id="toc-check-variables-together" class="nav-link" data-scroll-target="#check-variables-together">Check variables together</a></li>
  <li><a href="#investigate-before-changing" id="toc-investigate-before-changing" class="nav-link" data-scroll-target="#investigate-before-changing">Investigate before changing</a></li>
  </ul></li>
  <li><a href="#sec-quality-issues" id="toc-sec-quality-issues" class="nav-link" data-scroll-target="#sec-quality-issues"><span class="header-section-number">8.3</span> Common data quality issues</a></li>
  <li><a href="#sec-cleaning-excel" id="toc-sec-cleaning-excel" class="nav-link" data-scroll-target="#sec-cleaning-excel"><span class="header-section-number">8.4</span> Data cleaning in Excel</a></li>
  <li><a href="#sec-cleaning-r" id="toc-sec-cleaning-r" class="nav-link" data-scroll-target="#sec-cleaning-r"><span class="header-section-number">8.5</span> Data cleaning in R</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./module03a.html">Module 3: Getting and Combining Data</a></li><li class="breadcrumb-item"><a href="./module03b.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cleaning Data</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-cleaning" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cleaning Data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>A file that opens without an error may still contain duplicate rows, inconsistent names, mixed units and missing values recorded as ordinary text. Data cleaning takes up a large part of most data analysis projects. Unfortunately, it is also the dullest part of the job. This chapter is about finding common problems and recording what you did about them.</p>
<section id="sec-tidy-data" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-tidy-data"><span class="header-section-number">8.1</span> Data shape</h2>
<p>The R packages we use for data cleaning are part of the tidyverse, which is organized around the idea of <strong>tidy data</strong>. The same idea matters in Excel. A dataset is tidy when:</p>
<ol type="1">
<li>Every variable has its own column.</li>
<li>Every observation has its own row.</li>
<li>Every value has its own cell.</li>
</ol>
<p>The definition is simple, but deciding what counts as a variable or an observation is not always obvious. Consider the RM yield data used in the previous chapter. In the original file, one row represents an RM in one year, while the yields for six crops occupy six columns.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">RM</th>
<th style="text-align: right;">Spring Wheat</th>
<th style="text-align: right;">Durum</th>
<th style="text-align: right;">Canola</th>
<th style="text-align: right;">Barley</th>
<th style="text-align: right;">Oats</th>
<th style="text-align: right;">Peas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">34.32</td>
<td style="text-align: right;">29.18</td>
<td style="text-align: right;">28.65</td>
<td style="text-align: right;">50.96</td>
<td style="text-align: right;">56.36</td>
<td style="text-align: right;">37.7</td>
</tr>
<tr class="even">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">40.50</td>
<td style="text-align: right;">38.40</td>
<td style="text-align: right;">32.10</td>
<td style="text-align: right;">68.10</td>
<td style="text-align: right;">75.70</td>
<td style="text-align: right;">26.2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">45.97</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">39.19</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">85.82</td>
<td style="text-align: right;">43.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">50.00</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">39.20</td>
<td style="text-align: right;">76.00</td>
<td style="text-align: right;">96.00</td>
<td style="text-align: right;">42.0</td>
</tr>
</tbody>
</table>
<p>We could make the data even wider. One row could represent an RM, with a separate column for every crop-year combination: <code>Canola_2024</code>, <code>Canola_2025</code>, <code>Barley_2024</code> and so on.</p>
<!-- TODO: Insert the RM table with one column per crop-year combination. -->
<p>Or we could make the data longer, with one row for each RM-year-crop combination and separate columns for <code>RM</code>, <code>year</code>, <code>crop</code> and <code>yield_bu_ac</code>.</p>
<!-- TODO: Insert the long RM-year-crop table. -->
<p>None of these shapes is always right or wrong. The useful shape depends on what you want to do. The long version works well for PivotTables because <code>crop</code> can be placed in the Rows, Columns or Filters area. In R, the same <code>crop</code> column can be filtered, grouped or mapped to a graph. A wider table may be easier for a person to read or for presenting a small number of results.</p>
<p>When you open a table, write down what one row represents and what each column represents. This usually makes the shape problem visible.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Other resources – tidy data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>R for Data Science (2nd ed.)</strong> – <a href="https://r4ds.hadley.nz/data-tidy">Chapter 5, “Data tidying”</a> develops the tidy-data idea and shows how to reshape datasets between long and wide forms.</li>
<li><strong>Video</strong> – Riffomonas Project, <a href="https://www.youtube.com/watch?v=ZVddiwrbrr4"><em>Reshaping data to be long or wide with pivot_longer and pivot_wider</em></a>.</li>
</ul>
</div>
</div>
</div>
<section id="sec-unpivot" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="sec-unpivot"><span class="header-section-number">8.1.1</span> Data shape in Excel</h3>
<div class="video-callout">
<div class="callout callout-style-default callout-note callout-titled" title="Video walkthrough of this section">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Video walkthrough of this section
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/tIWh5nmnUso" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
</div>
</div>
</div>
<p>The RM yields file (<a href="module03a.html#sec-direct-download" class="quarto-xref"><span>Section 7.5.2</span></a>) is wide, with one column for each crop. Power Query calls the wide-to-long operation <strong>Unpivot</strong>. Import the CSV with <strong>Data &gt; Get Data &gt; From Text/CSV</strong>, choose <strong>Transform Data</strong>, select <code>Year</code> and <code>RM</code>, and then choose <strong>Transform &gt; Unpivot Columns &gt; Unpivot Other Columns</strong>. Rename the two new columns <code>crop</code> and <code>yield_bu_ac</code> before loading the result.</p>
<p>Power Query returns 15,478 rows because <strong>Unpivot Other Columns</strong> drops source cells containing <code>null</code>. The R example below keeps those cells as <code>NA</code> and therefore returns 17,700 rows; add <code>values_drop_na = TRUE</code> to <code>pivot_longer()</code> when you want the two results to agree. The reverse operation is <strong>Pivot Column</strong> in Power Query or a PivotTable on a worksheet.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/pq_unpivot_1_getdata.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Importing the CSV with Data > Get Data > From Text/CSV. The preview shows the wide table, one column per crop. Choose Transform Data to open the Power Query Editor."><img src="images/pq_unpivot_1_getdata.png" class="img-fluid figure-img" alt="Importing the CSV with Data > Get Data > From Text/CSV. The preview shows the wide table, one column per crop. Choose Transform Data to open the Power Query Editor."></a></p>
<figcaption>Importing the CSV with <strong>Data &gt; Get Data &gt; From Text/CSV</strong>. The preview shows the wide table, one column per crop. Choose <strong>Transform Data</strong> to open the Power Query Editor.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/pq_unpivot_2_editor.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="In the Power Query Editor, select the Year and RM columns, then choose Transform > Unpivot Columns > Unpivot Other Columns."><img src="images/pq_unpivot_2_editor.png" class="img-fluid figure-img" alt="In the Power Query Editor, select the Year and RM columns, then choose Transform > Unpivot Columns > Unpivot Other Columns."></a></p>
<figcaption>In the Power Query Editor, select the <code>Year</code> and <code>RM</code> columns, then choose <strong>Transform &gt; Unpivot Columns &gt; Unpivot Other Columns</strong>.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/pq_unpivot_3_result.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="After unpivoting, the crop names sit in one column and the yields in another. Rename them crop and yield_bu_ac before loading."><img src="images/pq_unpivot_3_result.png" class="img-fluid figure-img" alt="After unpivoting, the crop names sit in one column and the yields in another. Rename them crop and yield_bu_ac before loading."></a></p>
<figcaption>After unpivoting, the crop names sit in one column and the yields in another. Rename them <code>crop</code> and <code>yield_bu_ac</code> before loading.</figcaption>
</figure>
</div>
</section>
<section id="sec-reshaping" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="sec-reshaping"><span class="header-section-number">8.1.2</span> Data shape in R</h3>
<div class="video-callout">
<div class="callout callout-style-default callout-note callout-titled" title="Video walkthrough of this section">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Video walkthrough of this section
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/bL24bFKpvSg" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
</div>
</div>
</div>
<p><code>pivot_longer()</code> does the same job as Unpivot. It takes several columns, puts their names in one column and puts their values in another. Here is the RM yields table:</p>
<div class="cell">
<div class="cell-output-display">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the wide table</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>yields_wide <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"practice/data/rm_yields_2015_2024.csv"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the wide data</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>yields_wide</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Put the crop names and yields into columns</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>yields_long <span class="ot">&lt;-</span> yields_wide <span class="sc">|&gt;</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">-</span><span class="fu">c</span>(Year, RM),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"crop"</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"yield_bu_ac"</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the long data</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>yields_long</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(yields_long)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="console-transcript">
<pre><code>&gt; # Load packages
&gt; library(tidyverse)
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors
&gt; 
&gt; # Read the wide table
&gt; yields_wide &lt;- read_csv(
+   "practice/data/rm_yields_2015_2024.csv",
+   show_col_types = FALSE
+ )
&gt; 
&gt; # Print the wide data
&gt; yields_wide
# A tibble: 2,950 × 8
    Year    RM `Spring Wheat` Durum Canola Barley  Oats  Peas
   &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1  2015     1           34.3  29.2   28.6   51.0  56.4  37.7
 2  2016     1           40.5  38.4   32.1   68.1  75.7  26.2
 3  2017     1           46.0  NA     39.2   NA    85.8  43.4
 4  2018     1           50    NA     39.2   76    96    42  
 5  2019     1           50.9  NA     32.4   83.5 102.   43.8
 6  2020     1           56    NA     39.9   94   120.   48.4
 7  2021     1           46.2  NA     33.2   63.7  84    37.7
 8  2022     1           52.4  NA     37.4   90.3 106.   47.4
 9  2023     1           50.8  NA     36.8   53    55.1  44.9
10  2024     1           46.7  NA     36.4   77.1  99.4  40.1
# ℹ 2,940 more rows
&gt; 
&gt; # Put the crop names and yields into columns
&gt; yields_long &lt;- yields_wide |&gt;
+   pivot_longer(
+     cols = -c(Year, RM),
+     names_to = "crop",
+     values_to = "yield_bu_ac"
+   )
&gt; 
&gt; # Print the long data
&gt; yields_long
# A tibble: 17,700 × 4
    Year    RM crop         yield_bu_ac
   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt;
 1  2015     1 Spring Wheat        34.3
 2  2015     1 Durum               29.2
 3  2015     1 Canola              28.6
 4  2015     1 Barley              51.0
 5  2015     1 Oats                56.4
 6  2015     1 Peas                37.7
 7  2016     1 Spring Wheat        40.5
 8  2016     1 Durum               38.4
 9  2016     1 Canola              32.1
10  2016     1 Barley              68.1
# ℹ 17,690 more rows
&gt; 
&gt; nrow(yields_long)
[1] 17700</code></pre>
</div>
</div>
</div>
<p>The column selection <code>-c(Year, RM)</code> means every column except <code>Year</code> and <code>RM</code>. Those two columns continue to identify the observation, while the six crop columns become values in the new <code>crop</code> column. The result has one row per RM-year-crop and six times as many rows as the wide table.</p>
<p><code>pivot_wider()</code> goes in the other direction. <code>names_from</code> supplies the new column names and <code>values_from</code> supplies the values placed under them:</p>
<div class="cell">
<div class="cell-output-display">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return the crop column to six separate crop columns</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>yields_long <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> crop,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> yield_bu_ac</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="console-transcript">
<pre><code>&gt; # Return the crop column to six separate crop columns
&gt; yields_long |&gt;
+   pivot_wider(
+     names_from = crop,
+     values_from = yield_bu_ac
+   )
# A tibble: 2,950 × 8
    Year    RM `Spring Wheat` Durum Canola Barley  Oats  Peas
   &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1  2015     1           34.3  29.2   28.6   51.0  56.4  37.7
 2  2016     1           40.5  38.4   32.1   68.1  75.7  26.2
 3  2017     1           46.0  NA     39.2   NA    85.8  43.4
 4  2018     1           50    NA     39.2   76    96    42  
 5  2019     1           50.9  NA     32.4   83.5 102.   43.8
 6  2020     1           56    NA     39.9   94   120.   48.4
 7  2021     1           46.2  NA     33.2   63.7  84    37.7
 8  2022     1           52.4  NA     37.4   90.3 106.   47.4
 9  2023     1           50.8  NA     36.8   53    55.1  44.9
10  2024     1           46.7  NA     36.4   77.1  99.4  40.1
# ℹ 2,940 more rows</code></pre>
</div>
</div>
</div>
<p>There is no single correct shape for every purpose. Analysis is often easier with long data, while a wider table can be useful for presenting results.</p>
</section>
</section>
<section id="sec-data-cleaning" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-data-cleaning"><span class="header-section-number">8.2</span> Data cleaning</h2>
<p>Before cleaning a new dataset, check what arrived. A file can contain the wrong units, missing records and duplicate observations without producing an error. A short inspection at the beginning can save a great deal of confusion later.</p>
<p>These checks can find problems, but they cannot prove that every value is correct. A yield of 55 bu/ac may be perfectly plausible and still belong to the wrong field. We need to understand the source as well as inspect the values.</p>
<section id="know-what-the-values-mean" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="know-what-the-values-mean">Know what the values mean</h3>
<p>Data cleaning relies on your ability to spot values that do not make sense. This means you need some idea of what the data should look like. A crop yield between 0 and 100 may be plausible when it is measured in bushels per acre, while the same crop measured in tonnes per acre will have much smaller values. The number alone is not enough.</p>
<p>Before looking for errors, answer a few questions:</p>
<ul>
<li>What does one row represent?</li>
<li>What population and time period does the file cover?</li>
<li>What units are used?</li>
<li>Which column or columns should identify one observation?</li>
<li>How are missing values and categories coded?</li>
<li>Has the file already been filtered, cleaned or aggregated?</li>
</ul>
<p>This information may be in a data dictionary, a README file or the page from which the data were downloaded. If it is not documented, you may need to ask the person who created the file.</p>
</section>
<section id="take-a-first-look" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="take-a-first-look">Take a first look</h3>
<p>Start with the basic structure:</p>
<ul>
<li>Count the rows and columns.</li>
<li>Inspect the column names and data types.</li>
<li>Look at several rows from the beginning and end of the file.</li>
<li>Check whether numbers or dates were imported as text.</li>
<li>Count repeated values of any column, or combination of columns, that should identify one row.</li>
</ul>
<p>An unexpected row count or repeated identifier may mean that records are missing, duplicated or stored at a different level than you expected. Looking at the first few rows is useful, but it will not reveal a problem near the bottom of a large file.</p>
</section>
<section id="check-each-variable" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="check-each-variable">Check each variable</h3>
<p>For a <strong>numeric variable</strong>:</p>
<ul>
<li>Count the observed and missing values.</li>
<li>Examine the minimum, quartiles, median, mean and maximum.</li>
<li>Plot a histogram or box plot.</li>
<li>Look for impossible values, extreme observations, several clusters and suspicious concentrations at zero.</li>
</ul>
<p>The useful limits depend on the subject. A negative crop yield is impossible, while a yield of 100 bu/ac may be unusual but real. Investigate an extreme value rather than automatically deleting it.</p>
<p>For a <strong>categorical variable</strong>:</p>
<ul>
<li>Count the distinct values and their frequencies.</li>
<li>Look for inconsistent capitalization, spelling and extra spaces, such as <code>Canola</code>, <code>canola</code> and <code>Canola</code>.</li>
<li>Check whether blank strings or codes such as <code>-99</code>, <code>N/A</code> and <code>unknown</code> represent missing values.</li>
<li>Investigate rare categories rather than assuming that they are mistakes.</li>
</ul>
<p>For a <strong>date variable</strong>:</p>
<ul>
<li>Check the earliest and latest dates.</li>
<li>Look for dates outside the period covered by the data.</li>
<li>Check for gaps, repeated dates and dates stored as text.</li>
</ul>
</section>
<section id="check-variables-together" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="check-variables-together">Check variables together</h3>
<p>Some problems appear only when two or more variables are compared:</p>
<ul>
<li>Seeding should occur before harvest.</li>
<li>Percentages should normally fall between 0 and 100.</li>
<li>Reported production should be consistent with acres and yield.</li>
<li>Category and location codes should agree with their documentation.</li>
</ul>
<p>A scatter plot can reveal an odd relationship between two numeric variables. A line plot can expose gaps or abrupt changes over time. Summaries grouped by year, region or source can show whether missing values or unusual measurements are concentrated in one part of the dataset.</p>
</section>
<section id="investigate-before-changing" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="investigate-before-changing">Investigate before changing</h3>
<p>When something looks wrong:</p>
<ol type="1">
<li>Return to the source record or documentation if possible.</li>
<li>Flag the observation rather than immediately deleting it.</li>
<li>Keep the raw file unchanged.</li>
<li>Record any correction, conversion or exclusion in a reproducible cleaning step.</li>
<li>If the correct treatment remains uncertain, report that uncertainty and compare the results with and without the questionable observations.</li>
</ol>
</section>
</section>
<section id="sec-quality-issues" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-quality-issues"><span class="header-section-number">8.3</span> Common data quality issues</h2>
<p>These are the issues I most commonly encounter with datasets:</p>
<ol type="1">
<li><p><strong>Awkward column names.</strong> In R, you will refer to column names constantly, so consistency matters. If you sometimes use <code>SpringWheat</code>, other times <code>Spring Wheat</code>, and still other times <code>spring-wheat</code>, you will continually have to remember which convention you chose.</p>
<p>A common best practice is <strong>snake case</strong>: use lowercase letters and replace spaces with underscores. For example, use <code>spring_wheat</code>.</p>
<p>Column names should be descriptive without becoming unnecessarily long. Whether you choose <code>yield</code> or <code>yield_bu_ac</code> depends on the dataset. If it contains several yield measures, names such as <code>yield_bu_ac</code> and <code>yield_kg_ha</code> clearly distinguish their units. If there is only one yield column, the simpler name <code>yield</code> may be sufficient.</p></li>
<li><p><strong>Text in a numeric column.</strong> Sometimes units or other text are included with numeric values. For example, a weight column might contain <code>38.2 t</code>, <code>42.1 t</code>, and <code>37.8 t</code>.</p>
<p>Excel or R will usually interpret such a column as text, preventing you from performing calculations such as finding the mean or standard deviation. You will need to separate the units from the values and convert the values to numbers. Ideally, the units should be recorded in the column name—for example, <code>weight_t</code>.</p></li>
<li><p><strong>Duplicate observations.</strong> A dataset may contain duplicate rows. These can arise from data-entry mistakes, combining files more than once, or recording the same observation in multiple systems.</p>
<p>Duplicates are often data-quality problems, but identical rows are not necessarily errors. Two producers, fields, or transactions may legitimately have the same recorded values. Before removing duplicates, determine what uniquely identifies an observation and investigate why the duplication occurred.</p></li>
<li><p><strong>Missing values.</strong> Ideally, missing values are stored as blank cells or as <code>NA</code>. However, they may instead be represented by codes such as <code>-99</code>, <code>N/A</code>, <code>missing</code>, or <code>9999</code>.</p>
<p>You need to identify these codes and convert them to a consistent missing-value representation. Be careful: a code such as <code>0</code> may indicate a missing value in one dataset but a genuine observation in another. Consult the dataset’s documentation whenever possible.</p></li>
<li><p><strong>Impossible or implausible values.</strong> A dataset may contain values that are impossible, such as negative yields, or highly implausible, such as a wheat yield of 1,250 bu/acre.</p>
<p>Examining the minimum and maximum of each numeric variable is a quick way to identify potential problems. Histograms and other graphs can also reveal unusual observations. These values should be investigated before being corrected or removed; an unusual value is not necessarily an error.</p></li>
<li><p><strong>Mixed units.</strong> A column may contain values recorded in different units. For example, some weights might be reported in tonnes and others in kilograms.</p>
<p>A histogram can help identify mixed units. Suppose you plot nitrogen application rates and find that 30% of observations fall below 1 while the remaining 70% are above 100. This pattern may indicate that some producers recorded tonnes per hectare while others recorded kilograms per hectare.</p>
<p>Once you identify mixed units, convert all observations to a common unit and record that unit clearly in the column name or dataset documentation.</p></li>
<li><p><strong>Inconsistent categories.</strong> Data based on individual reporting often contain categories recorded in inconsistent ways. For example, the same wheat variety might appear as <code>Brandon</code>, <code>AAC Brandon</code>, <code>Brandon AAC</code>, and <code>Brndon</code>.</p>
<p>Listing the unique categories and counting the number of observations in each is a useful way to find these inconsistencies. You can then standardize the different versions under a single category, such as <code>AAC Brandon</code>.</p></li>
</ol>
<p>All seven issues appear together in <a href="practice/data/field_records_messy.csv"><code>field_records_messy.csv</code></a>, a season of spring wheat field records constructed for practice. The first ten rows:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Field ID</th>
<th>VARIETY_NAME</th>
<th style="text-align: right;">Acres</th>
<th style="text-align: right;">Yield (bu/ac)</th>
<th>harvest weight</th>
<th style="text-align: right;">N rate</th>
<th>Moisture %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F001</td>
<td>AAC Viewfield</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">67.6</td>
<td>297.7 t</td>
<td style="text-align: right;">97.1</td>
<td>12.4</td>
</tr>
<tr class="even">
<td>F002</td>
<td>Brandon</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">54.9</td>
<td>476.0 t</td>
<td style="text-align: right;">96.2</td>
<td>14.7</td>
</tr>
<tr class="odd">
<td>F003</td>
<td>CDC Landmark</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">54.4</td>
<td>172.6 t</td>
<td style="text-align: right;">0.081</td>
<td>12.3</td>
</tr>
<tr class="even">
<td>F002</td>
<td>Brandon</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">54.9</td>
<td>476.0 t</td>
<td style="text-align: right;">96.2</td>
<td>14.7</td>
</tr>
<tr class="odd">
<td>F004</td>
<td>Brandon AAC</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">-99</td>
<td>642.5 t</td>
<td style="text-align: right;">116.7</td>
<td>15.4</td>
</tr>
<tr class="even">
<td>F005</td>
<td>CDC Landmark</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">65.8</td>
<td>561.5 t</td>
<td style="text-align: right;">89.9</td>
<td>12.3</td>
</tr>
<tr class="odd">
<td>F006</td>
<td>Brndon</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">50.8</td>
<td>222.8 t</td>
<td style="text-align: right;">0.113</td>
<td>N/A</td>
</tr>
<tr class="even">
<td>F005</td>
<td>CDC Landmark</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">65.8</td>
<td>561.5 t</td>
<td style="text-align: right;">89.9</td>
<td>12.3</td>
</tr>
<tr class="odd">
<td>F007</td>
<td>AAC Viewfield</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">-12</td>
<td>138.6 t</td>
<td style="text-align: right;">135.9</td>
<td>14.5</td>
</tr>
<tr class="even">
<td>F008</td>
<td>AAC Brandon</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">60.3</td>
<td>264.0 t</td>
<td style="text-align: right;">127.3</td>
<td>12.4</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Column names have spaces, capitals and special characters</li>
<li>Harvest weight has its unit typed into the cell</li>
<li>F002 and F005 each appear twice, identically</li>
<li>Some yields are reported as -99 (a typical missing value code)</li>
<li>F007 has a yield of -12, which is impossible</li>
<li>The nitrogen rates for F003 and F006 sit below 1 while the rest sit near 100 – tonnes against kilograms per hectare</li>
<li>The same variety appears as Brandon, Brandon AAC, Brndon and AAC Brandon</li>
</ol>
<p>The quick check from the list – the minimum and maximum of every numeric column – surfaces more, computed here over the full file:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Column</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yield (bu/ac)</td>
<td style="text-align: right;">-99</td>
<td style="text-align: right;">1250</td>
<td style="text-align: right;">74.5</td>
<td style="text-align: right;">55.8</td>
</tr>
<tr class="even">
<td>N rate</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">135.9</td>
<td style="text-align: right;">71.5</td>
<td style="text-align: right;">89.9</td>
</tr>
<tr class="odd">
<td>harvest weight</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td>Moisture %</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">-</td>
</tr>
</tbody>
</table>
<p>The yield minimum is a missing-value code and the maximum is twenty times a real yield, and together they pull the mean eighteen bushels above the median. The N rate minimum and maximum are in different units. The last two columns refuse to summarize at all: the unit suffix and the missing-value codes make them text, which is issue 2 doing its damage before any analysis starts.</p>
</section>
<section id="sec-cleaning-excel" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-cleaning-excel"><span class="header-section-number">8.4</span> Data cleaning in Excel</h2>
<div class="video-callout">
<div class="callout callout-style-default callout-note callout-titled" title="Video walkthrough of this section">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Video walkthrough of this section
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/lITVHVsyOX4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
</div>
</div>
</div>
<p>The following Excel workbook shows some steps in checking and then cleaning the data. In the DataSummary worksheet, the numeric variables are summarized, getting the mean, median, minimum and maximum and a histogram is plotted. For the categorical variables, the <code>UNIQUE()</code> function is used to list the distinct values and the <code>COUNTIF()</code> function is used to count how many times each distinct value appears. Finally, we counted the number of rows using <code>=ROWS(RawData!A2:A39)</code> and the number of distinct rows using <code>=ROWS(UNIQUE(RawData!A2:A39))</code>. The difference between these two counts is the number of duplicate rows.</p>
<p>After diagnosing these issues, the best way to clean the data is through a Power Query which creates a transparent and reproducible workflow. The output of the Power Query is in the workbook and the video at the top of this section explains the steps taken to clean the data.</p>
<div class="workbook-callout">
<!-- Anyone-view link expires 2026-11-29 under the University of Saskatchewan 90-day policy. -->
<div class="excel-embed">
<iframe width="100%" height="700" frameborder="0" scrolling="no" src="https://usaskca1-my.sharepoint.com/personal/pjs998_usask_ca/_layouts/15/Doc.aspx?sourcedoc=%7BA96B2111-6943-487A-B1CD-2B84892058BB%7D&amp;action=embedview&amp;wdAllowInteractivity=False&amp;wdDownloadButton=True&amp;wdInConfigurator=True&amp;ActiveCell=%27DataSummary%27!A1">
</iframe>
</div>
<p><a href="textbook_examples/mod03_field_records_cleaning.xlsx">Download this workbook</a> · <a href="https://usaskca1-my.sharepoint.com/:x:/g/personal/pjs998_usask_ca/IQARIWupQ2l6SLHNK4SJIFi7AaPD784L8M-lxPSEBlwjw2I?e=Gd8AR1">Open online</a> (File → Save a Copy to view formulas and edit)</p>
</div>
</section>
<section id="sec-cleaning-r" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="sec-cleaning-r"><span class="header-section-number">8.5</span> Data cleaning in R</h2>
<p>Data cleaning is – in my view – easier in R than in Excel. We can write a easy to read R script that can be applied to any dataset.</p>
<p>The following code solves the seven issues above. There are a few new functions that we need to learn. The first, and most important, is <code>if_else()</code>.</p>
<p>In R the whole job fits in one script: read the raw file, check it, apply the cleaning rules and write the cleaned copy somewhere else. The script is the record of what was done, and when a new version of the raw file arrives it can be rerun from the top. The full script is <a href="practice/field_records_cleaning.R"><code>field_records_cleaning.R</code></a>; this section walks through it in stages.</p>
<p>The header describes the script, and the read step already deals with part of issue 4: the <code>na</code> argument of <code>read_csv()</code> lists the codes that mean missing, so <code>N/A</code>, <code>missing</code> and the blank cell all become <code>NA</code> on the way in.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This script loads field_records_messy.csv, checks for data quality and cleads the data.</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ---</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Read</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the file, declaring the missing-value codes up front (issue 4)</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>records <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/field_records_messy.csv"</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">na =</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">"N/A"</span>, <span class="st">"missing"</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Column names and types as they arrived</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(records)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="do">## This reveals a first set of issues: harvest weight is text when it should be numeric.  Moreover, column names are a mess.</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of every column: the min and max expose the planted problems</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(records)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="do">##This reveals further issues with the minimum and maximum of yield, and the minimum and 1st quartile of the nitrogen rate.  We might want to plot the histogram of the nitrogen rate to visualize the issue.</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(records<span class="sc">$</span><span class="st">`</span><span class="at">N rate</span><span class="st">`</span>, <span class="at">breaks =</span><span class="dv">20</span>)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the categories: the same variety appears under four spellings</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>records <span class="sc">|&gt;</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(VARIETY_NAME, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the rows, then the distinct rows: the difference is the duplicates</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(records)</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(<span class="fu">distinct</span>(records))</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="do">## We can dig futher into all these issues by visualizing/sorting the data in our Positron viewer, or printing it in the console.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="module03b_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="module03b_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="console-transcript">
<pre><code>&gt; library(janitor)

Attaching package: 'janitor'
The following objects are masked from 'package:stats':

    chisq.test, fisher.test
&gt; 
&gt; records &lt;- read_csv(
+   "data/field_records_messy.csv",
+   na = c("", "N/A", "missing")
+ )
Rows: 38 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): Field ID, VARIETY_NAME, harvest weight
dbl (4): Acres, Yield (bu/ac), N rate, Moisture %

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
&gt; 
&gt; glimpse(records)
Rows: 38
Columns: 7
$ `Field ID`       &lt;chr&gt; "F001", "F002", "F003", "F002", "F004", "F005", "F006…
$ VARIETY_NAME     &lt;chr&gt; "AAC Viewfield", "Brandon", "CDC Landmark", "Brandon"…
$ Acres            &lt;dbl&gt; 160, 320, 120, 320, 320, 320, 160, 320, 80, 160, 160,…
$ `Yield (bu/ac)`  &lt;dbl&gt; 67.6, 54.9, 54.4, 54.9, -99.0, 65.8, 50.8, 65.8, -12.…
$ `harvest weight` &lt;chr&gt; "297.7 t", "476.0 t", "172.6 t", "476.0 t", "642.5 t"…
$ `N rate`         &lt;dbl&gt; 97.100, 96.200, 0.081, 96.200, 116.700, 89.900, 0.113…
$ `Moisture %`     &lt;dbl&gt; 12.4, 14.7, 12.3, 14.7, 15.4, 12.3, NA, 12.3, 14.5, 1…
&gt; 
&gt; summary(records)
      Field ID     VARIETY_NAME     Acres       Yield (bu/ac)    
 Length   :38   Length   :38    Min.   : 80.0   Min.   : -99.00  
 N.unique :36   N.unique : 6    1st Qu.:160.0   1st Qu.:  51.55  
 N.blank  : 0   N.blank  : 0    Median :160.0   Median :  55.85  
 Min.nchar: 4   Min.nchar: 6    Mean   :191.6   Mean   :  74.47  
 Max.nchar: 4   Max.nchar:13    3rd Qu.:240.0   3rd Qu.:  61.58  
                                Max.   :320.0   Max.   :1250.00  
                                                                 
   harvest weight     N rate           Moisture %     
 Length   :38     Min.   :  0.0800   Min.   :  11.60  
 N.unique :36     1st Qu.:  0.1293   1st Qu.:  12.40  
 N.blank  : 0     Median : 89.9000   Median :  14.70  
 Min.nchar: 7     Mean   : 71.5021   Mean   : 299.33  
 Max.nchar: 7     3rd Qu.:104.0500   3rd Qu.:  15.45  
                  Max.   :135.9000   Max.   :9999.00  
                                     NAs    :3        
&gt; 
&gt; hist(records$`N rate`, breaks = 20)
&gt; 
&gt; records |&gt;
+   count(VARIETY_NAME, sort = TRUE)
# A tibble: 6 × 2
  VARIETY_NAME      n
  &lt;chr&gt;         &lt;int&gt;
1 CDC Landmark     13
2 AAC Viewfield     6
3 Brandon           6
4 Brandon AAC       5
5 AAC Brandon       4
6 Brndon            4
&gt; 
&gt; nrow(records)
[1] 38
&gt; nrow(distinct(records))
[1] 36</code></pre>
</div>
</div>
</div>
<p>The transcript shows the problems found earlier: the yield runs from -99 to 1250, the moisture maximum is the 9999 code, the harvest weight arrived as text, the variety appears under four spellings, and the file has 38 rows but only 36 distinct ones.</p>
<p>Now let’s clean the data. We will use a few different new functions:</p>
<ul>
<li><code>clean_names()</code> converts every column name to snake case, which fixes issue 1. For example, <code>VARIETY_NAME</code> becomes <code>variety_name</code>.</li>
<li><code>rename()</code> if we are still not happy with just using clean_names(), we can rename columns to whatever we want. For example, <code>variety_name</code> could be renamed to <code>variety</code>.</li>
<li><code>if_else()</code> is a conditional function. Similar to <code>IF</code> in Excel, it takes three arguments: a condition, a value to return if the condition is true, and a value to return if the condition is false. For example, <code>mutate(yield = if_else(yield &lt; 0, NA, yield))</code> would mean to mutate the yield column such that, if the yield is less than 0 replace it with NA and otherwise return what was in the yield column.</li>
<li><code>parse_number()</code> removes text from numbers, so that <code>142.9 t</code> becomes <code>142.9</code>.</li>
</ul>
<p>The yield rule blanks the -99 code, the negative and the 1250 rather than correcting them, because there is nothing defensible to replace them with.</p>
<div class="cell">
<div class="cell-output-display">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">## We can clean column names using the clean_names() function from the janitor package.  It converts all column names to lower case and replaces spaces with underscores.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>records_clean_names <span class="ot">&lt;-</span> records <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(records_clean_names)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="do">## We can remove duplicate rows using the distinct() function.  It removes any rows that are identical to another row in the dataset.  This is useful for removing accidental duplicates that may have been introduced during data entry or data processing.</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>records_unique <span class="ot">&lt;-</span> <span class="fu">distinct</span>(records_clean_names)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(records_unique)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="do">## We can strip the unit text from the weights and make them numeric using the parse_number() function.  This function extracts the numeric part of a string and converts it to a numeric value.  This is useful for cleaning up data that may have been entered with units or other text.</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>records_weight_fix <span class="ot">&lt;-</span> records_clean_names <span class="sc">|&gt;</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">harvest_weight =</span> <span class="fu">parse_number</span>(harvest_weight))</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>records_weight_fix<span class="sc">$</span>harvest_weight</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="do">## We can change yields below 0 and above 200 to NA using the if_else() function.  This function allows us to create a new variable based on a condition.  In this case, we are creating a new variable called yield_bu_ac that is equal to the original yield_bu_ac variable if it is between 0 and 200, and NA otherwise.</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>records_yield_fix <span class="ot">&lt;-</span> records_clean_names <span class="sc">|&gt;</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">yield_bu_ac =</span> <span class="fu">if_else</span>(yield_bu_ac <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">|</span> yield_bu_ac <span class="sc">&gt;</span> <span class="dv">200</span>,</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>                                <span class="cn">NA</span>,</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>                                yield_bu_ac))</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(records_yield_fix<span class="sc">$</span>yield_bu_ac)</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a><span class="do">## We can fix the variety names in the same way using the if_else() function.  The three arguments would say if variety is one of "Brandon", "Brandon AAC", or "Brndon", then replace it with "AAC Brandon", otherwise leave it as is.</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>records_variety_fix <span class="ot">&lt;-</span> records_clean_names <span class="sc">|&gt;</span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">variety_name =</span> <span class="fu">if_else</span>(variety_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Brandon"</span>, <span class="st">"Brandon AAC"</span>, <span class="st">"Brndon"</span>),</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"AAC Brandon"</span>,</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>                           variety_name))</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>records_variety_fix <span class="sc">|&gt;</span></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(variety_name, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="console-transcript">
<pre><code>&gt; ## We can clean column names using the clean_names() function from the janitor package.  It converts all column names to lower case and replaces spaces with underscores.
&gt; 
&gt; records_clean_names &lt;- records |&gt;
+   clean_names()
&gt; 
&gt; names(records_clean_names)
[1] "field_id"         "variety_name"     "acres"            "yield_bu_ac"     
[5] "harvest_weight"   "n_rate"           "moisture_percent"
&gt; 
&gt; ## We can remove duplicate rows using the distinct() function.  It removes any rows that are identical to another row in the dataset.  This is useful for removing accidental duplicates that may have been introduced during data entry or data processing.
&gt; 
&gt; records_unique &lt;- distinct(records_clean_names)
&gt; 
&gt; nrow(records_unique)
[1] 36
&gt; 
&gt; ## We can strip the unit text from the weights and make them numeric using the parse_number() function.  This function extracts the numeric part of a string and converts it to a numeric value.  This is useful for cleaning up data that may have been entered with units or other text.
&gt; 
&gt; records_weight_fix &lt;- records_clean_names |&gt;
+   mutate(harvest_weight = parse_number(harvest_weight))
&gt; 
&gt; records_weight_fix$harvest_weight
 [1] 297.7 476.0 172.6 476.0 642.5 561.5 222.8 561.5 138.6 264.0 226.5 256.6
[13] 481.3 402.2 269.8 249.6 234.9 225.5 418.7 283.2 177.8 323.9 431.7 492.0
[25] 365.8 150.5 226.1 252.7 120.3 191.4 268.5 237.8 189.5 195.9 386.2 185.9
[37] 215.8 255.6
&gt; 
&gt; ## We can change yields below 0 and above 200 to NA using the if_else() function.  This function allows us to create a new variable based on a condition.  In this case, we are creating a new variable called yield_bu_ac that is equal to the original yield_bu_ac variable if it is between 0 and 200, and NA otherwise.
&gt; 
&gt; records_yield_fix &lt;- records_clean_names |&gt;
+   mutate(yield_bu_ac = if_else(yield_bu_ac &lt;= 0 | yield_bu_ac &gt; 200,
+                                 NA,
+                                 yield_bu_ac))
&gt; 
&gt; summary(records_yield_fix$yield_bu_ac)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.     NAs 
  41.50   53.20   57.50   57.24   62.00   76.60       5 
&gt; 
&gt; ## We can fix the variety names in the same way using the if_else() function.  The three arguments would say if variety is one of "Brandon", "Brandon AAC", or "Brndon", then replace it with "AAC Brandon", otherwise leave it as is.
&gt; 
&gt; records_variety_fix &lt;- records_clean_names |&gt;
+     mutate(variety_name = if_else(variety_name %in% c("Brandon", "Brandon AAC", "Brndon"),
+                            "AAC Brandon",
+                            variety_name))
&gt; 
&gt; records_variety_fix |&gt;
+   count(variety_name, sort = TRUE)
# A tibble: 3 × 2
  variety_name      n
  &lt;chr&gt;         &lt;int&gt;
1 AAC Brandon      19
2 CDC Landmark     13
3 AAC Viewfield     6</code></pre>
</div>
</div>
</div>
<p>The mutate() function allows us to apply a series of transformations to the columns, including parsing numbers, replacing impossible values with NA, converting units and standardizing category names. Putting the steps together in one pipe, with a <code>rename()</code> to give the numeric columns names that carry their units:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>records_clean <span class="ot">&lt;-</span> records <span class="sc">|&gt;</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>() <span class="sc">|&gt;</span>   <span class="co"># issue 1: every column name to snake case</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>() <span class="sc">|&gt;</span>      <span class="co"># issue 3: drop the exact duplicate rows</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">variety =</span> variety_name,   <span class="co"># clearer names, with units where they matter</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">weight_t =</span> harvest_weight,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">n_rate_kg_ha =</span> n_rate,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">moisture_pct =</span> moisture_percent) <span class="sc">|&gt;</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Issue 2: strip the unit text from the weights and make them numeric</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">weight_t =</span> <span class="fu">parse_number</span>(weight_t),</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Issues 4 and 5: the -99 code, the negative and the 1250 all become NA</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">yield_bu_ac =</span> <span class="fu">if_else</span>(yield_bu_ac <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">|</span> yield_bu_ac <span class="sc">&gt;</span> <span class="dv">200</span>,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>                          <span class="cn">NA</span>,</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                          yield_bu_ac),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Issue 6: rates below 1 are t/ha, so convert them to kg/ha</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_rate_kg_ha =</span> <span class="fu">if_else</span>(n_rate_kg_ha <span class="sc">&lt;</span> <span class="dv">1</span>,</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>                           n_rate_kg_ha <span class="sc">*</span> <span class="dv">1000</span>,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>                           n_rate_kg_ha),</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Issue 7: one spelling for the Brandon variety</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">variety =</span> <span class="fu">if_else</span>(variety <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Brandon"</span>, <span class="st">"Brandon AAC"</span>, <span class="st">"Brndon"</span>),</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"AAC Brandon"</span>,</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>                      variety),</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Issue 4 again: the 9999 moisture code becomes NA</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">moisture_pct =</span> <span class="fu">if_else</span>(moisture_pct <span class="sc">&gt;</span> <span class="dv">100</span>,</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>                          <span class="cn">NA</span>,</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>                          moisture_pct)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the cleaned data</span></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>records_clean</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output-display">
<div class="console-transcript">
<pre><code>&gt; records_clean &lt;- records |&gt;
+   clean_names() |&gt;
+   distinct() |&gt;
+   rename(variety = variety_name,
+          weight_t = harvest_weight,
+          n_rate_kg_ha = n_rate,
+          moisture_pct = moisture_percent) |&gt;
+   mutate(
+     weight_t = parse_number(weight_t),
+     yield_bu_ac = if_else(yield_bu_ac &lt;= 0 | yield_bu_ac &gt; 200,
+                           NA, yield_bu_ac),
+     n_rate_kg_ha = if_else(n_rate_kg_ha &lt; 1,
+                            n_rate_kg_ha * 1000, n_rate_kg_ha),
+     variety = if_else(variety %in% c("Brandon", "Brandon AAC", "Brndon"),
+                       "AAC Brandon", variety),
+     moisture_pct = if_else(moisture_pct &gt; 100, NA, moisture_pct)
+   )
&gt; 
&gt; records_clean
# A tibble: 36 × 7
   field_id variety       acres yield_bu_ac weight_t n_rate_kg_ha moisture_pct
   &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;
 1 F001     AAC Viewfield   160        67.6     298.         97.1         12.4
 2 F002     AAC Brandon     320        54.9     476          96.2         14.7
 3 F003     CDC Landmark    120        54.4     173.         81           12.3
 4 F004     AAC Brandon     320        NA       642.        117.          15.4
 5 F005     CDC Landmark    320        65.8     562.         89.9         12.3
 6 F006     AAC Brandon     160        50.8     223.        113           NA  
 7 F007     AAC Viewfield    80        NA       139.        136.          14.5
 8 F008     AAC Brandon     160        60.3     264         127.          12.4
 9 F009     CDC Landmark    160        51.5     226.         81           13.7
10 F010     AAC Brandon     160        58.9     257.         92.4         16.4
# ℹ 26 more rows</code></pre>
</div>
</div>
</div>
<p>Check again before trusting the result. The ranges are now sane and the Brandon spellings have collapsed into one.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Check again</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The same checks on the cleaned data: sane ranges, one Brandon spelling</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(records_clean)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>records_clean <span class="sc">|&gt;</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(variety, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Write</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================================</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the cleaned file to output; the raw file is never edited</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(records_clean, <span class="st">"output/field_records_clean.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output-display">
<div class="console-transcript">
<pre><code>&gt; summary(records_clean)
      field_id       variety       acres        yield_bu_ac       weight_t    
 Length   :36   Length   :36   Min.   : 80.0   Min.   :41.50   Min.   :120.3  
 N.unique :36   N.unique : 3   1st Qu.:160.0   1st Qu.:53.05   1st Qu.:210.8  
 N.blank  : 0   N.blank  : 0   Median :160.0   Median :57.50   Median :254.2  
 Min.nchar: 4   Min.nchar:11   Mean   :184.4   Mean   :57.04   Mean   :291.4  
 Max.nchar: 4   Max.nchar:13   3rd Qu.:240.0   3rd Qu.:61.15   3rd Qu.:370.9  
                               Max.   :320.0   Max.   :76.60   Max.   :642.5  
                                               NAs    :5                      
  n_rate_kg_ha     moisture_pct  
 Min.   : 80.00   Min.   :11.60  
 1st Qu.: 89.78   1st Qu.:12.40  
 Median :103.45   Median :14.60  
 Mean   :105.85   Mean   :14.08  
 3rd Qu.:124.83   3rd Qu.:15.43  
 Max.   :135.90   Max.   :16.50  
                  NAs    :4      
&gt; 
&gt; records_clean |&gt;
+   count(variety, sort = TRUE)
# A tibble: 3 × 2
  variety           n
  &lt;chr&gt;         &lt;int&gt;
1 AAC Brandon      18
2 CDC Landmark     12
3 AAC Viewfield     6
&gt; 
&gt; write_csv(records_clean, "output/field_records_clean.csv")</code></pre>
</div>
</div>
</div>
<p>The cleaned file goes to <code>output/</code> and the raw file is never edited. If a corrected version of the raw data arrives, rerunning the script applies the same rules and rebuilds the cleaned file.</p>


</section>

</main> <!-- /main -->
<script>
// Wrap each executed chunk's console output in a collapsed <details> so
// students can predict what R will print before revealing it.
//
// Quarto has code-fold for *code*, but no equivalent for output, so we do it
// here: for every .cell-output block, build a <details class="console-fold">
// and move the output inside it. Runs once on DOMContentLoaded.
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll(".console-transcript, .cell-output").forEach(function (out) {
    // Don't double-wrap, and skip output already inside a transcript.
    if (out.closest("details.console-fold")) return;
    if (out.classList.contains("cell-output") && out.closest(".console-transcript")) return;

    var details = document.createElement("details");
    details.className = "console-fold";

    var summary = document.createElement("summary");
    // transcript = a full console session from console(); stderr =
    // messages/warnings; error = a deliberate mistake we're showing.
    if (out.classList.contains("console-transcript")) {
      summary.textContent = "Show console session";
    } else if (out.classList.contains("cell-output-error")) {
      summary.textContent = "Show R's error message";
    } else if (out.classList.contains("cell-output-stderr")) {
      summary.textContent = "Show console message";
    } else {
      summary.textContent = "Show console output";
    }
    details.appendChild(summary);

    out.parentNode.insertBefore(details, out);
    details.appendChild(out);
  });
});

// Split sidebar module labels ("Module 5: Probability and Random Variables")
// into a small number line above the title, so the module number is scannable
// and long titles stop wrapping mid-phrase. Quarto emits the whole label as one
// text node, so the split has to happen here rather than in CSS.
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll(".sidebar-item-section .menu-text").forEach(function (el) {
    if (el.querySelector(".module-label")) return;          // already split
    var m = el.textContent.match(/^\s*Module\s+(\d+)\s*:\s*(.+)$/);
    if (!m) return;                                          // not a module part

    el.textContent = "";
    var num = document.createElement("span");
    num.className = "module-label";
    num.textContent = "Module " + m[1];
    var title = document.createElement("span");
    title.className = "module-title";
    title.textContent = m[2];
    el.appendChild(num);
    el.appendChild(title);
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/agdataanalytics\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./module03a.html" class="pagination-link" aria-label="Getting Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Getting Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./module03c.html" class="pagination-link" aria-label="Merging Data">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Merging Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>